### ISSUE TITLE
Issue with Applying Snapshot/Wallet Backup

### ISSUE THREAD

**Issue by pmjlaw** [DeFiCh/app#1005]
#### How to reproduce it (as minimally and precisely as possible):
transferred first DFI coins today
after couple of hours sync was staying between 99.9% and not moving
so ì decided to apply a snapshot and since then the unpacking is not moving in the past 10 hours or so, additionally not able to backup wallet, the window to backup appears but it is not saved in library, although even previously attempted (before applying the snapshot). 
[Archive.zip](https://github.com/DeFiCh/app/files/6890624/Archive.zip)

1. Download snapshot
2. Snapshot was successfully downloaded but now the screen with applying snapshot (unpacking) is at the same level for the past 10 hours
3. cannot backup wallet - the window to save the backup appears but not able to locate the backup in the library

#### What are your environment parameters?

- DeFi Wallet Version: 2.5.2
- Operating System (OS): macOS 11.5.1
- Current free storage capacity: 14.36 GB

**Comment by pmjlaw** [comment]
![Screenshot 2021-07-28 at 08 07 25](https://user-images.githubusercontent.com/88074488/127273191-701c68ea-ccec-4a72-91a4-d6e77fe05368.png)
pls find attached the screenshot

**Comment by izzycsy** [comment]
Hi @pmjlaw , thanks for the screenshot, while the snapshot is unpacking — this usually takes about 20minutes to unpack. If could be the RAM of your Mac is full, try to clear some space and not run more than 3 applications on your MAC while running the snapshot. Run snapshot again. If you still face a similar issue after re-trying, send logs & screenshot. Thank you.

**Comment by pmjlaw** [comment]
thanks a lot for quickly getting back, this unpacking takes more than 10 hours now :( 
Not able to run a snapshot again, nor to make any other action. Please see earlier attached logs, can of course try to pull those again. 

I am wondering what happens with my wallet. I tried to backup and saved with different names but I cannot find those, however can find a wallet.dat 

Thanks a lot for your help!

**Comment by pmjlaw** [comment]
[Archive.zip](https://github.com/DeFiCh/app/files/6891852/Archive.zip)
Pls find attached the new zip logs, thanks!

**Comment by izzycsy** [comment]
Hi @pmjlaw , try the following: 
1. Force quit the app
2. Clear storage space
3. Backup the **entire** `wallets` folder, you can copy & paste it on an external drive, personally I store it in `Documents`

In the `wallets` folder you'll likely see `wallet-bak-123456789` as well, these are additional backups. 

##### For Mac, it's located here:  Go To Folder
`/Users/<username>/Library/Application Support/Defi/wallets/`

<img width="459" alt="Mac - Go To Folder" src="https://user-images.githubusercontent.com/65014479/127307153-1a0555b9-10fe-4d03-aa89-a88f8a4cb8d6.png">

<img width="822" alt="wallet dat location" src="https://user-images.githubusercontent.com/65014479/127307204-1763db92-86bd-423d-bc2c-ff4ae7286c08.png">

4. Once you've backup-ed the `wallet.dats`, ensure you're not running more than 3 applications on your MAC
5. Open DeFi Wallet app, most likely you'll face an error `node is disconnected`, this is because the app was forcefully quit (step 1), refer to the follow [guide to reindex](https://github.com/DeFiCh/app/discussions/899)

**Comment by pmjlaw** [comment]
many thanks @izzycsy :) I have followed the steps however now it shoes 0 for my tokens, how can I load my backed up wallet? :(

**Comment by izzycsy** [comment]
Hi @pmjlaw , okay great that you managed to sync, refer to this guide to [Restore Wallet](https://github.com/DeFiCh/app/discussions/988).

**Comment by pmjlaw** [comment]
dear @izzycsy sorry for all the questions, trying to avoid issues and hope to retrieve my coins, pls see the screen I am at currently, I do not see an option to restore wallet from backup
![Screenshot 2021-07-28 at 13 59 28](https://user-images.githubusercontent.com/88074488/127319767-95c1e42d-6ab2-4a19-866a-76c7d5e56860.png)

**Comment by pmjlaw** [comment]
I am also wondering if for whatever reason when i tried to backup the wallet, it did not work - app froze is there any mechanism to automatically save the latest version of the wallet to be able to retrieve it? I think this should be really a very crucial requirement.

It is interesting that I can see still my wallet address but where are the coins? if it is all on one blockchain we can easily verify that i have not transferred them anywhere, is there any way to get my coins back?

**Comment by izzycsy** [comment]
Hi @pmjlaw , anything you want to perform on the app can only happen after synchronisation to reaches 100%, your balances should reflect then.

**Comment by pmjlaw** [comment]
Thanks super @izzycsy thanks :) waiting for the good news! would confirm asap at 97.41% now

**Comment by pmjlaw** [comment]
Thanks G-d, my money is back! love you @izzycsy!

**Comment by izzycsy** [comment]
Hi @pmjlaw , good to hear! Please make a backup of your `wallet.dat` for safe keeping. 

<img width="269" alt="Menu bar   Backup Wallet" src="https://user-images.githubusercontent.com/65014479/127334517-c10301ef-4ae2-42a6-b09d-5e826a40cc98.png">
