### ISSUE TITLE
problems with the console

### ISSUE THREAD

**Issue by cryptopinky** [DeFiCh/app#1028]
#### Actual behavior:
Hi there. I've got several problems since i came back from holiday at the beginning of august. First my wallet didnt synchronized anymore and i just saw my DFI Token on the wallet but not my LM pair and my dBTC.
After i reinstalled the wallet the synchronisation problem is solved,but i still dont see my dBTC and LM Pair. And the other problem is, that the console doesn't react if i#m typing something in. Hope somebody can help me with that problem. 

sorry for my bad english! 

#### What are your environment parameters?

- DeFi Wallet Version: 2.6.2
- Operating System (OS): win10
- Current free storage capacity: 200GB

**Comment by izzycsy** [comment]
Hi @cryptopinky ,are you synced to 100%? Do you have a screenshot of your issue? Can you also attached your logs please, it'll help with the investigation.

**Comment by izzycsy** [comment]
Hi @cryptopinky , update [v2.6.3](https://github.com/DeFiCh/app/releases/tag/v2.6.3) is out.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by cryptopinky** [comment]
I still have the same problems with the update.

**Comment by izzycsy** [comment]
Hi @cryptopinky , I'm unable to investigate your issue further since I do not have a visual or logs. Are you synced to 100%? 

You can try to [Restore Wallet via Backup](https://github.com/DeFiCh/app/discussions/988). 

#### * If you _have not_ backup your wallet before, go to the `menu bar` and select `backup wallet`.  

<img width="269" alt="Menu bar   Backup Wallet" src="https://user-images.githubusercontent.com/65014479/123797850-33b76980-d919-11eb-8305-b8e9e2760416.png">

#### 1. Click on `Exit` icon & ensure app is 100% synchronized (green tick at bottom left hand corner), select `Restore wallet via backup` (wallet.dat)

<img width="236" alt="Exit Wallet" src="https://user-images.githubusercontent.com/65014479/131712262-381d814a-860a-4f50-885d-37e07348cce6.png">

<img width="1017" alt="Restore wallet from backup" src="https://user-images.githubusercontent.com/65014479/123794687-b50cfd00-d915-11eb-9950-a797b5b6e5c0.png">


#### 2. A window should pop up, direct the app to your `wallet.dat` location
• In the wallets folder you'll likely see wallet-bak-123456789 as well, these are additional backups. 
• Select the `wallet.dat` 
***Note: the `wallets` folder is a default location and should not be moved**

<img width="1016" alt="Restore   Select folder of backup1" src="https://user-images.githubusercontent.com/65014479/123795070-2ea4eb00-d916-11eb-9af3-ee436bba7c30.png">


#### 3. Another possible scenario, could be that you saved it in another folder. 
• For example, I saved the `wallet backup` in `Documents/_BACKUP`
• Hence, I'd **redirect** the app to the folder `Documents/_BACKUP`, and select the `wallet.dat`

<img width="1019" alt="Restore   Select folder of backup2" src="https://user-images.githubusercontent.com/65014479/123795291-73308680-d916-11eb-9dc6-73d0240c8678.png">


Leave the app to run for awhile, your balances should reflect as per the `wallet.dat` selected.

**Comment by izzycsy** [comment]
Hi @cryptopinky , is your issue resolved? The latest version is [v2.6.5](https://github.com/DeFiCh/app/releases/tag/v2.6.5), if you've not updated.

**Comment by izzycsy** [comment]
Hi @cryptopinky  update [v2.7.0](https://github.com/DeFiCh/app/releases/tag/v2.7.0) is out, this is a **mandatory update**. Kindly `backup wallet` before updating.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @cryptopinky , update [v2.7.1](https://github.com/DeFiCh/app/releases/tag/v2.7.1) is out, this is a **mandatory update**. Kindly `backup wallet` before updating.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Update [v2.10.0](https://github.com/DeFiCh/app/releases/tag/v2.10.0) is out, this is a **mandatory update**. Kindly `backup wallet` and read through the release notes before updating. _This comment is to notify you about the update._

If your issue persists, you may create a new one and elaborate on your issue.
