### ISSUE TITLE
v2.6.3 – App Freezes

### ISSUE THREAD

**Issue by ChrKlaHH** [DeFiCh/app#1033]
Hi,

I downloaded the current version 2.6.3 (MacOS 11.5.2) and downloaded the snapshot. Since the restart of the app it freezes, just showing the logo and nothing else happens. I tried to start manual via the Package Contents but it shows an error in the Terminal: 15:24:27.806 › [blockChainNotStarted - Not Running] ""

When I run the defid file it shows the following:

![grafik](https://user-images.githubusercontent.com/89588885/130970915-5745968c-411f-4f84-82c8-5ae2b912c326.png)

Restart of the Computer and Delete-Reinstallation does not help.

- DeFi Wallet Version: 2.6.3
- Operating System (OS): 11.5.2
- Current free storage capacity: 126GB

#### Anything else we need to know?

[Logs.zip](https://github.com/DeFiCh/app/files/7060113/Logs.zip)

**Comment by ChrKlaHH** [comment]
OK, looks like I have to switch to the mobile App. Luckily I had no assets in my Desktop wallet yet.

**Comment by izzycsy** [comment]
Hi @ChrKlaHH , apologies for the delayed reply. Based on your logs, the app is unable to find the data directory — hence the suggested reinstallation. Or perhaps even [delete all files and reinstall again](https://github.com/DeFiCh/app/discussions/964), which is a hassle. If it still does not work, could be a node issue and you might have to open an issue on <https://github.com/DeFiCh/ain>. 

Since you're using the mobile app, please keep your 24 recovery word safe — write on paper and save it somewhere only you know and have access to. May I close this issue then? Or do you want to try the above workaround provided first? Thank you.
