### ISSUE TITLE
DFI Masternode Rewards not Credited into Wallet

### ISSUE THREAD

**Issue by Gravbet** [DeFiCh/app#1054]
Hi All
I have my DFI Masternode running through the DeFi Wallet since 17 days and successfully minted my first Block on Oct 17th. However, after that I did not mint any new Block until now.
Today, I suddenly realised that my transaction history actually shows 4 additional "block rewards" after my first successful one on Oct 17th. These rewards were never received in my wallet though and when checking the transactions in the Defi Explorer, it says that it has (still) not been confirmed.
Thanks

- DeFi Wallet Version: 2.6.2
- Operating System (OS): Raspberry Pi
- Current free storage capacity: 20GB

Sample transaction of the 4 not received rewards:
90737dea38e225187e26ca3ce9ae2c153bcc7027035754a36f788ad294e77642

<img width="704" alt="image" src="https://user-images.githubusercontent.com/93462269/139569712-68951792-b32b-4d02-91d5-418eb91c902b.png">

**Comment by izzycsy** [comment]
Hi @Gravbet , could be because you're on an older node version, kindly `backup wallet` and proceed to update to the latest [version 2.6.5](https://github.com/DeFiCh/app/releases/tag/v2.6.5). Please read the release notes before updating. For future enquiries regarding masternode, you can ask on [DeFiChain Masternode](https://t.me/DeFiMasternodes) as well.

**Comment by Gravbet** [comment]
> Hi @Gravbet , could be because you're on an older node version, kindly `backup wallet` and proceed to update to the latest [version 2.6.5](https://github.com/DeFiCh/app/releases/tag/v2.6.5). Please read the release notes before updating. For future enquiries regarding masternode, you can ask on [DeFiChain Masternode](https://t.me/DeFiMasternodes) as well.

Hi @izzycsy 
I am running my node on Raspberry Pi OS, would the liked V2.6.5 run properly?
Thanks

**Comment by izzycsy** [comment]
Hi @Gravbet , yes, please `backup wallet` and update to the latest app version. It is advised to be on the latest node version; especially since you're running a masternode. For future enquiries, you can ask on [DeFiChain Masternode Telegram](https://t.me/DeFiMasternodes).

<img width="269" alt="Menu bar   Backup Wallet" src="https://user-images.githubusercontent.com/65014479/140681935-7ce90ad7-5812-4638-948b-3ee768f85117.png">

**Comment by izzycsy** [comment]
Hi @Gravbet , update [v2.7.0](https://github.com/DeFiCh/app/releases/tag/v2.7.0) is out, this is a **mandatory update**.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @Gravbet , update [v2.7.1](https://github.com/DeFiCh/app/releases/tag/v2.7.1) is out, this is a **mandatory update**. Kindly `backup wallet` before updating.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @Gravbet , update [v2.7.2](https://github.com/DeFiCh/app/releases/tag/v2.7.2) is out , there's an update node included in this release. I'd highly recommend that you follow [DeFiChain Masternode](https://t.me/DeFiMasternodes), as Masternode users are on that channel and you'll be regularly updated. I'll be closing this issue in the mean time, if you've a new issue regarding Masternode, you can post it in [DeFiCh/ain](https://github.com/DeFiCh/ain/issues). Thank you.
