### ISSUE TITLE
DUSD-DFI transfer not carried out

### ISSUE THREAD

**Issue by steffenHberlin** [DeFiCh/app#1104]
#### What are your environment parameters?

- DeFiCh/app Version: 2.8.1
- Operating System (OS): macOS Monterey
– RAM (GB): 16 GB
– CPU (Intel Core i5/i7/etc.): 2,6 GHz 6-Core intel Core i7
- Current free storage capacity: 230 GB

#### Anything else we need to know? thde transfer from my mobile wallet to the desktop wallet app worked

[app logs.zip](https://github.com/DeFiCh/app/files/7740604/app.logs.zip)
<img width="1337" alt="Senden" src="https://user-images.githubusercontent.com/96372545/146671401-426e30a4-e71d-4ceb-adc8-72b7365821fc.png">
<img width="1068" alt="screenshot transaction" src="https://user-images.githubusercontent.com/96372545/146671408-0ef37121-980d-4f9c-9622-eac681032ee3.png">

**Comment by izzycsy** [comment]
Hi @steffenHberlin , your transaction seems to be [confirmed](https://defiscan.live/address/df1qv8g9v6smxeyyn426z50yvcmxsu2c6r7e7c4w9x). Can you double check the address is correct on your mobile light wallet?

**Comment by steffenHberlin** [comment]
I've checked my light wallet adress, it is correct.

**Comment by izzycsy** [comment]
Hi @steffenHberlin , if you're using the same 24 words then yes, there's one address tag to your seed. Unless you created a 2nd address from on your current 24 words account, then you'll have 2 addresses to manage.

**Comment by izzycsy** [comment]
Hi @steffenHberlin , update [v2.9.1](https://github.com/DeFiCh/app/releases/tag/v2.9.1) is out, this is a **mandatory update**. Kindly `backup wallet` and read through the release notes before updating. _This comment is to notify you about the update._

Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Thank you.
