### ISSUE TITLE
Node Disconnected each time I try to move my funds. 

### ISSUE THREAD

**Issue by CryptoPetitioner** [DeFiCh/app#1215]
#### What are your environment parameters? I'm using the desktop version of the DEX on a mac. 

- DeFiCh/app Version: I'm in version 2.17.1
- Operating System (OS): MacOS Big Sur
– RAM (GB): 4
– CPU (Intel Core i5/i7/etc.): 1.6 GHZ Dual Intel Core i5
- Current free storage capacity: only using 900 GB of 1 TB

#### Anything else we need to know? It works for every other pair, I removed BTC/DFI and DUSD/DFI no problem. 

 Not sure what this is.

**Comment by izzycsy** [comment]
Hi @CryptoPetitioner , [v2.18.0](https://github.com/DeFiCh/app/releases/tag/v2.18.0) is out. Please read through the release notes before updating. Give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs, and we may reopen this issue. Thank you.
