### ISSUE TITLE
Transactions not shown correctly

### ISSUE THREAD

**Issue by AndErazor** [DeFiCh/app#146]
My Defi app does show some transactions wrong. 

 I have recognized, that there was a change in how LM transactions are shown. My earlier transactions are shown separately, for example in the BTC wallet - BTC, in the DFI wallet - DFI and in the BTC-DFI Poolwallet +BTC-DFI all with the same transaction ID and correct amount.

Since a few day newer LM transactions are showing with pairs in the different wallets, but only showing 2 instead of all three involved tokens. For example I see in my BTC wallet a removal of LM fund like - BTC-DFI pool token and + BTC token (both in the BTC wallet) and a corresponding DFI +  and - BTC-DFI transaction in the DFI wallet. So all good but still not ideal (would be showing all involved tokens).

Unfortunately I have two transactions where I don't see the one of the involved tokens at all. The BTC wallet shows + BTC-DFI and - DFI, the DFI wallet shows the same. So I don't see how much BTC was transferred in the transaction at all.

I did reindex the my wallet but this doesn't seem to solve the problem.

<img width="1026" alt="Bildschirmfoto 2020-12-19 um 18 01 26" src="https://user-images.githubusercontent.com/22431911/102695076-6aebe600-4225-11eb-82cd-1f5547379ee4.png">

**Comment by izzycsy** [comment]
Hi @AndErazor , apologies for the delayed reply. You may try to click on `Include Rewards` to provide more insights to your transaction. 
<img width="795" alt="Include rewards" src="https://user-images.githubusercontent.com/65014479/104160768-a21c7400-542c-11eb-9ced-f3e56a497a8d.png">

Update v2.1.6 is out <https://defichain.com/downloads/>. 
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue w new information (include screenshots) and your app logs. Thank you.
