### ISSUE TITLE
DFI transfer from pool to wallet lost

### ISSUE THREAD

**Issue by DeFiDirk** [DeFiCh/app#191]
![Screenshot 2020-12-28 160851](https://user-images.githubusercontent.com/74500775/103223659-0a486180-4927-11eb-9204-42808624891d.jpg)

After updating from 2.1.3 to 2.1.4 backup wallet could not be imported (no access to the button "import wallet" - just in grey colour).
So I restored my wallet by the mnemonic seed. Now the transfer (Txid:
bd9238a47b75995a24eb3ba69387e2bc75140a65d953647c99ba10d2e34d92f7) of 845 DFI is not shown in the wallet.
I tried to put in the old receiving address, but I get the message "Address already exists", I am sure it is mine but I cannot confirm in that app.
How do I get the 844 DFI in my wallet now?

Thanks for your help.

Regards Dirk

**Comment by izzycsy** [comment]
Hi @DeFiDirk , thanks for your feedback & screenshot. Could you check your balance with the following commands: 

`getbalance` — utxo DFI 
`getokenbalances` — DFI 

 The sum of utxo DFI & DFI would be your actual DFI.

**Comment by izzycsy** [comment]
Hi @DeFiDirk , I'm unable to see anything for txid `bd9238a47b75995a24eb3ba69387e2bc75140a65d953647c99ba10d2e34d92f7`, could you double check. You may also try the `reindex option` in Settings. 

<img width="993" alt="Settings   Reindex option" src="https://user-images.githubusercontent.com/65014479/104300545-98b10b80-5501-11eb-8d80-d87d92387ce4.png">

In the mean time, update v2.1.6 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and your app logs. Thank you.
