### ISSUE TITLE
can not add liquidity

### ISSUE THREAD

**Issue by Anlien75** [DeFiCh/app#205]
All,
I can not add or remove liquidity there is an insuffucient UTXOS to perform add liquidity.
Installation on Windows 10 Rev. 2.1.4.
Wallet restored by using mnemonic seed.
Initial installation was the previous release. 2.1.3.

![image](https://user-images.githubusercontent.com/76808716/103402903-8d97cc00-4b4e-11eb-98bd-9193f4591cca.png)

Regards Andy

**Comment by booky84** [comment]
maybe try this workaround to fix the problem. 

[https://github.com/DeFiCh/app/issues/192#issuecomment-752864650](url)

**Comment by booky84** [comment]
[https://github.com/DeFiCh/app/issues/192#issuecomment-752864650](url)

Try this to fix.

**Comment by booky84** [comment]
you can try this. 

#192

**Comment by Anlien75** [comment]
Thanks for help.

Step 1 and 2 are able. 

But i didn't find any owner-Address in the skript. This line are empty.
I used the Address (8J....)  from my wallet but it didn'n works. (Replay are... does not refer to any valid address).

Where can I find it?


Regards Andy

**Comment by Anlien75** [comment]
Thanks for Info. 

But I can`t doing step four. I find no owner address. 

There are al lot of Blocks (maybe 30) wich content the content of Token, sometimes with small amount of (0,25, 0,1, 2,2) Tokens. 44 are available now. 

Have I to convert all of this small amoint each?

On this step I despair.

![image](https://user-images.githubusercontent.com/76808716/103483647-fef2ab80-4de8-11eb-9c26-1f8dcc54345a.png)

Regrads Andy

**Comment by izzycsy** [comment]
Hi @Anlien75 , thanks for your feedback. There’s a temporary solution to this, it could be that you've too little DFI UTXOs balance (min. 0.05DFI) — which is required to perform swap and other functions. You could try convert a little DFI tokens to DFI UTXOs, and see if it works. Attached a link that might help you.  <https://www.reddit.com/r/defiblockchain/comments/kb10d3/stepbystep_changing_dfitoken_to_dficoin/>

If you're stuck you could seek help from the Community as this guide was created from one of them. 

DeFiChain Telegram (EN): <https://t.me/defiblockchain> DeFiChain Telegram (DE): <https://t.me/defiblockchain_DE>

If it's an error, I do need your app logs in order to let the team investigate. Thank you.

**Comment by Anlien75** [comment]
Hello,

I have solved the problem differently.  
I bought DFI through Bittrex and sent to my wallet. 

Now it is running again. It is important not to have too little DFI. One DFI should always remain in the wallet. 

Thanks for your support.

Greetings Andy

**Comment by izzycsy** [comment]
Hi @Anlien75 , thanks for the update. I'll keep this issue open for now so others may still refer to it. Thank you.

**Comment by izzycsy** [comment]
Hi @Anlien75 	, update v2.1.7 is out <https://defichain.com/downloads/>.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and your app logs. Thank you.
