### ISSUE TITLE
Unable to start blockchain

### ISSUE THREAD

**Issue by KouLiTo** [DeFiCh/app#213]
[app wrong.log](https://github.com/DeFiCh/app/files/5761553/app.wrong.log)

Hello. I have a problem to Start the Application DeFiChain. I cant start it. When I start it, it doesnt start and i see only "Unable to start Blockchain" and that is all. I already made many things to fix it like making RAM larger but it didnt help. It wont load the blockchain. Please help me.

**Comment by izzycsy** [comment]
Hi @KouLiTo , thanks for your app log, will forward this to the team. Please give us time to investigate this issue. Thank you.

**Comment by izzycsy** [comment]
Hi @Grega-bot , do you have screenshot of the error? Also, kindly send your app logs. This will provide more insight for the investigation. Thank you.

  In the mean time, kindly install the latest version v2.1.6 of the app <https://defichain.com/downloads/>.

**Comment by izzycsy** [comment]
Hi @KouLiTo , update v2.1.6 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, please provide new information (include screenshots) and your app logs. Thank you.

**Comment by izzycsy** [comment]
Hi @KouLiTo , regarding the issue `Unable to start blockchain`, I'll link you to <https://github.com/DeFiCh/app/issues/155> which we can further discuss on the problem. We would like to keep same issues in one thread. The team is currently investigating this. Thank you. 

Hi @Grega-bot , I've informed the team to look out for your email, alternatively, you can send your logs to <https://github.com/DeFiCh/app/issues/155>, so that I can escalate it. 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/104440968-01fe5080-55ce-11eb-9403-424dc3db01d9.png">
<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/104440977-0460aa80-55ce-11eb-9d9b-7e1fba03cd3e.png">
