### ISSUE TITLE
Wallet not showing up

### ISSUE THREAD

**Issue by sunburniesanders** [DeFiCh/app#225]
just like issue #220 
[app log.log](https://github.com/DeFiCh/app/files/5768678/app.log.log)
it also wont let me send the compressed zip

**Comment by izzycsy** [comment]
Hi @sunburniesanders , thanks for your feedback. May I know the OS + version no. you're using? Well received on the app logs. Please give us time to investigate this issue.

**Comment by izzycsy** [comment]
Hi @sunburniesanders 	, update v2.1.7 is out <https://defichain.com/downloads/>.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, please leave a comment on <https://github.com/DeFiCh/app/issues/220> with your new information (include screenshots) and app logs. Thank you.
