### ISSUE TITLE
Cannot withdraw ETH and USDT out of DEX

### ISSUE THREAD

**Issue by mikej289** [DeFiCh/app#232]
After some app crashes and several errors, I am not able to withdraw ETH & USDT to Cake. I am able to swap those tokens for DFI on the DEX though. I am always getting an UTXO error when trying to withdraw it. I am fully aware of the workaround for DFI (DFI token to coin) but performing the same steps for ETH & USDT creates an error in the console. 

Things I did so far using the console:
.) Sent small DFI to all DFI addresses in use by calling listaccounts {} false false true
.) Converted all DFI token to coins using utxostoaccount
.) Tried to apply the same utxostoaccount to USDT & ETH - got error message, telling me only allowed for DFI
.) Sending in ETH & USDT from Cake - credited successfully 

Error I am getting when trying to send out ETH & USDT: "Not enough balance on wallet accounts, call utmost account to increase it."

**Comment by izzycsy** [comment]
Hi @mikej289 , thanks for your feedback and for trying the workaround. Kindly send your app logs. If possible, do attach screenshots / screen recordings. This will provide more insight for the investigation. Thank you.

**Comment by mikej289** [comment]
The app logs & screenshots have already been sent via David L.

**Comment by izzycsy** [comment]
Hi @mikej289 , nice to e-meet you. Your logs are well received, please give us time to investigate this issue.

**Comment by izzycsy** [comment]
After reviewing your case, here's an update. For _existing issue_, the team is in the midst of fixing them. For _new issue_, please give us time to investigate it. Thank you.

<img width="283" alt="210106 v2 1 5 MN - Wallet - JavaScript error" src="https://user-images.githubusercontent.com/65014479/103884947-43988280-511a-11eb-89c2-3eee682d6333.png">
<img width="874" alt="210106 v2 1 5 MN - Wallet - corrupted block" src="https://user-images.githubusercontent.com/65014479/103884999-57dc7f80-511a-11eb-81df-1bdf6a005225.png">

**Issue 1**
_New issue:_ `JavaScript error occurred in the main process`
Existing issue:_ `Corrupted block database detected. Please restart with -reindex or -reindex-chainstate to recover. Do you want to restart?`


<img width="292" alt="210106 v2 1 5 MN - Wallet - status 500" src="https://user-images.githubusercontent.com/65014479/103885183-940fe000-511a-11eb-92bd-1481a80a11c7.png">

**Issue 2**
_New issue:_ `Request failed with status code 500`


<img width="621" alt="210106 v2 1 5 MN - Wallet - call utxostoaccount to increase it" src="https://user-images.githubusercontent.com/65014479/103885259-b0ac1800-511a-11eb-8a35-d25662cf6549.png">

**Issue 3**
_Existing issue:_ `Not enough balance on wallet accounts, call utxostoaccount to increase it`


<img width="874" alt="210106 v2 1 5 MN - Wallet - corrupted block" src="https://user-images.githubusercontent.com/65014479/103885305-c4f01500-511a-11eb-8965-a6f5cd83746e.png">

**Issue 4**
_Existing issue:_ `Corrupted block database detected. Please restart with -reindex or -reindex-chainstate to recover. Do you want to restart?`

Temporary solution:
wait for blockchain to sync to 100% to continue using app. However, it’ll take quite awhile to load, current block is at 556,166.
I faced the same error and it takes me about 1–2hrs to sync, the lesser apps you run in your mac the better because DeFi app is going to take up a lot of RAM due to the bug.

**Comment by Huzi1988** [comment]
are there any solutions? because i have the same problem and cannnot pay out my ETH´s or BTC´s back to the cake pool page.

**Comment by mikej289** [comment]
Seems like not yet. I tried all suggested solutions so far and nothing worked so far.

**Comment by floxcgncgn** [comment]
Hello. I have the same problem with, can not send (withdraw) usdt from dex definchain to cake. "Not enough balance on wallet accounts, call utxostoaccount to increas it". So i have a lot of balance and dfi is enough there...whats the problem=

**Comment by DanielZirkel** [comment]
@Huzi1988 @mikej289 @floxcgncgn 
The following workaround via console worked in my case
https://www.reddit.com/r/defiblockchain/comments/kvsw4l/stepbystep_workaround_sending_btc_eth_usdt_and/

**Comment by mikej289** [comment]
awesome! Thx for the article 👍

**Comment by izzycsy** [comment]
Hi @Huzi1988 @mikej289 , regarding the issue `Unable to send BTC / ETH / USDT`, kindly refer to <https://github.com/DeFiCh/app/issues/195> which we can further discuss on the problem. I'll keep you guys update on that issue there. Thank you. 

Thank you @DanielZirkel !

**Comment by izzycsy** [comment]
Hi @mikej289 	, update v2.1.6 is out <https://defichain.com/downloads/>.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and your app logs. Thank you.
