### ISSUE TITLE
The app synchronised 100%, after a while the screen get grey

### ISSUE THREAD

**Issue by user1950** [DeFiCh/app#234]
When the app synchronised 100%, I could use it for a while and the screen turned grey.
Closed the wallet, waited till the app dissapeared in task manager,
restarted windows and opened the app again.
synchronisation stated at the beginning, then the same problem

[binary.zip](https://github.com/DeFiCh/app/files/5776256/binary.zip)
[app.zip](https://github.com/DeFiCh/app/files/5776228/app.zip)
[appconfig.zip](https://github.com/DeFiCh/app/files/5776229/appconfig.zip)

Windows 10
8gb ram
defi-app v2.1.5

same problem in defi-app v2.1.4

**Comment by izzycsy** [comment]
Hi @user1950 , thank you for the feedback, logs are well received. Please give us time to investigate this issue.

**Comment by user1950** [comment]
I installed v2.1.3 yesterday and it works. Also I was able to add some liquidity to the pool.

**Comment by izzycsy** [comment]
Hi @user1950 , update v2.1.6 is out <https://defichain.com/downloads/>. You may continue to use 2.1.3 if it works for you, we do launch releases quite regularly. 

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and your app logs. Thank you.
