### ISSUE TITLE
Send coins not received by target address (USDT)

### ISSUE THREAD

**Issue by guiphil** [DeFiCh/app#253]
Hello, 

I've send 3 USDT (DeFi App 2.1.6, Windows 10) from `8X2fB6Yg8H9i95QLUo5aVPbNfWa9pAeEbb` to `dQsR5cHyw9vNz8Mu14GaFowpwSFatMcQv4`.
 Txid `461116cbed4159691a8cbab38095981a34be29fe75f6205514df98660a815c0c`

The transaction currently has 40+ confirmations, still the target address did not receive any funds.
According to [explorer.defichain.io](explorer.defichain.io) the last transaction on the target address was on the 10th December. 

What also confused me is that none of the target or source address can be found in transaction on [explorer.defichain.io](explorer.defichain.io).

[app.log](https://github.com/DeFiCh/app/files/5792974/app.log)
[binary.log](https://github.com/DeFiCh/app/files/5792975/binary.log)

**Comment by izzycsy** [comment]
Hi @guiphil , thanks for your feedback. Is your balance reflected correctly on your Wallet screen? You can check your balances with the following commands via CLI: 

`getbalance` — utxo DFI
`gettokenbalances` — DFI  

> The sum of utxo DFI & DFI would be your total tokens.

`listaccounts {} true true true` — breakdown of your coin(s) / token(s)

**Comment by guiphil** [comment]
Hi @izzycsy , after a day of waiting the funds arrived. 

But I'm still wondering why the *from* and *To* addresses in the transaction `461116cbed4159691a8cbab38095981a34be29fe75f6205514df98660a815c0c` are not the same as my the actual *from* and *to* addresses mentioned above. 

Do you why that is? I'm just keen to know, otherwise this issue can be closed.

**Comment by izzycsy** [comment]
Hi @guiphil , good to know! If you transferred from Cake, as I understand; due to the increase in volume of transactions, the waiting time could be up to 72hrs. 

Regarding your question, I did some research and it could be that, and I quote from the article: "_because the wallet is built on an HD (hierarchical deterministic) framework, a privacy-centered method for address generation and management. Each public bitcoin address your wallet generates stems from your wallet's xPub (or Extended Public Key). Once a public address receives an incoming payment, a new address will automatically be generated and display._

_While previously used bitcoin addresses remain valid and can always be used to receive funds multiple times, if you use the same address each time you receive funds, it becomes easy for anyone to track your entire payment history. This method of address generation improves privacy by automatically presenting you with a new address when you’re expecting a new payment._". 

Although, don't take my word for it, I may be wrong myself. 

Thanks for your patience on this matter, I'll proceed to close this Issue.
