### ISSUE TITLE
2.1.7 Bricked Liquidity Mining and Swap Tether

### ISSUE THREAD

**Issue by TheWeeezel** [DeFiCh/app#281]
So after the update there is no way you can add funds to liquidity mining and no chance to swap for tether. 

After downgrading to 2.1.6 i could swap but could not provide liqudity either in 2.1.6 or 2.1.7. 

In my opinion you bricked something with this upgrade. QA is the most important position in a software house :)

**Comment by izzycsy** [comment]
Hi @TheWeeezel , I suppose you're referring to this issue <https://github.com/DeFiCh/app/issues/280>. I'll proceed to close this issue as we would like to keep same issues in one thread. Unless your issue is different, you may reopen. Please send your app logs and screenshots if you do so. Thank you.
