### ISSUE TITLE
Add LP / Add-on auth TX failed: Insufficient funds

### ISSUE THREAD

**Issue by MarsaXod** [DeFiCh/app#312]
Hi @izzycsy,

After the last update got another error message as described in the subject. 

[applog 2.1.10.log.zip](https://github.com/DeFiCh/app/files/5821360/applog.2.1.10.log.zip)

![Capture](https://user-images.githubusercontent.com/77227016/104744310-03a25280-574d-11eb-80d8-9c8c1cd18864.PNG)

**Comment by izzycsy** [comment]
Hi @MarsaXod , thanks for your feedback. Please give us time to investigate this issue.

**Comment by izzycsy** [comment]
Hi @RoyDD87 , I understand that you're facing this issue as well. Could you send you app logs again please? It can't be expanded. 

<img width="374" alt="Screenshot 2021-01-20 at 5 15 53 PM" src="https://user-images.githubusercontent.com/65014479/105153373-51e79500-5b43-11eb-86aa-7cef2dfd1d9a.png">

**Comment by izzycsy** [comment]
Hi @MarsaXod @RoyDD87 , could you try sending 1 DFI to your account — used for transaction fees. It could be that you've insufficient DFI. Do let me know the outcome. Thank you.

**Comment by MarsaXod** [comment]
Hi @izzycsy,

I have tried already, I sent 5DFI to the account and looks like all back to normal.

**Comment by RoyDD87** [comment]
Hello, here is the Zipp file. I hope you can open you

[Applogs.log](https://github.com/DeFiCh/app/files/5844087/Applogs.log)

**Comment by RoyDD87** [comment]
I sent 5DFI to the account and it didn't work out

**Comment by RoyDD87** [comment]
![Uploading 20210120_182012.jpg…]()

**Comment by RoyDD87** [comment]
I still have the problem that since the last synchronization I also have fewer tokens than before in Liquidity Mining. Thank you for your support

**Comment by RoyDD87** [comment]
[applogs.zip](https://github.com/DeFiCh/app/files/5844921/applogs.zip)

**Comment by RoyDD87** [comment]
[applogs.zip](https://github.com/DeFiCh/app/files/5844934/applogs.zip)

**Comment by RoyDD87** [comment]
[Uploading debuglog.zip…]()

**Comment by RoyDD87** [comment]
The binary file is too large. What can I do. by email?

**Comment by izzycsy** [comment]
Hi @RoyDD87 , well received, it's okay. Please give us time to investigate this. Thank you.

**Comment by INQB1** [comment]
I have the same issue on the DEX. Trying to swap BTC or ETH to DFI returns the error: 
Add-on auth TX failed: Insufficient funds.

**Comment by INQB1** [comment]
Same issue here: 
"recipient () does not refer to any valid address"
when trying to add to liquidity mining. 
I assume you're still working on the solution, or is there a workaround available already? 
Thx.

**Comment by INQB1** [comment]
I upgraded to 2.1.12 and the issues still persists. This is really annoying. Looks like people had the same issue in previous versions and it keeps coming back. I guess I can't do LM then until a newer version fixes it.

**Comment by izzycsy** [comment]
Hi @RoyDD87 , update v2.1.12 is out <https://defichain.com/downloads/>.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, kindly send your logs. Thank you. 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/105638009-70cf8980-5eab-11eb-84fe-9618426fba83.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/105638013-7331e380-5eab-11eb-88d4-fcc062efa287.png">

**Comment by izzycsy** [comment]
Hi @INQB1 , thanks for your feedback. I understand the frustration, I assure you that the team is constantly working on improving the app and solving its issues. 

Regarding issue `Add-on auth TX failed: Insufficient funds` , could you send your logs please? 

Regarding issue `Add LP: recipient () does not refer to any valid address` I'll link you to <https://github.com/DeFiCh/app/issues/314> which we can further discuss on the problem. Let’s keep this thread related to what the original author opened. Thank you for your understanding.

**Comment by INQB1** [comment]
Thx
Goran

On 24 Jan 2021, at 18:24, Bella <notifications@github.com> wrote:

Hi [@INQB1](https://github.com/INQB1) , thanks for your feedback. I understand the frustration, I assure you that the team is constantly working on improving the app and solving its issues.

Regarding issue Add-on auth TX failed: Insufficient funds , could you send your logs please?

Regarding issue Add LP: recipient () does not refer to any valid address I'll link you to [#314](https://github.com/DeFiCh/app/issues/314) which we can further discuss on the problem. Let’s keep this thread related to what the original author opened. Thank you for your understanding.

**Comment by izzycsy** [comment]
Hi @RoyDD87 @INQB1 @GitHubRea , the problem could be that you've too little DFI UTXOs balance (min. 0.05DFI) — which is required to perform swap and other functions. Try sending yourself 1 DFI and try the function again. To send one DFI, you can do it from an exchange or get a friend to send you some. Thank you.

**Comment by INQB1** [comment]
In my case I have 20 DFI in the wallet. So for me it’s not that.

Thx
Goran

On 26 Jan 2021, at 08:33, Bella <notifications@github.com> wrote:

Hi [@RoyDD87](https://github.com/RoyDD87) [@INQB1](https://github.com/INQB1) [@GitHubRea](https://github.com/GitHubRea) , the problem could be that you've too little DFI UTXOs balance (min. 0.05DFI) — which is required to perform swap and other functions. Try sending yourself 1 DFI and try the function again. To send one DFI, you can do it from an exchange or get a friend to send you some. Thank you.

**Comment by INQB1** [comment]
Just to add to my response below, Bella.
In the screenshot I sent you, it shows 0 DFI in the wallet because it couldn’t compete the synch. But earlier it did and should show 20 DFI again once it gets passed the synchronisation.

Thx
Goran

On 26 Jan 2021, at 08:51, Goran ProtonMail <info@goranamin.com> wrote:

In my case I have 20 DFI in the wallet. So for me it’s not that.

Thx
Goran

On 26 Jan 2021, at 08:33, Bella <notifications@github.com> wrote:

Hi [@RoyDD87](https://github.com/RoyDD87) [@INQB1](https://github.com/INQB1) [@GitHubRea](https://github.com/GitHubRea) , the problem could be that you've too little DFI UTXOs balance (min. 0.05DFI) — which is required to perform swap and other functions. Try sending yourself 1 DFI and try the function again. To send one DFI, you can do it from an exchange or get a friend to send you some. Thank you.

**Comment by GitHubRea** [comment]
Hi @izzycsy  I sent some DFI to wallet; now it is working! Thanks for your support, but I do not really understand the issue with DFI UTXOs balance. Is it not possible to use the DFI for UTXOs balance which I get from rewards? Thanks a lot

**Comment by izzycsy** [comment]
Hi @INQB1 @GitHubRea , basically DFI exist in 2 forms; **utxoDFI** and **accountDFI**. utxoDFI is used to pay for transactions fees while Rewards received are in accountDFI. You can freely convert between the 2 anytime — at a 1:1 ratio, and in order to convert accountDFI to utxoDFI. The simplest way is to send DFI from your `receive address A` to your `receive address A`, the app will automatically convert for you.

**Comment by GitHubRea** [comment]
Ah I See; now it is clear for me. Thanks for your support

**Comment by GitHubRea** [comment]
BTW nice emoji

**Comment by INQB1** [comment]
Oh, I see. Many Thanks !!

Goran

On 26 Jan 2021, at 14:45, Bella <notifications@github.com> wrote:

Hi [@INQB1](https://github.com/INQB1) [@GitHubRea](https://github.com/GitHubRea) , basically DFI exist in 2 forms; utxoDFI and accountDFI. utxoDFI is used to pay for transactions fees while Rewards received are in accountDFI. You can freely convert between the 2 anytime — at a 1:1 ratio, and in order to convert accountDFI to utxoDFI. The simplest way is to send DFI from your receive address A to your receive address A, the app will automatically convert for you.

**Comment by INQB1** [comment]
Actually, that didn’t work for me.
Sending accountDFI to my receive address (within the wallet) did not convert it to utxoDFI, but kept it in accountDFI (it deducted the fees though).

Thx
Goran

On 26 Jan 2021, at 14:45, Bella <notifications@github.com> wrote:

Hi [@INQB1](https://github.com/INQB1) [@GitHubRea](https://github.com/GitHubRea) , basically DFI exist in 2 forms; utxoDFI and accountDFI. utxoDFI is used to pay for transactions fees while Rewards received are in accountDFI. You can freely convert between the 2 anytime — at a 1:1 ratio, and in order to convert accountDFI to utxoDFI. The simplest way is to send DFI from your receive address A to your receive address A, the app will automatically convert for you.

**Comment by izzycsy** [comment]
Hi @INQB1 , may I know if you tried sending from an exchange / someone else wallet?

**Comment by INQB1** [comment]
Thx Bella.

Yes, I transferred the funds from Cake to the wallet and I’m now on v2.1.13 (in reference to you other email re #305).

I solved the issue about insufficient funds by converting some accountDFI to utxoDFI through the CLI commands.

Unfortunately I keep having other issues I’m now working on.
This tool is starting to frustrate me. Is it really so buggy?

I had the error: txn-mempool-conflict (code 18)
I’m trying to resolve it by re-indexing but that hung up the app. I killed it and re-started it, which came up fine. But as soon as I hit the index setting when saving it throws error alerts and tries to restart the node. After several hours I think I’m going to kill it again.

Best

Goran

On 27 Jan 2021, at 13:35, Bella <notifications@github.com> wrote:

Hi [@INQB1](https://github.com/INQB1) , may I know if you tried sending from an exchange / someone else wallet?

**Comment by izzycsy** [comment]
Hi @INQB1 , the error `txn-mempool-conflict (code 18)` stems from the same issue of not having enough utxoDFI. Basically DFI exist in 2 forms; utxoDFI and accountDFI. utxoDFI is used to pay for transactions fees while Rewards received are in accountDFI. You can freely convert between the 2 anytime — at a 1:1 ratio, and in order to convert accountDFI to utxoDFI. The simplest way is to send DFI from your receive address A to your receive address A, the app will automatically convert for you.

**Comment by INQB1** [comment]
Hi Bella

Just fyi. What solved the “txn-mempool-conflict (code 18)” error for me was by refreshing UTXOs in Settings.

Thx
Goran

On 28 Jan 2021, at 11:06, Bella <notifications@github.com> wrote:

Hi [@INQB1](https://github.com/INQB1) , the error txn-mempool-conflict (code 18) stems from the same issue of not having enough utxoDFI. Basically DFI exist in 2 forms; utxoDFI and accountDFI. utxoDFI is used to pay for transactions fees while Rewards received are in accountDFI. You can freely convert between the 2 anytime — at a 1:1 ratio, and in order to convert accountDFI to utxoDFI. The simplest way is to send DFI from your receive address A to your receive address A, the app will automatically convert for you.

**Comment by BastianReed** [comment]
i have the same issue since today with version 2.1.13. 
i Have a Mac OS System.

If i reinstall the App, the syncronisation hangs on block: 606539...

If i refreshing UTXO Settings, the Pop Up Display Show: Restart Node...
This is hours displayed and nothing more happens.

Please help

**Comment by BastianReed** [comment]
> Hi @INQB1 @GitHubRea , basically DFI exist in 2 forms; **utxoDFI** and **accountDFI**. utxoDFI is used to pay for transactions fees while Rewards received are in accountDFI. You can freely convert between the 2 anytime — at a 1:1 ratio, and in order to convert accountDFI to utxoDFI.

How can i convert in the utxoDFI?
I have many DFI in my Account but i cannot change it in the dex with example btc or eth. 

I get this failure:
Add-on auth TX failed: Insufficient funds

**Comment by izzycsy** [comment]
Hi @BastianReed try sending 1 DFI to your account — used for transaction fees. Update [v2.1.15](https://defichain.com/downloads/) is out.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, provide new information (include screenshots) and app logs. Thank you.

**Comment by izzycsy** [comment]
Hi @BastianReed @INQB1 , update [v2.1.17](https://defichain.com/downloads/) is out.
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.

**Comment by BastianReed** [comment]
now it works. thanks
