### ISSUE TITLE
Mac: sync stops at 99%+ > increases memory usage

### ISSUE THREAD

**Issue by Capswiss** [DeFiCh/app#352]
### Preflight Checklist

- [x] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [x] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details

- **DeFi App Version:**
  - 2.1.11 
- **Previous DeFi App Version:**
  - 2.1.4
- **Operating System:**
  -  (Mac OS 10.13.6) (see Picture), with 360 GB free Disk-Space

### Screenshot(s) / screen recording(s) of issue

![Bildschirmfoto 2021-01-22 um 16 51 40](https://user-images.githubusercontent.com/46944467/105523041-3a90df00-5cde-11eb-9649-3b633c4de341.jpg)
![Bildschirmfoto 2021-01-22 um 16 49 14](https://user-images.githubusercontent.com/46944467/105523099-49779180-5cde-11eb-82cb-a5f727fc512a.jpg)
![Bildschirmfoto 2021-01-22 um 16 54 13](https://user-images.githubusercontent.com/46944467/105523116-4e3c4580-5cde-11eb-8b38-7eec2bf64930.jpg)
![Bildschirmfoto 2021-01-22 um 17 40 02](https://user-images.githubusercontent.com/46944467/105523144-598f7100-5cde-11eb-9e19-89537d5b3eef.jpg)

### Actual Behavior

Please provide steps on how to reproduce the issue:

1. I remove the 2.1.4 App out the Aplication Folder.

2. I Copy 2.1.11 to the Aplication Folder

3. I Start the App.

4. immediately started loading the blockchain, quickly and everything seemed ok.

5. At 99.88% it stopped (see Picture) and it no longer continued to load the Blockchain. My Mac became very slow at this Moment. I could hardly change windows or type anything. When i typed, the signs came as if in time. Always the spinning ball. The download monitor showed no download (see Pictures), but sometimes a lot of uploads.
I left the Mac running for 2 hours without success.
However, the wallets were displayed with the data already loaded from the BlockChain. After clicking around in the program, white screen. Then I shot down the program. Mac still slow but a little less bad. It seems that the Mac is still weighing something even though the app is no longer running. after about one to two hours, the mac is almost back to normal. But it goes faster if I do a restart.

6. I already had this problem with 2.1.4. Sometimes it worked, and sometimes that's exactly what happened. Sometimes it was suddenly 100% synced after all, and then the Mac ran normally again.

7. i have uploaded the Log Files

### Expected Behavior
I've struggled with different versions of this app for many hours now. Version 2.1.4 worked best for me, but also with many Bugs. But I am sure that at some point you will get the app perfect and I would like to thank you very much for your work!

### App log / binary log / app config
[Log files.zip](https://github.com/DeFiCh/app/files/5858966/Log.files.zip)

**Comment by arnaudom** [comment]
I have similar issue with this version on windows 8. did not have that problem on previous version.
Slow down and lag around 99.7%. 
Sucking a lot of memory. 
I included a screenshot of memory consumption in the logs.
[walletlogs.zip](https://github.com/DeFiCh/app/files/5859705/walletlogs.zip)

**Comment by izzycsy** [comment]
Hi @Capswiss , thanks for the feedback. Your app syncs till 99%+ then it get stuck and there's no error shown on the app screen? Logs well received, please give us time to investigate. 

Hi @arnaudom , thanks for the feedback, is there any error shown on the app screen?Logs well received, please give us time to investigate.

**Comment by arnaudom** [comment]
No, there is no error message displayed.
I noticed it hanged for quite some time (maybe 30mn or more) on block 590687 with memory surge and once it passed that it continued to sync up to 100% at normal rate.

**Comment by Capswiss** [comment]
> Hi @Capswiss , thanks for the feedback. In the future, when updating the app, you can do in internally in the app or download from https://defichain.com/downloads/. and replace your current app. Your app syncs till 99%+ then it get stuck and there's no error shown on the app screen? Logs well received, please give us time to investigate.
> 
> <img alt="Replace app1" width="539" src="https://user-images.githubusercontent.com/65014479/105575191-ca00c580-5da4-11eb-89d7-4a2a30b5e8cc.png">
> 
> <img alt="Replace app2" width="535" src="https://user-images.githubusercontent.com/65014479/105575173-a50c5280-5da4-11eb-8fff-e878757668b0.png">
> 


@izzycsy Thank you for your hint. I usually do the update the way you show it. However, since there were often more new problems with the updates, I wanted to keep the old version, so I removed it from the program folder first. The old version 2.1.4 worked for me at least partially.

**Comment by cherryactiveo2** [comment]
Hi, since today i get the same issue, sync stops at 99,95% @ version 2.1.12

Logs:
[2021-01-25 17:27:13.939] [IPC-MAIN-info] [Starting Electron App] OS Windows 10 - 10.0.19042
[2021-01-25 17:27:13.945] [IPC-MAIN-info] Checking for update
[2021-01-25 17:27:14.475] [IPC-RENDERER-info] [Starting App] App is running with version 2.1.12
[2021-01-25 17:27:14.504] [IPC-RENDERER-info] Node start initiated
[2021-01-25 17:27:14.828] [IPC-RENDERER-info] Update for version 2.1.12 is not available (latest version: 2.1.12, downgrade is disallowed).
[2021-01-25 17:27:14.829] [IPC-RENDERER-debug] checkForUpdatesAndNotify called, downloadPromise is null
[2021-01-25 17:27:16.607] [IPC-RENDERER-info] Node started
[2021-01-25 17:27:18.620] [IPC-RENDERER-error] [isBlockchainStarted] Error: Request failed with status code 500
[2021-01-25 17:27:20.615] [IPC-RENDERER-error] [isBlockchainStarted] Error: Request failed with status code 500
[2021-01-25 17:27:22.767] [IPC-RENDERER-error]  [object Object]
[2021-01-25 17:27:22.770] [IPC-RENDERER-error]  Error: Invalid response from node, getpeerinfo: {"result":[],"error":null,"id":"4649574..."}


seems like there is a problem with the server --> Error: Request failed with status code 500

**Comment by oh-johnny** [comment]
[logs.zip](https://github.com/DeFiCh/app/files/5868383/logs.zip)
<img width="224" alt="Screenshot 2021-01-25 at 18 35 38" src="https://user-images.githubusercontent.com/76650269/105742696-20543c80-5f3c-11eb-89de-6e55f5a0e8fb.png">

Same here on MacOS 10.15.7 running version 2.1.12

**Comment by cRuuZaR** [comment]
> [logs.zip](https://github.com/DeFiCh/app/files/5868383/logs.zip)
> 
> <img width="224" alt="Screenshot 2021-01-25 at 18 35 38" src="https://user-images.githubusercontent.com/76650269/105742696-20543c80-5f3c-11eb-89de-6e55f5a0e8fb.png">
> 
> 
> 
> Same here on MacOS 10.15.7 running version 2.1.12

Today I have the same issue on  Mcbook big sure!

**Comment by Jacobsieler8888** [comment]
What is wrong with DEFI APP?  Mine will not sync either.  Please help!

**Comment by izzycsy** [comment]
Hi @Capswiss I understand, I do not recommend installing older version for your safety and security, our team is constantly working on improving the app and solving its issues. We regularly do releases, so if you are not in a big hurry I would suggest staying on the latest version and wait for a fix. 

Hi @cherryactiveo2 @oh-johnny @cRuuZaR @Jacobsieler8888, thanks for your feedback, please give us time to investigate this.

**Comment by izzycsy** [comment]
Hi @Capswiss @arnaudom @cherryactiveo2 @oh-johnny @cRuuZaR @Jacobsieler8888 , patch v2.1.12 is out <https://defichain.com/downloads/>.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.

**Comment by dieterich-m** [comment]
If not already mentioned somewhere, the same issue also applies to the Win App (Win 10).

**Comment by arnaudom** [comment]
> Hi @Capswiss @arnaudom @cherryactiveo2 @oh-johnny @cRuuZaR @Jacobsieler8888 , update [v2.1.13](https://defichain.com/downloads/) is out.
> Do give a thumbs up to this comment if your issue has been resolved, otherwise, provide new information (include screenshots) and app logs. Thank you.

I managed to sync 100% with latest version.
It still consumes a lot of memory and even more after full sync, up to 10kMb.
Then close the application and tried to reopen but it loops forever on splash screen. Have surge of memory use  memory use (more than 11kMb); computer freeze a a certain point and have to shut down.
Can't use.
[wallets1.zip](https://github.com/DeFiCh/app/files/5880457/wallets1.zip)

**Comment by cRuuZaR** [comment]
All ok here with 2.1.13 👍🏽

arnaudom <notifications@github.com> schrieb am Mi. 27. Jän. 2021 um 14:22:

**Comment by dieterich-m** [comment]
Do you update the app for Win as well: #325

**Comment by arnaudom** [comment]
> > Hi @Capswiss @arnaudom @cherryactiveo2 @oh-johnny @cRuuZaR @Jacobsieler8888 , update [v2.1.13](https://defichain.com/downloads/) is out.
> > Do give a thumbs up to this comment if your issue has been resolved, otherwise, provide new information (include screenshots) and app logs. Thank you.
> 
> I managed to sync 100% with latest version.
> It still consumes a lot of memory and even more after full sync, up to 10kMb.
> Then close the application and tried to reopen but it loops forever on splash screen. Have surge of memory use memory use (more than 11kMb); computer freeze a a certain point and have to shut down.
> Can't use.
> [wallets1.zip](https://github.com/DeFiCh/app/files/5880457/wallets1.zip)

Finally tried to downgrade to 2.1.12 then 2.1.11. I had same problem, Looping on splash screen with high memory use then end-up freezing my PC.
My next procedure, under v. 2.1.11: closed app, kill all app processes running in background, deleted all blockchain data folders.
The app opened and started sync again.

**Comment by izzycsy** [comment]
Hi @INQB1 , could you send your app logs here please?

**Comment by INQB1** [comment]
It works for me now but for syncing I have to close all other apps and free memory (RAM and disk). Syncing
[28JAN2021_applog_v2.1.13.log](https://github.com/DeFiCh/app/files/5885585/28JAN2021_applog_v2.1.13.log)
 seems to be done entirely in RAM memory. 
Hence with the growing size of the blockchain it seems to need more and more every day. Yesterday, for me,  it peaked at 18.5GB for a short moment at around 99.7%, and then completed with 10.5GB held in memory. I then need to close and restart the app to free that memory for it to come down to the operational level at about 450MB. 

I believe soon, most computers won’t be able to handle it unless they’re loaded with extensive amounts of memory (greater than 32GB) or take ages with disk swapping.

**Comment by INQB1** [comment]
If the computer isn't equipped with enough memory, what some people do as a work around (until it's fixed) is to kill the app in between, say when it reaches 5GB of memory usage, and restart the app to resume with fresh memory. The app then continues to sync from where it was when it was stopped (process killed). Not beautiful, but it seems to work for now.

**Comment by INQB1** [comment]
For me, the memory issues pertained to all versions: v2.1.11, v2.1.12, v2.1.13
I'm now on v2.1.13 and the memory part works fine. I now struggle with a different issue, but that's not for this thread (txn-mempool-conflict (code 18)).

**Comment by arnaudom** [comment]
> If the computer isn't equipped with enough memory, what some people do as a work around (until it's fixed) is to kill the app in between, say when it reaches 5GB of memory usage, and restart the app to resume with fresh memory. The app then continues to sync from where it was when it was stopped (process killed). Not beautiful, but it seems to work for now.

Not always, it happened many times to me where is starts over from 0 after killing.
At least in my configuration windows 8 / 16Gb

**Comment by izzycsy** [comment]
Hi @INQB1 , thanks for the feedback and app log. May I know what operating system you're using? if possible can you send your binary log & app config? It'll help provide more insight during investigation. Thank you.

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/106107124-7d8cff80-6181-11eb-8d6a-e4a7d78ec033.png">

**Comment by izzycsy** [comment]
Hi @arnaudom , well noted, the team is looking into it.

**Comment by INQB1** [comment]
> > If the computer isn't equipped with enough memory, what some people do as a work around (until it's fixed) is to kill the app in between, say when it reaches 5GB of memory usage, and restart the app to resume with fresh memory. The app then continues to sync from where it was when it was stopped (process killed). Not beautiful, but it seems to work for now.
> 
> Not always, it happened many times to me where is starts over from 0 after killing.
> At least in my configuration windows 8 / 16Gb

I don't think 8/16GB is enough. Deducting what the OS and system needs, there's not enough left and I wouldn't be surprised if the app sync runs into issues already at around 5GB mem usage.

**Comment by bvbfan** [comment]
This is another issue, 1GiB should be normal usage of the node.

**Comment by INQB1** [comment]
> Hi @INQB1 , thanks for the feedback and app log. May I know what operating system you're using? if possible can you send your binary log & app config? It'll help provide more insight during investigation. Thank you.
> 
> <img alt="1 App log" width="339" src="https://user-images.githubusercontent.com/65014479/106107124-7d8cff80-6181-11eb-8d6a-e4a7d78ec033.png">

My OS is MacOS Mojave, 10.14.6

[Archive.zip](https://github.com/DeFiCh/app/files/5885660/Archive.zip)

**Comment by izzycsy** [comment]
Hi @INQB1 , the team reviewed your logs, it seems that the issue you're facing is due to the block being stalled at block 597924, which can cause the node to disconnect, hence not a ram issue. The solution to this is **wait** for the block to sync to 100% _or_ try `Reindex Option` in Settings. If `Reindex option` does not work, send screenshots / app logs.

Hi @arnaudom , currently it seems that some windows-users are facing the issue [`Windows: sync stops at 99%+ > node is disconnected`](https://github.com/DeFiCh/app/issues/325), so I'll redirect you there. Take a screenshot of your activity monitor — attached is an example. 

<img width="734" alt="Activity Monitor" src="https://user-images.githubusercontent.com/65014479/106119521-46721a80-6190-11eb-9f38-1a7343bdaa82.png">

**Comment by izzycsy** [comment]
Hi @Capswiss @arnaudom @cherryactiveo2 @oh-johnny @Jacobsieler8888 , the team reviewed your logs, it seems that the issue you're facing could be due to the block being stalled at block 597924 yesterday, which can cause the node to disconnect, hence not a ram issue. The solution to this is wait for the block to sync to 100% or try `Reindex Option` in Settings. If `Reindex option` does not work, you may reopen this issue, kindly send screenshots / app logs.

Hi @arnaudom , currently it seems that some windows-users are facing the issue [Windows: sync stops at 99%+ > node is disconnected](https://github.com/DeFiCh/app/issues/325). Take a screenshot of your activity monitor and send it in that thread — attached is an example.

<img width="734" alt="Activity Monitor" src="https://user-images.githubusercontent.com/65014479/106120687-a1584180-6191-11eb-9233-897f727c62d0.png">

**Comment by arnaudom** [comment]
> 
> Hi @arnaudom , currently it seems that some windows-users are facing the issue [Windows: sync stops at 99%+ > node is disconnected](https://github.com/DeFiCh/app/issues/325). Take a screenshot of your activity monitor and send it in that thread — attached is an example.
> 
> <img alt="Activity Monitor" width="734" src="https://user-images.githubusercontent.com/65014479/106120822-d2387680-6191-11eb-96ae-86d81bb483b7.png">

Here it is, but right now I am back on v2.1.11 and everything runs fine after I downgraded and reset all data.
![image](https://user-images.githubusercontent.com/1535627/106122689-f006db00-6193-11eb-9b61-5f2ca04c3ab3.png)

**Comment by INQB1** [comment]
Hi Bella

The root cause of the issue might be here: https://www.reddit.com/r/defiblockchain/comments/l765tb/fix_for_ram_bug_and_corrupt_blockchain/
Great troubleshoot from Kracht (Sp0nde on reddit).
Please share with developers.

Thx

Goran

On 28 Jan 2021, at 10:43, Bella <notifications@github.com> wrote:

Hi [@INQB1](https://github.com/INQB1) , the team reviewed your logs, it seems that the issue you're facing is due to the block being stalled at block 597924, which can cause the node to disconnect, hence not a ram issue. The solution to this is wait for the block to sync to 100% or try Reindex Option in Settings. If Reindex option does not work, send screenshots / app logs.

Hi [@arnaudom](https://github.com/arnaudom) , currently it seems that some windows-users are facing the issue [Windows: sync stops at 99%+ > node is disconnected](https://github.com/DeFiCh/app/issues/325), so I'll redirect you there. Take a screenshot of your activity monitor — attached is an example.

[Activity Monitor](https://user-images.githubusercontent.com/65014479/106119521-46721a80-6190-11eb-9f38-1a7343bdaa82.png)
