### ISSUE TITLE
txn-mempool-conflict (code 18)

### ISSUE THREAD

**Issue by Ausafari** [DeFiCh/app#378]
App version 2.1.12. When I go to add liquidity to the BTC-DFI pool, it generates the following error every time: txn-mempool-conflict (code 18).
I have closed the app, restarted it, refreshed the wallet balances several times, but still cannot add liquidity to the pool.
Please help!
David

[app_log.log](https://github.com/DeFiCh/app/files/5866519/app_log.log)

[binary_log.log](https://github.com/DeFiCh/app/files/5866513/binary_log.log)

**Comment by BenThrottle85** [comment]
Hi @Ausafari 
Maybe this thread can help you?
https://github.com/DeFiCh/app/issues/241
I had the same issue so I think the fix is not working anymore with 2.1.12.

**Comment by Ausafari** [comment]
Thanks @BenThrottle85 . Still not working. Hoping the devs can release a fix soon!

**Comment by izzycsy** [comment]
Hi @Ausafari , it could be that you've too little DFI UTXOs balance (min. 0.05DFI) — which is required to perform swap and other functions. Try sending yourself 1 DFI and try the function again.

**Comment by Ausafari** [comment]
Thanks @izzycsy . Would that be Step 4 from the instructions on this page: https://www.reddit.com/r/defiblockchain/comments/kb10d3/stepbystep_changing_dfitoken_to_dficoin/ ?

**Comment by jung-eto** [comment]
Hi, I have got the same issue and I have more than enough DFI in my wallet. I reset the app completely an imported it with the backup file. It still doesn’t work.
Thank you for any help or tricks to solve it 🙏

**Comment by izzycsy** [comment]
Hi @Ausafari , step 4 refers to you token balances, the sum of utxo DFI & DFI would be your total tokens.

`getbalance` — utxoDFI
`gettokenbalances` — accountDFI  

Hi @jung-eto @Ausafari , basically DFI exist in 2 forms; **utxoDFI** and **accountDFI**. utxoDFI is used to pay for transactions fees while Rewards received are in accountDFI. You can freely convert between the 2 anytime — at a 1:1 ratio, and in order to convert accountDFI to utxoDFI. The simplest way is to send DFI from your `receive address A` to your `receive address A`, the app will automatically convert for you.

**Comment by Ausafari** [comment]
Thanks for that. I followed Step 4 in that linked page earlier today and was thereafter able to add liquidity again successfully.
Like many UX aspects of the app, it is an incredibly poor experience; having to go through all this rigmarole.
Like many reviewers of the app on the Telegram page, in my opinion such poor UX is definitely keeping a significant number of investors away who are simply not prepared to put up with this crappy UX experience.
That's my two DFI worth anyway.

**Comment by izzycsy** [comment]
Hi @Ausafari , thanks for the constructive criticism, we'll work on improving the ux.
