### ISSUE TITLE
Same issue

### ISSUE THREAD

**Issue by thbestforyourbizdeployment** [DeFiCh/app#400]
Delete previous builds, same issue. 
What is the most stable build? 

![image](https://user-images.githubusercontent.com/73033172/105919670-0da53a80-6004-11eb-8d97-f024a6708da1.png)

**Comment by izzycsy** [comment]
Hi @thbestforyourbizdeployment , thanks for the feedback. The most stable would be the latest, however someone a minority of users face new issues that did not occur during testing. I do not recommend installing older version for your safety and security, our team is constantly working on improving the app and solving its issues. We regularly do releases, so if you are not in a big hurry I would suggest staying on the latest version and wait for a fix. If the issue is widespread enough you will likely see a fix in under a week's time. Thank you for your understanding. I've tagged in the the issue relevant to what you're facing.
