### ISSUE TITLE
Window ver 2.1.10 Wallet DFI balance & DFI tokenbalances are different?

### ISSUE THREAD

**Issue by kenang68** [DeFiCh/app#422]
Hi Sir/ Madam,

Can I check why the DFI wallet balance & DFI Token balance are so different?

As shown in photo below. 

DFI Wallet Balance is 7.9

DFI coin balance is 3.0
DFI token balance is 182.3

Can you explain?

Thanks.

![210129 Wallet balance](https://user-images.githubusercontent.com/72757945/106231700-3e1bed00-622d-11eb-856b-524d2abcd385.jpg)
![210129 tokenbalances](https://user-images.githubusercontent.com/72757945/106231706-43793780-622d-11eb-94e0-e4f7e24f2f95.jpg)

**Comment by izzycsy** [comment]
Hi @kenang68 , thanks for your feedback. Regarding the issue of balance difference reflected in wallet & CLI, your wallet amount(s) have been correct since the start, while `gettokenbalances` had a bug — where it's over reporting the amount. Thus, you don’t lose money that money never belonged to you. This issue has already been resolved, kindly update your app to the latest [v2.1.13](https://defichain.com/downloads/). You may do a `backup wallet` before update. Thank you.
