### ISSUE TITLE
[Proposal / Feature Request] Allow user to choose installation directory

### ISSUE THREAD

**Issue by Darkwinde** [DeFiCh/app#435]
### Preflight Checklist
- [x] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [x] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### User Details
- **Current DeFi App Version:**
  - 2.1.15
- **Operating System (OS):**
  - Windows 10.0.19042

### Proposal
Would be great to get the possibility for the installer to choose the installation directory and stores information for updates. Due to my personal structure, I have placed all crypto wallets to a separate encrypted SSD. DeFi app always uses a default directory, for sure I can transfer it, but this would then on update always a manual step and makes no fun to be done on the current daily update cycle.

**Comment by izzycsy** [comment]
Hi @Darkwinde , would you be interested to join our Windows Teamon Telegram? It's a volunteer group with the community for the purpose of testing the app. If you're interested to know more, send me a dm on Telegram @imnotabell. This message will be removed once you've seen it. Thank you.

**Comment by izzycsy** [comment]
Hi @Darkwinde , update [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2) is out, this is a **mandatory update**.  Please read through the release notes before updating.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
