### ISSUE TITLE
Node disconnected AGAIN - Issue #428 closed prematurely

### ISSUE THREAD

**Issue by Ausafari** [DeFiCh/app#437]
Thanks so much Bella for prematurely closing Issue #428 , as absolutely nothing has changed with the latest release.
Call me wild and impulsive, but gee it would have been a good idea if you had checked the issue was resolved by the release of this cosmetic update before closing the thread.
So let's start again with a screenshot of EXACTLY the same issue occurring - as it has been for the last two days now, resulting in a completely unuseable app.
The logs are attached.
[binary_log.log](https://github.com/DeFiCh/app/files/5898717/binary_log.log)
[app_log.log](https://github.com/DeFiCh/app/files/5898718/app_log.log)

![defi-app-fails-again](https://user-images.githubusercontent.com/75756887/106368053-8b659f00-6392-11eb-8559-effb5f9f3b9e.jpg)

**Comment by Cryptopunch** [comment]
Hi DeFi-Team,
same problem for me since release 2.1.11. And now even with 2.1.15. App is not useable.
reddit also no solution so far:
https://www.reddit.com/r/defiblockchain/comments/l7k17u/defichain_wallet_app_freezes_all_the_time/
My files:

[2.1.14.zip](https://github.com/DeFiCh/app/files/5899108/2.1.14.zip)
