### ISSUE TITLE
Error: new Backup wallet file not generated

### ISSUE THREAD

**Issue by teich1961** [DeFiCh/app#460]
### Preflight Checklist

- [ ] I have searched [DeFiChain’s Github Issue Page](https://github.com/DeFiCh/app/issues) and none matches my issue
- [ ] I have read through [How To Submit Issues for DeFi App](https://github.com/DeFiCh/app/wiki/How-to-submit-issues-for-DeFi-app”)

### Issue Details

- **Current DeFi App Version:**
  - 
- **Previous DeFi App Version:**
  - 
- **Operating System (OS):**
  -

**Comment by teich1961** [comment]
Hello , I have version 2.1.15. when I press WALLET on the app, then BACKUP WALLET I enter 0202.txt, for example. want to save in folder in documents, press SAVE, then I open the folder but nothing is saved. What am I doing wrong?

**Comment by teich1961** [comment]
I've been working with the app since mid-December. It is not empty and has 3 LM pools. The last backup is from December 23rd, 2020. Since then, no further backups have worked.

**Comment by teich1961** [comment]
the file is empty, because when I press OVERWRITE OLD FILE nothing changes in the old backup, the backup date becomes the last saved block

**Comment by izzycsy** [comment]
Hi @teich1961 , thanks for your feedback and switching from [Reddit](https://www.reddit.com/r/defiblockchain/comments/lajiq7/wallet_backup/). As I understand, you're still in your original wallet and everything is working except that when you try to backup wallet, the file is empty. 

Regarding what you mentioned: _Yes, the file is empty, because when I press OVERWRITE OLD FILE nothing changes in the old backup, the backup date becomes the last saved block_. One more question, have you tried naming the the `backup wallet` a new name instead of replacing the old file which you previously saved?

Also, could you send your app logs please? 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/106591002-b3b6ee80-6588-11eb-9f7d-d08ebf696bc1.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/106591013-b6b1df00-6588-11eb-8526-288ae267e785.png">

<img width="671" alt="3 Drag and drop" src="https://user-images.githubusercontent.com/65014479/106591029-baddfc80-6588-11eb-8208-4f45754957d0.png">

**Comment by teich1961** [comment]
here are my APP logs . zip 
[Archiv.zip](https://github.com/DeFiCh/app/files/5910794/Archiv.zip)

**Comment by izzycsy** [comment]
Hi @teich1961 , well received, please give us time to investigate the issue.

**Comment by teich1961** [comment]
thank you much

**Comment by izzycsy** [comment]
Hi @teich1961 , regarding the issue [`Error: new Backup wallet file not generated`](https://github.com/DeFiCh/app/issues/461), I'll keep you updated there. We would like to keep same issues in one thread. Thank you.
