### ISSUE TITLE
Add-on auth TX failed: Insufficient funds

### ISSUE THREAD

**Issue by elxlee** [DeFiCh/app#501]
Hi, I have 10 LTC in the defi app wallet. I tried to use the DEX to swap 10 LTC for DFI, but it failed.

Error message was "Add-on auth TX failed: Insufficient funds"

What does it mean and how do I fix this issue?

![error fees](https://user-images.githubusercontent.com/70930938/107874612-ab9a6f80-6ef5-11eb-8253-f0e35b1c80d9.jpg)

**Comment by Darkwinde** [comment]
Hi @elxlee,
It could be that you've too little utxoDFI balance (min. 1DFI) — which is required to perform swap and other functions. Try sending yourself 1 DFI and try the function again.

Check for the long discussions in #312.

**Comment by izzycsy** [comment]
Hi @elxlee , update [v2.3.0](https://github.com/DeFiCh/app/releases/tag/v2.3.0) is out, this is a mandatory update due to node Dakota Upgrade 1.5.0. Please note that you’ll need to reindex from 0%. 
Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.  

You can refer to DeFiChain Telegram (EN) for more enquiries, simply type !insufficientfunds and you'll get an answer on why that prompt occurred.
