### ISSUE TITLE
can't send my btc into another wallet

### ISSUE THREAD

**Issue by Deuf97** [DeFiCh/app#535]
[defi defi.log.zip](https://github.com/DeFiCh/app/files/6026833/defi.defi.log.zip)

so the problem is when I want to send my btc into another wallet I put the amount and the address but the button "continue" stay grey and Ican't click on this so I can't send nothing. thank you

**Comment by thedoublejay** [comment]
@Deuf97 Are you sending it to another DeFi wallet or to another exchange? If you're sending it to another exchange, you need to send it thru Cake first.

**Comment by izzycsy** [comment]
Hi @Deuf97 , the address you’re using is probably not a DeFiChain-friendly address, that's why the button is _grey_. You can retrieve the DeFiChain address via <cakedefi.com>, try sending a small amount first to test.

1. Click on Balances in <cakedefi.com>
2. In the BTC row, click on Deposit button
3. You'll see the Transfer Network options `BTC` / `DeFiChain`
4. Under the QR Code states your DeFiChain address, copy it
5. Go to DeFi app > BTC wallet > Send
6. Paste your DeFiChain address into `To address` field

<img width="375" alt="Click DeFiChain   BTC" src="https://user-images.githubusercontent.com/65014479/108972748-945e3d80-76be-11eb-8e5e-464bba954675.png">

**Comment by Deuf97** [comment]
Got error in handleFallbackSendToken: Got error in accountToAccount - handleFallbackSendToken: Add-on auth TX failed: Insufficient funds.   . When I send my btc into the wallet I get this "Insufficient funds" but my btc are always in the wallet app and don't appear on defi cake

**Comment by izzycsy** [comment]
Hi @Deuf97 , do you have DFI in your wallet? uxtoDFI is needed for transaction fees, such as when you are about to send your tokens out of your wallet.
