### ISSUE TITLE
Balance in Wallet & Add Liquidity displayed is different

### ISSUE THREAD

**Issue by tame81** [DeFiCh/app#542]
#### What happened:
This happened to me a couple of times already for several coin types: When wanting to add liquidity, the balance of the coin I want to use is displayed wrongly, namely too high. I think it happens after I add liquidity once and then when I want to repeat the process, the balance is not updated. Thus the `MAX` button will use the wrong value.

#### What you expected to happen:
The balance displayed under the reference currency on the left side (e.g. LTC) should match what is in the wallet page.

#### How to reproduce it (as minimally and precisely as possible):
I had added liquidity before that day. Then later, I wanted to add some more. The last time it was LTC, so I'll use it in this example. I clicked `Liquidity` -> `LTC-DFI` -> `Add more`. The reference currency on the left side shows a wrong balance (too high), so when using the `MAX` button, it will enter the wrong amount.

#### What are your environment parameters?

- DeFi App Version: 2.1.17 (happened before, too)
- Operating System (OS): MacOS

**Comment by izzycsy** [comment]
Hi @tame81 , thanks for your feedback. I would like to further understand your issue, the balance displayed in `Wallet` & `Add Liquidity` is different? Or when you click `MAX` it displays a different balance (too high) compared to the amount displayed in your Wallet?

**Comment by tame81** [comment]
Hi @izzycsy, it's the former. The `MAX` button then uses the same (too high) value.

**Comment by izzycsy** [comment]
Hi @tame81 , I understand, can update to [v2.3.0](https://github.com/DeFiCh/app/releases/tag/v2.3.0), this a mandatory update due to node Dakota Upgrade 1.5.0. Please note that you’ll need to reindex from 0%.  I've seen your comment in https://github.com/DeFiCh/app/issues/544 .

So I'll suggest that you keep a copy of your wallet.dat file. 
Mac — Go to Folder: ` /Users/<username>/Library/Application Support/DeFi/wallets/wallet.dat`

<img width="626" alt="wallet dat location" src="https://user-images.githubusercontent.com/65014479/109154550-6570c600-77a9-11eb-9a38-e0429caa4c0a.png">


 If after the upgrade to v2.3.0, balance reflected is still different, can you send your app logs please?

**Comment by tame81** [comment]
Hi Bella,

I have upgraded and will check once I add liquidity twice - this is when
the error occurred.

About posting the logs publicly I am not very keen to be honest as I find
it dangerous.


Regards,
T

Am Do., 25. Feb. 2021 um 13:38 Uhr schrieb Bella <notifications@github.com>:

**Comment by izzycsy** [comment]
Hi @tame81 , I understand I'll try to help you from here since we won't be able to further understand your issue with the logs. When you add liquidity, what was the error message shown?

**Comment by tame81** [comment]
Hi @izzycsy!

I have updated to v2.3.0 and still have issues:

Problem 1: First time I wanted to add liquidity to the ETH-DFI pair, in the input dialog with the two fields, the wrong ETH balance was displayed. Restarted the procedure with clicking on Liquidity, pair selection and adding more: now the balance was correct. 

Problem 2: In the input dialog with the two fields, I can only enter a value into the left element (ETH), the right one (DFI) is not writable. I can use the MAX button on both sides, though.

**Comment by tame81** [comment]
Problem 3: I wanted to add liquidity in two steps having a balance of ~4 ETH and ~2600 DFI. Added 2 ETH and 9xx DFI which was successful. Clicked `Back To Pool` and wanted to add more. The ETH balance is again wrong (4 ETH), the DFI balance is correct (16xx DFI). When clicking the `MAX` button now on the ETH side, it will take the 4 ETH but display `Insufficient balance`.

Restarting the process yielded the correct ETH balance after 2 trials.

<img width="1136" alt="Screenshot 2021-03-04 at 18 09 26" src="https://user-images.githubusercontent.com/34913516/110001626-d61d6280-7d14-11eb-9a11-a848fc25b2e1.png">

**Comment by izzycsy** [comment]
Hi @tame81 , when you click on `MAX` ETH it equates to 1,916 DFI which is insufficient, then the` insufficient balance` message, reduce your ETH amount and your tx should get through. Update [v2.3.1](https://github.com/DeFiCh/app/releases/tag/v2.3.1) is out. Do give a thumbs up to this comment if your issue has been resolved, otherwise, please provide new information (include screenshots) and app logs. Thank you.

**Comment by izzycsy** [comment]
Hi @tame81 , update [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2) is out, this is a **mandatory update**.  Please read through the release notes before updating.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Thank you.

**Comment by tame81** [comment]
Hi @izzycsy! I have issues with the new Mac app, it can't be run (see screenshot). It's not the regular thing where you allow the app to open via 'Security & Privacy' settings. Clicking the question mark brings up an empty window.

<img width="532" alt="Screenshot 2021-03-23 at 11 01 26" src="https://user-images.githubusercontent.com/34913516/112129922-2d9e4800-8bc8-11eb-8821-509dd0a1e062.png">

<img width="1002" alt="Screenshot 2021-03-23 at 11 10 45" src="https://user-images.githubusercontent.com/34913516/112130173-7e15a580-8bc8-11eb-8c15-642ec4826f37.png">

**Comment by izzycsy** [comment]
Hi @tame81 , you can install using the `.dmg` format. Thanks for your feedback. As for the old app v2.3.0 named defi-app, you can delete it. We'll be moving forward with the new DeFi Wallet; as mentioned in the [release notes](https://github.com/DeFiCh/app/releases/tag/v2.3.2) due to the upcoming Dakota Cresent upgrade that's going to happen at block 733,000. If you've updated to v2.3.2, then there should be no issues. 

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.

**Comment by tame81** [comment]
@izzycsy, it's still not solved, there are my two issues left:

Adding liquidity the first time worked: I added 50 DFI, the BTC was calculated correctly.
Second go: Wanted to add 50 more, the BTC is calculated wrongly which results in an insufficient balance error.

<img width="1136" alt="Screenshot 2021-03-23 at 11 48 46" src="https://user-images.githubusercontent.com/34913516/112135492-224e1b00-8bce-11eb-83d7-4360f9e019ad.png">

When adding liquidity, you can either click the specific liquidity pool and then `+ ADD MORE` or click the `+ ADD LIQUIDITY` button. The difference is that with the first one, the tokens BTC, ETH, LTC are on the left side, with the latter, DFI is on the left. Only the left value can be edited, the right one only accepts the `MAX` button. This should be fixed as well.

Now with the new app, I have 2 extra addresses which I did not have in v2.3.0. I have to select every time where I want my proceeds from LM to go. Apparently these addresses existed before because from the app I see that they are 3 months old as the one address I created myself.

<img width="1136" alt="Screenshot 2021-03-23 at 11 42 20" src="https://user-images.githubusercontent.com/34913516/112136197-f3847480-8bce-11eb-9227-3f5b39a77091.png">

**Comment by tame81** [comment]
@izzycsy: Is the bonus available for bugs that are reported, as it was announced some time ago?

**Comment by izzycsy** [comment]
The add liquidity function is deliberately designed this way, when you add liquidity, the ratio of the two respective tokens are calculated for you. In your first screenshot, you wanted to add 50DFI and the BTC needed is 0.08980700, which for your case you have an amount under it. So to add the 50DFI, you'll need more BTC. 

To your next issue, have extra addresses, in v2.3.2 the app automatically retrieves old address — which you can remove if you're not using them. This was included in the update because we've cases where addresses are missing when users updated. Hence, you can just `cancel request` and continue using the app. 
 
<img width="692" alt="#4 Receive   Cancel request" src="https://user-images.githubusercontent.com/65014479/112137805-ae326800-8c0b-11eb-9ac5-6bc69947470f.png">

To check which address has tokens, you may type in the CLI: `listaccounts {} false false true` 
This will give you a breakdown of your tokens on the respective addresses.

What bonus are you referring to? There's no bonuses for bugs reported. If you're technical, feel free to contribute to the DeFi App — find out more [here](https://defichain.com/developers/). The purpose of this GitHub Issue page is to address bugs that users face. Although we do test before official release, sometimes new bugs may occur. Thank you for your feedback.

**Comment by tame81** [comment]
> The add liquidity function is deliberately designed this way, when you add liquidity, the ratio of the two respective tokens are calculated for you. In your first screenshot, you wanted to add 50DFI and the BTC needed is 0.08980700, which for your case you have an amount under it. So to add the 50DFI, you'll need more BTC.

That's what I'm saying, it's calculating wrongly: 50 DFI == 150 USD, 0.089 BTC == 4800 USD.

**Comment by izzycsy** [comment]
Hi @tame81 , I understand your issue now, can you send your logs please?

**Comment by tame81** [comment]
> To your next issue, have extra addresses, in v2.3.2 the app automatically retrieves old address — which you can remove if you're not using them. This was included in the update because we've cases where addresses are missing when users updated / addresses that were not saved. Hence, you can just `cancel request` and continue using the app.

Don't know where these addresses come from, they were not displayed in the older apps. I'll remove them once I'm sure there's nothing on them. If somebody would send me DFI to a removed address, can it be added again?

> To check which address has tokens, you may type in the CLI: `listaccounts {} false false true`
> This will give you a breakdown of your tokens on the respective addresses.

It shows only tokens from the address I created (address #1, starting with a "d"), the other addresses starting with "8" are not listed. Would they be listed if there was balance on them?
 
> What bonus are you referring to? There's no bonuses for bugs reported. If you're technical, feel free to contribute to the DeFi App — find out more [here](https://defichain.com/developers/). The purpose of this GitHub Issue page is to address bugs that users face. Although we do test before official release, sometimes new bugs may occur. Thank you for your feedback.

I was referring to something I read on a DeFi page, where you'd get a bounty of 50 DFI for real bugs. Can't find the link right now.

**Comment by izzycsy** [comment]
Yes, you can add the addresses back manually even after it's been removed. 

If you're keen on a bounty and you found a security related issue, you can submit a PR for the issue said you managed to resolve. If you've such a case you may send an email to _security@defichain.com_.

**Comment by tame81** [comment]
> Hi @tame81 , I understand your issue now, can you send your logs please? Thank you.
> <img alt="2 Compress" width="511" src="https://user-images.githubusercontent.com/65014479/112140933-9fe64b00-8c0f-11eb-930b-74cb10894eea.png">

I'd rather send them to you directly.

**Comment by izzycsy** [comment]
Hi @tame81 , sure, you may email to `bella@defichain.com`.

**Comment by tame81** [comment]
> Hi @tame81 , sure, you may email to `bella@defichain.com`.

Just sent them out to you.

**Comment by izzycsy** [comment]
Hi @tame81 , well received, please give us time to investigate this.

**Comment by tame81** [comment]
@izzycsy: Update with v2.3.3:

Changed some DFI to BTC using the DEX, then wanted to add liquidity.

Wallet balance is this:
![Uploading image.png…]()

Adding liquidity dialog looks like this:
![Uploading image.png…]()

The BTC balance is wrong, still.

**Comment by izzycsy** [comment]
Hi @tame81 , noted what is your output of `gettokenbalances` ? Also, before you add liquidity DFI-BTC, is it still reflect incorrectly?

**Comment by tame81** [comment]
`gettokenbalances` reflects what I see in the `Wallet` tab.

There are two ways to add liquidity to the DFI-BTC pair:

- `Liquidity` -> `BTC-DFI`
- `Liquidity` -> `+ ADD LIQUIDITY`

I think the latter calculated correctly, the former had a buggy calculation.

**Comment by tame81** [comment]
Here's an observation:
When using `Liquidity` -> `+ ADD LIQUIDITY` the ETH balance is used for BTC, thus resulting in wrong behaviour when using the `MAX` button.

Hint:
It should be possible to enter values on both sides...

![image](https://user-images.githubusercontent.com/34913516/113839355-e8654300-978f-11eb-867c-cde88bb8aedd.png)
![image](https://user-images.githubusercontent.com/34913516/113839448-fadf7c80-978f-11eb-9a9b-7432d300d3e8.png)

**Comment by izzycsy** [comment]
Hi @tame81 , thanks the team is investigating this. Thank you for your feedback.

**Comment by izzycsy** [comment]
Hi @tame81 , [v2.3.4](https://github.com/DeFiCh/app/releases/tag/v2.3.4) is out. Please read through the release notes before updating. Is you balance now reflected the same? Thank you.

**Comment by izzycsy** [comment]
Hi @tame81 , [v2.3.5](https://github.com/DeFiCh/app/releases/tag/v2.3.5) is out. Please read through the release notes before updating. Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Thank you.
