### ISSUE TITLE
Unable to add DFI-BTC

### ISSUE THREAD

**Issue by Brownie89** [DeFiCh/app#550]
What happened:
After updating to 2.3.0 and waiting for full sync I made a DFI => BTC change on the DEX.
Wanted to add Liquidity to the BTC Pool, but received the error in the added screenshot.
![IMG_558927A3DA3E-1](https://user-images.githubusercontent.com/79607801/109072219-ff2a6b80-76f4-11eb-82d0-afca184cd9e7.jpeg)

What you expected to happen:
I expected the App to add the amount of BTC / DFI.

How to reproduce it (as minimally and precisely as possible):
Close the error and retry to to add Liquidity.

What are your environment parameters?
- DeFi App Version: 2.3.0
- Operating System (OS): macOS Big Sur 11.2.1

[app_logs.zip](https://github.com/DeFiCh/app/files/6039137/app_logs.zip)

**Comment by izzycsy** [comment]
Hi @Brownie89 , thanks for your feedback, the error `Please wait for your transaction to be reflected in the next block before proceeding with a new transaction` occurred because you may have too many transactions stuck in the same block. The solution for this would be to leave your app running for about 1–2 hours and let the app process your pending transactions. Type the following to check pending transactions via CLI: `listtransactions`

**Comment by Brownie89** [comment]
Waiting for the error to solve itself was my first idea, but this didn't help.
After waiting a couple of hours I tried to swap a little amount of ETH on the DEX, this worked, but I still wasn't able to add BTC Liquidity.
Then I added some ETH to LM successfully, this may have changed something in the background, because after this step I was also able to add BTC.

All this should be visible in the appended log-files.

**Comment by Brownie89** [comment]
Today I was able to reproduce the error with the same steps already mentioned.
Changed DFI to BTC on DEX, tried to add it to LM and got the error. Waited for over 12 hours and retried with same error.
Added ETH to LM was successfully and afterwards I was able to add BTC to LM.

**Comment by izzycsy** [comment]
Hi @Brownie89 , thanks for elaborating, please give us time to investigate this.

**Comment by Amino159** [comment]
I had the same issue. I solved it also by using the ETH-DFI first then the other pools worked fine but when I try to add first to BTC-DFI or USDT-DFI I'll get the same error.

**Comment by izzycsy** [comment]
Hi @Amino159 , thanks for your feedback, can you send your app logs please? 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/109284401-c6a4a200-785a-11eb-8888-1ed6c29ae75b.png">
<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/109284415-cad0bf80-785a-11eb-81d3-88125dfdd9f9.png">

**Comment by Amino159** [comment]
Of course. You'll find it attached.
[app_logs.zip](https://github.com/DeFiCh/app/files/6048787/app_logs.zip)

**Comment by izzycsy** [comment]
Hi @Amino159 , thank you, please give us time to investigate this.

**Comment by izzycsy** [comment]
Hi @Amino159 , may I know what your output of the following: 
`getbalance` — utxoDFI
`gettokenbalances` — accountDFI

The sum of utxoDFI & accountDFI would be your total DFI tokens.

**Comment by Amino159** [comment]
getbalance
1.52960166

gettokenbalances
[
  "3.03015864@0",

**Comment by izzycsy** [comment]
Hi @Amino159 , can you send 1 DFI to your address that holds the 1.52 DFI. You can check which address holds those DFI via CLI: 
`listaccounts {} false false true`

**Comment by Amino159** [comment]
@izzycsy When I check via the CLI I see serveral adresses but none of them is holding exactly the 1.52 DFI

But getbalance still same result as before.

**Comment by izzycsy** [comment]
@Amino159 does the DFI add up in your addresses? 1.52960166 + 3.03015864 = `4.5597603`
DFI exist in 2 forms; **utxoDFI** and **accountDFI**. utxoDFI is used to pay for transactions fees while rewards received are in accountDFI. You can freely convert between the 2 anytime — at a 1:1 ratio. What you'll have to do is convert accountDFI to utxoDFI, the simplest way is to send DFI from your `receive address B` to your `receive address A`, the app will automatically convert for you.  Any function you use in the app charges a utxoDFI fee. It could be you've insufficient utxoDFI. Either that, or there's too many transactions going on in the same block, hence you'll have to wait for the next block to try again.

**Comment by izzycsy** [comment]
Hi @Brownie89 @Amino159 , update [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2) is out, this is a **mandatory update**.  Please read through the release notes before updating.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Thank you.

**Comment by lraphael** [comment]
I just had exactly the same problem with version 2.3.2. See logs for details.

Thanks!
[defilogs.zip](https://github.com/DeFiCh/app/files/6195210/defilogs.zip)

Env:
DeFi Wallet Version: 2.3.2
Operating System (OS): macOS Big Sur 11.2.3

**Comment by mrowean** [comment]
Having the same issue as above post installing 2.3.2

I'm able to make exchanges on DEX - however I cannot add to liquidity pool.
each time gives the above error.

"Please wait for your transaction to be reflected in the next block before proceeding with a new transaction."

DeFi Wallet Version: 2.3.2
Operating System (OS): macOS Big Sur 11.2.3

**Comment by izzycsy** [comment]
Hi @lraphael @mrowean , it’s likely that you've insufficient utxoDFI balance (min. 1 DFI) — which is required to perform swap and all other functions. DFI exist in 2 forms; **utxoDFI** and **accountDFI**. utxoDFI is used to pay for transactions fees while rewards received from liquidity mining (for example) are in accountDFI. 

You can freely convert between the 2 anytime — at a 1:1 ratio. To convert accountDFI to utxoDFI, the simplest way would via be DeFi Wallet app. Go to send DFI > paste in your address (send to yourself), the app will convert for you.

**Comment by izzycsy** [comment]
Hi @Brownie89 @lraphael @mrowean , [v2.3.3](https://github.com/DeFiCh/app/releases/tag/v2.3.3) is out. Please read through the release notes before updating. If you have not sync to 100%, there was a node issue on 05/04/2021 that may have cause the `network error`, everything is back online now, you may try the following: 

**Option 1 — Reset & Reindex (sync from 0%)**
1. Settings > `Reset & Reindex` 

<img width="790" alt="Settings   Reset   Reindex" src="https://user-images.githubusercontent.com/65014479/113691297-ddae9d80-96fe-11eb-85e8-a888f16a8df3.png">

 
**Option 2 — Snapshot (sync from 90%+)**
1. Settings > `Reset & Reindex` 
2. Wait for app to start syncing
3. Ensure you’ve at least 27GB of extra space
2.  Click on `i` located at bottom-left corner of app screen 
3. Download Snapshot

<img width="244" alt="`i` to trigger Snapshot download" src="https://user-images.githubusercontent.com/65014479/113691572-2403fc80-96ff-11eb-94c9-1e7ebafd697f.png">

If your issue persist, we can further discuss on the problem here [`v2.3.2 Unable to add liquidity`](https://github.com/DeFiCh/app/issues/704). We would like to keep same issues in one thread. Thank you for your patience.
