### ISSUE TITLE
Loop: Corrupted block database detected. Please restart with -reindex or -reindex-chainstate to recover. Do you want to restart?

### ISSUE THREAD

**Issue by nasilemak06** [DeFiCh/app#560]
#### What happened:
I closed the DEFI APP normally and restarted my machine.
It seems the app was removed after the restart without any warnings
I downloaded and installed DEfi 2.30. After launching the app, i am getting "Corrupted block database detected. Please restart with -reindex or -reindex-chainstate to recover. Do you want to restart? "

There is no option to access the setting.

I restart but always getting the problem with the pop-up error message.
I re-install it but getting the problem with the pop-up error message.
#### What are your environment parameters?

- DeFi App Version: 2.30
- Windows 10 Pro

#### Anything else we need to know?:

![image](https://user-images.githubusercontent.com/79631989/109159283-6a387880-77af-11eb-9035-5f1e30ffc269.png)
[DEFI_binary_error.log](https://github.com/DeFiCh/app/files/6043201/DEFI_binary_error.log)
[DEFI_error.log](https://github.com/DeFiCh/app/files/6043203/DEFI_error.log)

**Comment by izzycsy** [comment]
Hi @nasilemak06 , thanks for your feedback, please give us time to investigate this issue. Our team is constantly working on improving the app and solving its issues. We regularly do releases, so if you are not in a big hurry I would suggest staying on the latest version and wait for a fix.

**Comment by izzycsy** [comment]
triage / accepted

**Comment by Fabio129** [comment]
Hello

I should write my issue here. 
I have problems with my log in. I have already two problem. 

1. when I open my App it shows "beschädigte Blockdatenbank" an it do not show me the Home Screen. 

2. when I start my app it shows the number (2.3.0) but this is everything. There is nothing more Wayne how long I am waiting. 

I hope you can help me. Should I send my app logs in here?

Kind Regards

Fabio

**Comment by izzycsy** [comment]
Hi @nasilemak06 @Fabio129 , update [v2.3.1](https://github.com/DeFiCh/app/releases/tag/v2.3.1) is out.   Do give a thumbs up to this comment if your issue has been resolved, otherwise, please leave a comment with new information (include screenshots) and app logs. Thank you. 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/110774646-01fe9200-8299-11eb-8c60-cb25381be0bc.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/110774657-0460ec00-8299-11eb-82e9-9d6d3354e093.png">

**Comment by Fabio129** [comment]
Hello, 

I have downloaded the new version. Now if I will start my DeFi App it's loading and loading and loading. There are nothing happen.

I use windows 10 
Version DeFi 2.3.1

Enclosed you have my App Logs and an Screenshot! 

Hope you can help me!

Kind Regards 

Fabio Kuhn

[DeFi Wallet Sicherung_11.03.2021.log](https://github.com/DeFiCh/app/files/6122662/DeFi.Wallet.Sicherung_11.03.2021.log)

![WhatsApp Image 2021-03-11 at 12 38 16](https://user-images.githubusercontent.com/77388401/110781860-b29f6e00-8266-11eb-8d92-f190db37452d.jpeg)

**Comment by izzycsy** [comment]
Hi @Fabio129 , thank you. The team is constantly working on improving the app and solving its issues. We regularly do releases, so if you are not in a big hurry I would suggest staying on the latest version and wait for a fix.

**Comment by izzycsy** [comment]
Hi @nasilemak06 @Fabio129 , update [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2) is out, this is a **mandatory update**.  Please read through the release notes before updating.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
