### ISSUE TITLE
Configuration failure: no data found

### ISSUE THREAD

**Issue by xiongsheng97** [DeFiCh/app#570]
#### What happened:
[app log.log](https://github.com/DeFiCh/app/files/6051304/app.log.log)

Hi there, I am facing the issue with opening up the app. Furthermore, I have seeing people having issues with using seed for recovery. For myself, I didn't back up and i am afraid to lose everything. I hope you can help me with my concerns.

#### What are your environment parameters?

- DeFi App Version: 2.3
- Operating System (OS): 

#### Anything else we need to know?:

[app log.log](https://github.com/DeFiCh/app/files/6051287/app.log.log)

**Comment by izzycsy** [comment]
Hi @xiongsheng97 , thanks for your feedback. May I know what OS are you using? May I also have a screenshot of the error you're facing? In the mean time, make a copy of your `wallet.dat` file, if you keep this safe everything would be fine. The routes for the relevant OS as stated. 

Windows — C:  
`\Users\<username>\AppData\Roaming\DeFi Blockchain\wallets\wallet.dat`

Mac — Go to Folder:  
`/Users/<username>/Library/Application Support/DeFi/wallets/wallet.dat`

<img width="626" alt="wallet dat location" src="https://user-images.githubusercontent.com/65014479/109384101-89591680-7925-11eb-89c4-58960afee0ac.png">

I'll wait for your next reply on the error before advising further. Thank you.

**Comment by xiongsheng97** [comment]
Hi, I am using OS windows 10 and right now i can't find my wallet.dat. I have attach a photo for your reference. Please assist.
![Capture](https://user-images.githubusercontent.com/79715324/109388266-08a81380-7941-11eb-914a-0025428685bd.PNG)
![Untitled](https://user-images.githubusercontent.com/79715324/109388335-5e7cbb80-7941-11eb-8982-394d8be71694.png)

**Comment by izzycsy** [comment]
Hi @xiongsheng97 , the wallet.dat folder is a hidden folder, can you try copy & pasting the route (stated below) to the search bar? Your app should not be running while you're making a copy of / doing anything to the `wallet.dat`. Your 2nd screenshot refers to the app being unable to find the wallet.dat file. If you manage to find the folder, please make a copy of the wallet.dat first.

![xiongsheng97_img1](https://user-images.githubusercontent.com/65014479/109431176-214b2300-7a40-11eb-9415-94dbdaf6c79f.png)

Windows — C: ` \Users\<username>\AppData\Roaming\DeFi Blockchain\wallets\wallet.dat`

**Comment by xiongsheng97** [comment]
Hi. I tried following the steps that you said. Nothing seems to work. Hope that you can help me resolve this problem soon as I am really worried. I still have my 24 Code with me if it helps
![issue](https://user-images.githubusercontent.com/79715324/109495175-df66bf00-7ac9-11eb-95f3-dbe8949cb3aa.png)

**Comment by izzycsy** [comment]
Hi @xiongsheng97 , I meant type ` \Users\<username>\AppData\Roaming\DeFi Blockchain\wallets\wallet.dat` into the Finder's search bar. You can try restoring wallet via mnemonic seed, but if your balances are not displayed you will still have to use your wallet.dat file.

**Comment by thedoublejay** [comment]
@xiongsheng97 Can you check if you have `defi.conf` file on this folder `C:\Users\your username\.defi`? or maybe this folder is "hidden". Try to make this folder visible and run the app again.

**Comment by izzycsy** [comment]
Hi @xiongsheng97 	, update [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2) is out, this is a **mandatory update**.  Please read through the release notes before updating.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Thank you

**Comment by izzycsy** [comment]
Hi @xiongsheng97 , [v2.3.3](https://github.com/DeFiCh/app/releases/tag/v2.3.3) is out. Please read through the release notes before updating. If you have not sync to 100%, there was a node issue on 05/04/2021 that may have cause the `network error`, everything is back online now, you may try the following: 

**Option 1 — Reset & Reindex (sync from 0%)**
1. Settings > `Reset & Reindex` 

<img width="790" alt="Settings   Reset   Reindex" src="https://user-images.githubusercontent.com/65014479/113691297-ddae9d80-96fe-11eb-85e8-a888f16a8df3.png">

 
**Option 2 — Snapshot (sync from 90%+)**
1. Settings > `Reset & Reindex` 
2. Wait for app to start syncing
3. Ensure you’ve at least 27GB of extra space
2.  Click on `i` located at bottom-left corner of app screen 
3. Download Snapshot

<img width="244" alt="`i` to trigger Snapshot download" src="https://user-images.githubusercontent.com/65014479/113691572-2403fc80-96ff-11eb-94c9-1e7ebafd697f.png">

Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Thank you
