### ISSUE TITLE
add to liquidity

### ISSUE THREAD

**Issue by helhimm** [DeFiCh/app#577]
since yesterday I am trying to add funds to liquidity  for the usdt / dfi pair

#### How to reproduce it (as minimally and precisely as possible): trie to add add to liquidity several times, mdoes not work

 see above
[picture of issue.pdf](https://github.com/DeFiCh/app/files/6056496/picture.of.issue.pdf)

#### What are your environment parameters? at home using the system without any changes

- DeFi App Version:
- Operating System (OS): 2.30

#### Anything else we need to know?:

 attached picture of issue

**Comment by Capswiss** [comment]
I had the same issue since my update on 2.3.0 before 3 Days, when I try to add Liquidity. I can send tokens or Change in DEX whiteout Problems. Only Add Liquidity show this error message.
Also since the update, my Wallet BTC-DFI can't show transactions... it show the text, no transactions available. On my other Computer with the app 2.1.7, there it shows the transactions. Also there I can add Liquidity without problems.

Update: today the same issue with add Liquidity. Then I try to remove Liquidity and it works without problems. Then I test to add Liquidity again, and now it works.

**Comment by helhimm** [comment]
tried that, removed some no Problem but adding does not work

**Comment by helhimm** [comment]
I tried all that , removing works, adding does not work, same error message.
even over night <i left the app open and no action, transactions are not
shown .

**Comment by RobinTorque** [comment]
I had the same problem and have documented my solution here. 

https://defichain-wiki.com/wiki/210226-Block-Error

Many other users have also reported this problem.

**Comment by izzycsy** [comment]
Hi @helhimm , sometimes the error occurs when there's too many transaction in the same block. Update [v2.3.1](https://github.com/DeFiCh/app/releases/tag/v2.3.1) is out.  Do give a thumbs up to this comment if your issue has been resolved, otherwise, please leave a comment with new information (include screenshots) and app logs. Thank you.

**Comment by izzycsy** [comment]
Hi @helhimm @Capswiss , update [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2) is out, this is a **mandatory update**.  Please read through the release notes before updating.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Thank you
