### ISSUE TITLE
Masternode: Update message for Create

### ISSUE THREAD

**Issue by adrian-schnell** [DeFiCh/app#629]
#### What happened:
When trying to create a new masternode in 2.3.1, an error occurs to spent 1mio DFI

#### What you expected to happen:
Collateral changed to 20k DFI

#### How to reproduce it (as minimally and precisely as possible):

Menu Button "Masternode" and then create

#### What are your environment parameters?

- DeFi App Version: 2.3.1
- Operating System (OS): Mac OsX 11.2.2

![masternode](https://user-images.githubusercontent.com/322735/110761720-5a5d7180-8250-11eb-8bdc-635554cc51b5.png)

**Comment by RobinTorque** [comment]
Thank you for your message. The problem has already been detected and will be fixed in the next version. 

https://github.com/DeFiCh/app/pull/630

**Comment by izzycsy** [comment]
Hi @adrian-schnell , update [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2) is out, this is a **mandatory update**.  Please read through the release notes before updating.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
