### ISSUE TITLE
Snapshot: Local storage of the Blockchain

### ISSUE THREAD

**Issue by sbisig** [DeFiCh/app#647]
#### What would you like to be added:
Local storage of the Blockchain

#### Why is this needed:
It is very annoying (and inefficient) to wait hours until the whole blockchain is synchronized/downloaded (after each version update)

**Comment by RobinTorque** [comment]
Hi @sbisig 
The following texts might help

https://defichain-wiki.com/wiki/Fullnode#Create_and_use_backup_for_blockchain_data

https://defichain-wiki.com/wiki/Fullnode#Blockchain_Snapshot_Service

**Comment by izzycsy** [comment]
Hi @sbisig , thanks for your feedback, this issue is there will be an automated `snapshot` released soon, alternatively you may use it manually first. Thank you for your patience.

**Comment by izzycsy** [comment]
Hi @sbisig , update [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2) is out, this is a **mandatory update**.  Please read through the release notes before updating.

The above feature / issue is not included in this update yet, this comment is to notify you about the update.

**Comment by izzycsy** [comment]
Hi @sbisig , [v2.3.3](https://github.com/DeFiCh/app/releases/tag/v2.3.3) is out. Please read through the release notes before updating. If you have not sync to 100%, there was a node issue on 05/04/2021 that may have cause the `network error`, everything is back online now, you may try the following: 

**Option 1 — Reset & Reindex (sync from 0%)**
1. Settings > `Reset & Reindex` 

<img width="790" alt="Settings   Reset   Reindex" src="https://user-images.githubusercontent.com/65014479/113691297-ddae9d80-96fe-11eb-85e8-a888f16a8df3.png">

 
**Option 2 — Snapshot (sync from 90%+)**
1. Settings > `Reset & Reindex` 
2. Wait for app to start syncing
3. Ensure you’ve at least 27GB of extra space
2.  Click on `i` located at bottom-left corner of app screen 
3. Download Snapshot

<img width="244" alt="`i` to trigger Snapshot download" src="https://user-images.githubusercontent.com/65014479/113691572-2403fc80-96ff-11eb-94c9-1e7ebafd697f.png">

If your issue persist, we can further discuss on the problem here [`Unable to start blockchain`](https://github.com/DeFiCh/app/issues/733). We would like to keep same issues in one thread. Thank you for your patience.
