### ISSUE TITLE
TN: App hangs on reboot due to gen=1

### ISSUE THREAD

**Issue by Stonygan** [DeFiCh/app#650]
#### What you expected to happen:

Status displayed correctly.

#### How to reproduce it (as minimally and precisely as possible):

Createmasternode with Wallet CLI and remote VPS, restart Node at VPS.

#### What are your environment parameters?

- DeFi App Version: 2.3.1
- Operating System (OS): WIN10

#### Anything else we need to know?:

Whats the right way to update the Node on the VPS without get displayproblems in the APP. What happens if iuse the switch "Enable", only recreate defi.conf? Or send some command to the network?

![local_offline](https://user-images.githubusercontent.com/44975826/111025647-c3c2b900-83e5-11eb-82c8-7d246a07493b.jpg)
![staking_runs](https://user-images.githubusercontent.com/44975826/111025648-c45b4f80-83e5-11eb-8fa4-9ec9108f2635.jpg)

**Comment by Stonygan** [comment]
Another behaviour, when you create MN over CLI with seperate Operator MN and then use "Enable" in the GUI, the APP hangs on reboot and cant start anymore.
I think its because the Enable switch add gen=1 to config and the whole APP cant start, in the Log is entered:

Unable to stark Blockchain, unknown operator.

Must delete gen=1 manually in the defi.conf that the APP can work again.

**Comment by izzycsy** [comment]
Hi @Stonygan , thanks for your feedback, please give us time to investigate this.

**Comment by thedoublejay** [comment]
@Stonygan If GEN and SPV is enabled, it will by default run the masternode. However, if the masternode_operator listed is not owned by your wallet, it will cause some issues on the app. I suggest you check if this masternode_operator is part of your own wallet.

**Comment by Stonygan** [comment]
Ok, maybe some missunderstanding. I create my MN without the Create-Button, because i want to run the Operator on a seperate Machine (VPS). Therefore i use the CLI and type createmasternode owneradress operatoraddress. The operatoraddress is outside my Wallet and not  a part of it. After that, in the GUI the MN appears with the State ENABLED and ONLINE and local. Maybe thats wrong? The Operator is not local. After quitting the APP and start again, the APP displays my Masternode is offline and Status is not enabled. Minting is running fine with this state, but its confusing me and i think other Users, when the APP displays offline and give me the possibility to klick "ENABLE". I know that i not have to use this Button. But others?
When i click enable, you are right, defi.conf are rewrite with the options gen and spv. But with this click, APP wants to restart and never come back again, because operator is not in my wallet (and thats correct)
I think we must disable the ENABLE Button when Operatornode is remote.

**Comment by AltCoiFish** [comment]
>@Stonygan If GEN and SPV is enabled, it will by default run the masternode. However, if the masternode_operator listed is not owned by your wallet, it will cause some issues on the app. I suggest you check if this masternode_operator is part of your own wallet.

From an end user perspective its already hard enough to setup the MN itself. We should at least update the official tutorial https://defichain.com/learn/run-a-masternode/#for-owners-who-would-like-to-delegate-the-masternode-duties-to-another-node describing the delegation of the MN to a remote VPS. As this seems to not enable the tap on the DFI-Wallet when delegating the operator to a remote VPS. 

> I suggest you check if this masternode_operator is part of your own wallet.

If I delegate the MN to my operator server, in order to avoid this problem, can I add the operator address to my local wallet?


>Another behaviour, when you create MN over CLI with seperate Operator MN and then use "Enable" in the GUI, the APP hangs on reboot and cant start anymore.
I think its because the Enable switch add gen=1 to config and the whole APP cant start, in the Log is entered:
Unable to stark Blockchain, unknown operator.

We had the same experience when using the `cli` on the Wallet .

**Comment by izzycsy** [comment]
Hi @Stonygan , due to priorities for the app, we don't support features that are not through the usual UI route of the app at the moment, I'll be closing this issue in the mean time. Thank you for your understanding! You can post your idea on [DeFiChain Discussions](https://github.com/DeFiCh/app/discussions/categories/ideas), garner some support from the community, and the team can decide whether to implement the feature in the future. Thank you!
