### ISSUE TITLE
Catchphrase to restore wallet

### ISSUE THREAD

**Issue by johnny72764** [DeFiCh/app#653]
Help! My wallet never actually synched to the website and was lost? during an upgrade. I currently am running 2.3.0 and have both my catchphrase and seed phrases; however, when trying to restore my wallet through the app. it asks for me to enter my catchphrase first before the 24 seed phrases, yet, there is no entry field to enter catchphrase? What to do? Am I missing something? I don't want to lose and or stop investing.

**Comment by thedoublejay** [comment]
@johnny72764 When you open the app, it opens the passphrase popup? If you close it, can you see if your wallet is loaded? Maybe it's displaying because you have an unencrypted wallet

**Comment by izzycsy** [comment]
Hi @johnny72764 , which Restore option did you select?

**Comment by izzycsy** [comment]
Hi @johnny72764 , try to restore wallet using your `wallet.dat`. The routes to the wallet.dat as stated, please backup first before updating to , update [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2).

Windows — C:  \Users\<username>\AppData\Roaming\DeFi Blockchain\wallets\wallet.dat

Mac — Go to Folder:  /Users/<username>/Library/Application Support/DeFi/wallets/wallet.dat

<img width="1019" alt="Restore wallet from backup" src="https://user-images.githubusercontent.com/65014479/112043848-12114e00-8b84-11eb-9dce-5c528d894baf.png">

**Comment by izzycsy** [comment]
[v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2) is a **mandatory update**.  Please read through the release notes before updating.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Thank you

**Comment by izzycsy** [comment]
Hi @johnny72764 , [v2.3.3](https://github.com/DeFiCh/app/releases/tag/v2.3.3) is out. Please read through the release notes before updating. If you have not sync to 100%, there was a node issue on 05/04/2021 that may have cause the `network error`, everything is back online now, you may try the following: 

**Option 1 — Reset & Reindex (sync from 0%)**
1. Settings > `Reset & Reindex` 

<img width="790" alt="Settings   Reset   Reindex" src="https://user-images.githubusercontent.com/65014479/113691297-ddae9d80-96fe-11eb-85e8-a888f16a8df3.png">

 
**Option 2 — Snapshot (sync from 90%+)**
1. Settings > `Reset & Reindex` 
2. Wait for app to start syncing
3. Ensure you’ve at least 27GB of extra space
2.  Click on `i` located at bottom-left corner of app screen 
3. Download Snapshot

<img width="244" alt="`i` to trigger Snapshot download" src="https://user-images.githubusercontent.com/65014479/113691572-2403fc80-96ff-11eb-94c9-1e7ebafd697f.png">

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
