### ISSUE TITLE
v2.3.1 corrupted blockchain / app not syncing

### ISSUE THREAD

**Issue by canica84** [DeFiCh/app#657]
[DefiPenalba.zip](https://github.com/DeFiCh/app/files/6145011/DefiPenalba.zip)
#### What happened:
I updated to 2.3.1, wallet did not sync, it said it was corrupted, I reinstalled app, tried loading several wallet backups. The wallet backups load, but there is nothing in the balances. It does not ask me for my security catchprase nor is there anywhere to do so. It asks me for a mnemonic but when I installed in 2.3.0 it had not asked me for one to setup.  Appreciate any help as I can't see or load my balance. 

#### What you expected to happen:
 I expected update to work cleanly. 

#### What are your environment parameters?

- DeFi App Version: 2.3.1
- Operating System (OS): win 10 x64

#### Anything else we need to know?:

 Let me know how I can securely send in my logs.  Also It would help if I knew how I can look for a way back into my wallet. Thank you!

**Comment by izzycsy** [comment]
Hi @canica84 , thanks for your feedback, the team has halted v2.3.1 at the moment due to some issues. I'll update you again when the team fixes it and is ready for release. In the mean time please refer to the official channels for updates. 
[DeFiChain Telegram (EN)](https://t.me/defiblockchain)
[DeFiChain Announcements (EN)](https://t.me/defichain_announcements)

**Comment by franz1612** [comment]
Hey there, I got a similar problem. My app doesn't synchronize, but I don't get any error message. My files are attached. Screenshot as well. It stucks at block 678067, and no matter how long I let it load, it doesn't work.
Thanks for your help!

<img width="1015" alt="Bildschirmfoto 2021-03-16 um 12 25 03" src="https://user-images.githubusercontent.com/80677204/111301548-a47c9380-8652-11eb-9bcf-1a1e6153155f.png">
[Archiv.zip](https://github.com/DeFiCh/app/files/6148505/Archiv.zip)

**Comment by izzycsy** [comment]
Hi @franz1612 , thanks for your feedback, it's likely you've to wait for it to sync to 100%. There doesn't seem to be an error, it's just taking awhile to load. We'll be improving the loading speed soon. Thank you for your patience.

**Comment by franz1612** [comment]
Hi izzycsy, thank you for your answer. Unfortunately i tried it a few times to give the app time to load, but after a few tries for more than 2-3 hours each, i don´t know what to do.

**Comment by izzycsy** [comment]
If it's not throwing an error for eg the whole screen displays `Node disconnected`, then it's actually working fine and syncing — which from the screenshot sent it's exactly what you're facing. I understand that it takes time, but once your sync the 100%, the next time you load the app it wouldn't take that long. Alternatively, you can wait for the fix which includes Snapshot, basically it'll help the app load faster. As to when it'll be launch I can't give you a date yet. If you're a technical user, you can apply the snapshot manually — ask on Telegram. Other than that, wait for it to sync to 100%.

**Comment by RussellReibold** [comment]
<img width="804" alt="Bildschirmfoto 2021-03-18 um 19 56 20" src="https://user-images.githubusercontent.com/68062207/111681987-240d8c80-8824-11eb-8aa3-085d69fc97e4.png">

I have a similar Problem. 
- Synchro stopped at 86% for hours. 
- Then i wanted to update, because i thought maybe it has something to do with that. After updating, only a white screen 
  appeared. 
- Deinstalled the Wallet and downloaded the new Version 2.3.0
- After installing the Synchro worked
- Tried to restore the wallet with Seed but got the error message "corrupted blockchain"
- After trying the seed again i get the message that you can see in the screenshot. 

@izzycsy should i upload my logs here or send it to you via DM?

**Comment by izzycsy** [comment]
Hi @RussellReibold , can you try to Restore using wallet backup (wallet.dat) instead of mnemonic seed?

For Mac the route is:

Mac — Go to Folder:  `/Users/<username>/Library/Application Support/DeFi/wallets/wallet.dat`

Please keep your wallet.dat safe, you can duplicate a copy and store it in a thumb drive / external storage.

**Comment by RussellReibold** [comment]
@izzycsy i checked my backups but they are .txt not dat. All of them. 
Seems like i have to proceed with the seed. 
Any other ideas what i can do?

**Comment by izzycsy** [comment]
Hi @franz1612 @RussellReibold , try to restore wallet using your `wallet.dat`. The routes to the wallet.dat as stated, please backup first before updating to [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2).

Windows — C:  \Users\<username>\AppData\Roaming\DeFi Blockchain\wallets\wallet.dat

Mac — Go to Folder:  /Users/<username>/Library/Application Support/DeFi/wallets/wallet.dat

<img width="1019" alt="Restore wallet from backup" src="https://user-images.githubusercontent.com/65014479/112044316-a380c000-8b84-11eb-84d8-0b3689330466.png">

**Comment by izzycsy** [comment]
Hi @canica84 @franz1612 @RussellReibold , [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2) is a **mandatory update**.  Please read through the release notes before updating.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Thank you

**Comment by canica84** [comment]
sorry for delay, i was camping and off grid. I did upgrade to 2.3.2 but it keeps says node disconnected and balance error? Where can i proceed from here? Thank you
![Screenshot 2021-03-24 214451](https://user-images.githubusercontent.com/80724502/112420360-4bfc6480-8cea-11eb-814d-097cde889db6.png)

**Comment by izzycsy** [comment]
Hi @canica84 , , thanks for your feedback, a few questions to understand what may be the cause:

• May I know you have new folders named defi-wallet & DeFi Blockchain respectively? (you can take a screenshot so it's easier to refer to)
To find the files on Windows:
C:\Users\<username>\AppData\Roaming\DeFi Blockchain\

• Where did you specify to install the DeFi Wallet?

• Did you turn off your firewall & anti-virus?

**Comment by canica84** [comment]
![image](https://user-images.githubusercontent.com/80724502/112475714-56d8e880-8d2e-11eb-9210-2e10ee7e3cfc.png)

yes, i turned off antivirus and firewall as well. Thank you

**Comment by izzycsy** [comment]
Hi @canica84 , thanks for your reply. Make a copy of your wallets folder on a thumbdrive / external hard disk. Try re-installing [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2). 

Please note that for Windows users
• Do not use the installation folder `C:\Users\username\AppData\Roaming\defi-app` to store your wallet files. This folder is deleted and created on every manual install/update. If you have any wallet files on this folder, backup your wallet.dat files on a different directory before updating.
• You can now choose the installation directory during manual install 
• The new folder `defi-wallet` & `DeFi Blockchain` will be used from v2.3.2 onwards

Does it work?

**Comment by canica84** [comment]
Hi, I attempted this on a new computer, no previous install. I am still getting the node disconnected error when the blockchain is synching? Anything else I can do?

**Comment by izzycsy** [comment]
Hi @canica84 , is your antivirus & firewall turned off? Try using the [snapshot](https://snapshots.defichain.com/snapshot-mainnet-682097.tar.gz) (option 2). 

**Option 1 — Reindex (sync from 0%)** 
 1. You'll have to Reindex via Settings  
 2. App will start syncing from 0%  
3. Wait till 100% 

 You can try the following option if you’re more technical:
**Option 2 — Snapshot (sync from 90%+)** 
 1. Download the snapshot 
  2. In app, Reindex via Settings 
   3. Wait for 1%, close the app  
   4. Go to Defi (Mac) / DeFi Blockchain (Windows) folder  Mac — Go to Folder: `/Users/<username>/Library/Application Support/Defi` 
Windows — C: `C:\Users\<username>\AppData\Roaming\DeFi Blockchain` 
5. Unzip the downloaded Snapshot, replace the files in the Defi / DeFi Blockchain folder 
 6. Open your app, and it should start syncing from 90%+

**Comment by izzycsy** [comment]
Hi @canica84 @franz1612 , [v2.3.3](https://github.com/DeFiCh/app/releases/tag/v2.3.3) is out. Please read through the release notes before updating. We've included the Snapshot via the app UI should you face synchronizing issues. 

If your issue persist, we can further discuss on the problem here [`Unable to start blockchain`](https://github.com/DeFiCh/app/issues/733). We would like to keep same issues in one thread. Thank you for your patience.
