### ISSUE TITLE
Restore: choose a recent backup > bal 0

### ISSUE THREAD

**Issue by RobinTorque** [DeFiCh/app#662]
All attempts on the test net:

I installed version 2.3.0 on a new device. After that I clicked receive, sent me some DFI and left the wallet again. When I left, I did not create a backup, because backups are only necessary for emergencies, but not for everyday use. 

Then I tried to open the app again. 
<img width="1001" alt="Bildschirmfoto 2021-03-16 um 18 21 48" src="https://user-images.githubusercontent.com/65536965/111352599-a2332d00-8684-11eb-9f10-8f52bf83b400.png">
The wallet was opened, but the account balance was 0. 

I did this test 3 times. 3 times the same result. The default Wallet.dat does not store private keys. 

<img width="1004" alt="Bildschirmfoto 2021-03-16 um 18 26 00" src="https://user-images.githubusercontent.com/65536965/111352975-1968c100-8685-11eb-9ec5-f3e7452b550e.png">
Then I changed the test. I have saved the backup. After that I could choose between the backup and the default file when restoring. The backup contains the coins, the default wallet does not. 

Why does the standard wallet not store private keys?

**Comment by izzycsy** [comment]
Hi @RobinTorque , thanks for your feedback, please give us time to investigate this.

**Comment by RobinTorque** [comment]
The problem was fixed with version V2.3.2. 
@izzycsy The issue can be closed from my point of view.

**Comment by izzycsy** [comment]
Thanks @RobinTorque

**Comment by thedoublejay** [comment]
I'll re-open this for v2.3.2 @RobinTorque. It will not be included on this version. Unfortunately the issue requires a different fix as it causes other major issues.

Currently, what happens is:
1. By default, the node creates `wallet.dat`. Initially it's empty.
2. If you don't have any wallet or walletdir files, the node uses this file as the default wallet.

The issue occurs because we delete the default `wallet.dat`. We backup them every time we delete it (e.g, wallet-bak-dateofbackup.dat) on the default wallet directory so funds are safe. My initial fix caused some regressions that I had to rollback. I will do a proper fix for this on the next release.
