### ISSUE TITLE
Restore: show old addresses after wallet import

### ISSUE THREAD

**Issue by RobinTorque** [DeFiCh/app#669]
![210317 1348](https://user-images.githubusercontent.com/65536965/111469927-90569600-8727-11eb-8830-a4decb6174ce.PNG)

What I did: Wallet backup created. Exit Wallet. Backup restored. Try to add some liquidity. 

Problem: The app does not know a DFI wallet address and therefore cannot perform a swap or add liquidity to a pool pair. 

The current solution is to create a new address, which I have already documented here: https://defichain-wiki.com/wiki/Create_address

I would suggest 2 things to improve the app:
- Wallet addresses that already have some DFI should be automatically added to the list when importing the backup file. 

- When creating a new wallet, a first address should already be created automatically. This would make the setup a bit easier for new users.

**Comment by izzycsy** [comment]
Hi @RobinTorque , thanks for your feedback, please give us time to investigate this issue.

**Comment by izzycsy** [comment]
Hi @RobinTorque , update [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2) is out, this is a **mandatory update**.  Please read through the release notes before updating. 

Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
