### ISSUE TITLE
Win: Reinstalling on D:

### ISSUE THREAD

**Issue by Genaro6675** [DeFiCh/app#673]
i did back up  i couldnt get it to send  after I traded on dex grom defi from cake to tethusd and ether and btc  and bch  i thought the updates would help but everything went to 0000000 seed phrase  didn't work
I have all the logs

**Comment by izzycsy** [comment]
Hi @Genaro6675 , regarding the issue [`Restore: choose a recent backup > bal 0`](https://github.com/DeFiCh/app/issues/662), we can further discuss on the problem there. We would like to keep same issues in one thread. The team is currently fixing the issue. In the mean time, please wait for the fix and keep your `wallet.dat` safe. Thank you.

**Comment by Genaro6675** [comment]
bella i have tied to do it the way u guys asked  or told me to do it I
don't now   if I'm doing it wrong I don't think so   though but I have one
question do u need the same version 2.3.0  or can it bee done with the
2.3.2   i did how ever  start with the older I think I needed help

**Comment by izzycsy** [comment]
Hi @Genaro6675 , it's mandatory to update to v2.3.2, kindly read the [release notes](https://github.com/DeFiCh/app/releases/tag/v2.3.2). I would advice that you stay on v2.3.2, because after the upgrade, tx made on v2.3.0 would likely cause you problems. You can restore your wallet using your wallet backup (wallet.dat) on v2.3.2. 

<img width="1019" alt="Restore wallet from backup" src="https://user-images.githubusercontent.com/65014479/112136768-5f380300-8c0a-11eb-8cce-c9e56e135db0.png">

To find your `wallet.dat`: 
Windows: 
`C:\Users\<username>\AppData\Roaming\DeFi Blockchain\wallets\wallet.dat`

Mac — Go to Folder:
`/Users/<username>/Library/Application Support/Defi/wallets/wallet.dat`

**Comment by Genaro6675** [comment]
Thank you, I will do that.
but now it won't get passed 98 %   it keeps going up and down
and go back down

**Comment by izzycsy** [comment]
Hi @Genaro6675 , that's because you updated after the Dakota Crescent upgrade happen around 25 March 2021. To resolve this, I'm afraid you've to `Reindex` via Settings, the app will start syncing from 0%. Ensure that your PC is not locked / on screen saver mode when the app is syncing. I understand the frustration of re-syncing, the team is working on the snapshot where to speed up the syncing. Thank you for your patience. Kind reminder to keep your` wallet.dat` & `passphrase` safe.

**Comment by Genaro6675** [comment]
Ok, thank you.

**Comment by izzycsy** [comment]
Hi @Genaro6675 , [v2.3.3](https://github.com/DeFiCh/app/releases/tag/v2.3.3) is out. Please read through the release notes before updating. If you have not sync to 100%, there was a node issue on 05/04/2021 that may have cause the `network error`, everything is back online now, you may try the following: 

**Option 1 — Reset & Reindex (sync from 0%)**
1. Settings > `Reset & Reindex` 

<img width="790" alt="Settings   Reset   Reindex" src="https://user-images.githubusercontent.com/65014479/113691297-ddae9d80-96fe-11eb-85e8-a888f16a8df3.png">

 
**Option 2 — Snapshot (sync from 90%+)**
1. Settings > `Reset & Reindex` 
2. Wait for app to start syncing
3. Ensure you’ve at least 27GB of extra space
2.  Click on `i` located at bottom-left corner of app screen 
3. Download Snapshot

<img width="244" alt="`i` to trigger Snapshot download" src="https://user-images.githubusercontent.com/65014479/113691572-2403fc80-96ff-11eb-94c9-1e7ebafd697f.png">

If your issue persist, we can further discuss on the problem here [`Unable to start blockchain`](https://github.com/DeFiCh/app/issues/733). We would like to keep same issues in one thread. Thank you for your patience.

**Comment by Genaro6675** [comment]
I'm sorry i know u said to talk there further I don't know how yet   sorry
but I have all thoughts problems except   after I down loaded the new 2.3.3
it worked at first they were not there the coins so as instructed i i
refreshed in the test they were not and followed further instructions and
now it says un able to start block chain please help me I have a lot in
there to loose

**Comment by izzycsy** [comment]
Hi @Genaro6675 , can you first confirm that you've backup-ed your wallet.dat? 

To find your `wallets` folder, search in Go To Folder:
`/Users/<username>/Library/Application Support/Defi/wallets`
<img width="822" alt="wallet dat location" src="https://user-images.githubusercontent.com/65014479/114377885-ba319a00-9bb9-11eb-86bf-3f3e9c6dc4fe.png">

You can copy and paste the `wallets` folder on another directory in your mac, I personally put it in Documents so it's easier for me to `Restore Wallet from backup` if need be.

**Comment by Genaro6675** [comment]
Yes, I did.
ty but now says can't connect to the blockchain

**Comment by Genaro6675** [comment]
yes i have it backed 
it said the laST TO TIMES BEFORE IT COULDNT CONNECT THAT THE NODE OR BLOCK WAS CORRUPTED  WOULD YOU LIKE TO RESYNCOR DOWNLOAD MAP I RESYNCED FIRST THEN WHRN IT DID IT AGAIN I SAD THE MAP AND NOW IT CANT CONNECT

**Comment by izzycsy** [comment]
Ok, what do you mean by map? 

Can you try to download the `DeFi-Wallet-2.3.3.dmg` file, and replace your existing app. 

<img width="540" alt="Replace app1" src="https://user-images.githubusercontent.com/65014479/114389678-e2c09080-9bc7-11eb-8dff-bafd825f91e1.png">
<img width="538" alt="Replace app2" src="https://user-images.githubusercontent.com/65014479/114389691-e6541780-9bc7-11eb-80ba-2cdbaf0b2c57.png">

Then go to System Preferences and `open anyway`. 
<img width="665" alt="Open Anyway" src="https://user-images.githubusercontent.com/65014479/114390074-5d89ab80-9bc8-11eb-9642-121ac094e1e4.png">

See if the DeFi Wallet opens.

**Comment by Genaro6675** [comment]
startsync over or download blockchain snapshot or blockchain map I
cant remember exactly

**Comment by Genaro6675** [comment]
ok im on it and maybe some info on my com would or might help
and ty  so much
![Screenshot 2021-04-12 055314](https://user-images.githubusercontent.com/75793821/114397486-98053100-9b53-11eb-8be6-d7610cbcc0e7.png)
![Screenshot 2021-04-12 055234](https://user-images.githubusercontent.com/75793821/114397525-a0f60280-9b53-11eb-83f2-ecbf2794427a.png)
![Screenshot 2021-04-12 060155](https://user-images.githubusercontent.com/75793821/114398429-a3a52780-9b54-11eb-9f77-ce466117641f.png)

**Comment by Genaro6675** [comment]
it  didn't  this is what i get when I unzip the file
 
![image](https://user-images.githubusercontent.com/75793821/114405135-3779f200-9b5b-11eb-96ea-2880ed7c6848.png)

**Comment by Genaro6675** [comment]
it didnt look like urs

**Comment by Genaro6675** [comment]
and this is what it gives 
![image](https://user-images.githubusercontent.com/75793821/114405381-7b6cf700-9b5b-11eb-9188-1dd37a2d3df3.png)
me

**Comment by izzycsy** [comment]
Hi @Genaro6675 , ah okay my bad you're on Windows. Thanks for the screenshot, it seems you lack space on your **C-drive**, for some reason on Windows it's requiring >100GB due to the size of the blockchain, our team is working on a Light Wallet, but for now if you want to use DeFi Wallet you'll have to make storage space. I'll guide you to reinstall please follow the steps **carefully**: 

1. `This PC\Documents\wallets` keep the files there. 
2. Ensure app is not running
3. Go to the hidden DeFi Blockchain folder
`C:\Users\<username>\AppData\Roaming\DeFi Blockchain\wallets\wallet.dat` 
If there are more wallet.dat here, copy and paste it in your `This PC\Documents\wallets`. 
4. Once you've backup your wallet.dat, proceed to `delete` everything 
App Installation: `C:\Users\username\Program Files\DeFi Wallet  `
DeFi Blockchain folder: `C:\Users\<username>\AppData\Roaming\DeFi Blockchain`
DeFi Wallet folder: ` C:\Users\username\AppData\Roaming\defi-wallet` 

**Reinstalling DeFi Wallet:** 

5. Go to [DeFiChain Downloads](https://defichain.com/downloads/)
Guide for Windows [here](https://defichain.com/learn/defi-app-how-to/)
<img width="596" alt="Windows Download" src="https://user-images.githubusercontent.com/65014479/114536813-09440180-9c84-11eb-9d54-248b89fc9e12.png">

6. Install DeFi Wallet, specify it to your **D-drive** (because it's the one with storage space)
7. Open app 


**Snapshot (sync from 90%+)**  

8. Wait for app to start syncing  
9.  Ensure you’ve at least 27GB of extra space   
10. Click on `i` located at bottom-left corner of app screen
<img width="244" alt="`i` to trigger Snapshot download" src="https://user-images.githubusercontent.com/65014479/114536368-976bb800-9c83-11eb-9bf3-6552652ac2c3.png"> 

11. Download Snapshot  or just wait for it to sync to 100% 
<img width="1007" alt="Snapshot size" src="https://user-images.githubusercontent.com/65014479/114536400-9f2b5c80-9c83-11eb-945e-1f16a6745113.png">

12. Once sync **reaches 100%**, Restore wallet from backup (wallet.dat)
– Link the app to `This PC\Documents\wallets` folder, click on any wallet.dat file
<img width="1021" alt="Restore wallet from backup" src="https://user-images.githubusercontent.com/65014479/114537776-2b8a4f00-9c85-11eb-946a-f0c7d677436f.png">


Let me know the results.

**Comment by Genaro6675** [comment]
ok excited  starting now ty let you now

**Comment by Genaro6675** [comment]
ok so it is all done i put it in the F drive it has 5 t  more than enough and it is partitioned as part of the computer, not  a backup  drive cool hu  it is downloading snapshot  now how do I link the document or restore wallets to the app??

**Comment by izzycsy** [comment]
Hi @Genaro6675 , I'll provide the steps: 

1. Wait for app sync to 100%
2. Click `Restore Wallet from Backup` (wallet.dat)
<img width="1021" alt="Restore wallet from backup" src="https://user-images.githubusercontent.com/65014479/114693207-f432a580-9d4b-11eb-905c-a70d8ca81f75.png">

3. A window should pop up and you've to direct the app to where your `wallet.dat` is located 
(for eg. I keep my wallet.dat in `Documents` folder, so I'll click on `Documents` folder > `wallets` folder > `wallet.dat` file) 
4. Your balances should reflect accordingly and you're good to go

**Comment by Genaro6675** [comment]
ok ive been trying to  get tit   to pass  
![image](https://user-images.githubusercontent.com/75793821/115020051-dca00d80-9e6e-11eb-8f8e-ae10b9ba06c6.png)

**Comment by Genaro6675** [comment]
ok so i 
![image](https://user-images.githubusercontent.com/75793821/115099786-0435bb00-9eed-11eb-8cb1-2bc673e6bd67.png)
get to  96.4  and it says network error  wallet balance error

**Comment by Genaro6675** [comment]
and pending wallet 
![image](https://user-images.githubusercontent.com/75793821/115099811-3e06c180-9eed-11eb-9a60-7a90fe80f13b.png)
failure   ntwork error

**Comment by Genaro6675** [comment]
![image](https://user-images.githubusercontent.com/75793821/115099836-6f7f8d00-9eed-11eb-95e5-d47101c9155f.png)

**Comment by Genaro6675** [comment]
now what ive tried to restart it all day

**Comment by Genaro6675** [comment]
it didn't work i took picture s to show u what it's saying and doing

**Comment by izzycsy** [comment]
Hi @Genaro6675 , try to close the app, restart your computer and try again or click `sync node`.

**Comment by Genaro6675** [comment]
996network error

**Comment by izzycsy** [comment]
Hi @Genaro6675 , did you turn off your firewall when using the app?

**Comment by Genaro6675** [comment]
no i didnt can i just allow it to to pass through or do I have to shut it
off

**Comment by izzycsy** [comment]
Hi @Genaro6675 , you've to turn off your firewall / allow DeFi Wallet to run on your desktop. It could also be a disruption in the internet connection when synchronizing.

**Comment by Genaro6675** [comment]
ok so it has  admin permission to go thru the fire wall is that still possibly affecting the program  so as I should take down the fire wall then
 and how about TOTALAV  it does how ever say that  it is clear and safe to use when it scanned the app before and during   download and  installation

**Comment by izzycsy** [comment]
Hi @Genaro6675 , yes your firewall has to be turned off when running the app, this is Window's operating system by default. Even on Mac, we've to allow it once to run the app. I guess it's part and parcel of running a decentralised application yourself.

**Comment by izzycsy** [comment]
Hi @Odynius , kindly refer to this message. 

> ... I'll guide you to reinstall please follow the steps **carefully**:
> 
> 1. `This PC\Documents\wallets` keep the files there.
> 2. Ensure app is not running
> 3. Go to the hidden DeFi Blockchain folder
>    `C:\Users\<username>\AppData\Roaming\DeFi Blockchain\wallets\wallet.dat`
>    If there are more wallet.dat here, copy and paste it in your `This PC\Documents\wallets`.
> 4. Once you've backup your wallet.dat, proceed to `delete` everything
>    App Installation: `C:\Users\username\Program Files\DeFi Wallet        `
>    DeFi Blockchain folder: `C:\Users\<username>\AppData\Roaming\DeFi Blockchain`
>    DeFi Wallet folder: `    C:\Users\username\AppData\Roaming\defi-wallet`
> 
> **Reinstalling DeFi Wallet:**
> 
> 1. Go to [DeFiChain Downloads](https://defichain.com/downloads/)
>    Guide for Windows [here](https://defichain.com/learn/defi-app-how-to/)
> 
> <img alt="Windows Download" width="596" src="https://user-images.githubusercontent.com/65014479/114536813-09440180-9c84-11eb-9d54-248b89fc9e12.png">
> 
> 1. Install DeFi Wallet, specify it to your **D-drive** (because it's the one with storage space)
> 2. Open app
> 
> **Snapshot (sync from 90%+)**  
> 
> 1. Wait for app to start syncing
> 2. Ensure you’ve at least 27GB of extra space
> 3. Click on `i` located at bottom-left corner of app screen
> 
> <img alt="`i` to trigger Snapshot download" width="244" src="https://user-images.githubusercontent.com/65014479/114536368-976bb800-9c83-11eb-9bf3-6552652ac2c3.png">
> 
> 1. Download Snapshot     or just wait for it to sync to 100%
> 
> <img alt="Snapshot size" width="1007" src="https://user-images.githubusercontent.com/65014479/114536400-9f2b5c80-9c83-11eb-945e-1f16a6745113.png">
> 
> 1. Once sync **reaches 100%**, Restore wallet from backup (wallet.dat)
>    – Link the app to `This PC\Documents\wallets` folder, click on any wallet.dat file
> 
> <img alt="Restore wallet from backup" width="1021" src="https://user-images.githubusercontent.com/65014479/114537776-2b8a4f00-9c85-11eb-946a-f0c7d677436f.png">
> 
> Let me know the results.

**Comment by Odynius** [comment]
Hi @izzycsy. Since I use the app for the first time, i can't create a backup. I want to start using the app to make use of the DFI from CakeDEFI. It's the first installation.

**Comment by izzycsy** [comment]
Hi @Odynius , ah okay then you just need to specify where you want to install the app on your PC. Follow the instructions on the [DeFiChain website](https://defichain.com/learn/defi-app-how-to/).

**Comment by Odynius** [comment]
@izzycsy There are no instructions regarding installation in D:, if I didn't overlook something. I installed the App on D: but the Blockchain lands in %AppData% nevertheless...

**Comment by Genaro6675** [comment]
CAN U GIVE ME THE LOCATION AND ILL CHECK MY WINDOWS IS ACTUALLY SET TO PLACE APPS ETC  ON O TH 5 T   HARDRIVE THE D IS STICKY  FOR THE COMS USE AND THE C FOR WINDOWS TO NOT CLOG THE SYSTEM, IN THE BEGINNING, I DID ALLOW IT TO WORK ON THE C  WOULD THIS  CAUSE AN ISSUE  YOU THINK

**Comment by Odynius** [comment]
If someone needs the answer i was looking for: https://defichain-wiki.com/wiki/Blockchain_folder

**Comment by izzycsy** [comment]
Hi @Odynius , did you manage to successfully switch drive?

**Comment by Genaro6675** [comment]
i did that and it gave me the same eroro then un able to connect to block
chain i have now upgraded my hartd drive to 4 terra bit now there sj=hold
be plenty of memory and is syncing as we speak  i will gladly  let you now
the out come

 and as for  the backed up wallet how or were do i put them in the file or
u said link them

**Comment by izzycsy** [comment]
Hi @Genaro6675 , personally I store my wallet.dat on Documents; in the same drive as the app files. So I can easily access them. 

You can restore wallet via wallet backup (wallet.dat) 

<img width="1021" alt="Restore wallet from backup" src="https://user-images.githubusercontent.com/65014479/118019920-1f7cd480-b38c-11eb-9e4e-739230c5b0e5.png">

**Comment by izzycsy** [comment]
Hi @Genaro6675 @Odynius , update [v2.4.0](https://github.com/DeFiCh/app/releases/tag/v2.4.0) is out, this is a **mandatory update**.  Please read through the release notes before updating. Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Thank you.

**Comment by Genaro6675** [comment]
i  am doing as  u sy  up date mmentarally

**Comment by Genaro6675** [comment]
Will do, thanks!
i wanted to let you nowso i got it to work after my computer got a bad
update or something i had to set it back and it failed not to worry i as
sent the new assistant for windows it to backed everything and
incorporated my external harddrives it now believes that they are no longer
backup and external hard drives don't ask me  i don't know so now the c
drive is the original stil the make a long story short the backup failed
when it came time to reinstate the old the files painstakingly
i finally got defi back and going and it finished finally so connected the
as it was loading it says update needed it dated and restarted then said
node is disconnected

**Comment by Genaro6675** [comment]
ok so i followed the instructions to  erase everything after backing up th
wallet  step by step   cause after the defi upgraded it would say iot was
runningbut wouldnt show up on  the screen but said it was running like 8 of
the defi apps were up and running    now with the   uninstall and delete  i
can see it its faster but at well heres the picture this is what it says oh
and at the beginning  it says something kike timer adjustments 300 sec
 but any ways here is the picture as of now and how do i get the logs u
asked for
[image: image.png]

**Comment by izzycsy** [comment]
Hi @Genaro6675 , thanks for the update. 

<img width="348" alt="300 sec" src="https://user-images.githubusercontent.com/65014479/120169582-afe36200-c232-11eb-90be-2469c275e09a.png">

`Timeout updated to 300 sec` simply means you've synced to 100% and your wallet auto-lock is set to 300 seconds — 5 minutes. 

I'm unable to see your screenshot, can you drag and drop again and send over so I can understand if you have an issue.

**Comment by Genaro6675** [comment]
Sure, here it is.  IT WAS JUST SAYING DISCONNECTED  THING LIKE BEFORE

**Comment by izzycsy** [comment]
Hi @Genaro6675 , try [v2.4.1](https://github.com/DeFiCh/app/releases/tag/v2.4.1), and check your internet connection and auto-sleep is turn off on your PC.

**Comment by izzycsy** [comment]
Hi @Genaro6675 , [v2.4.2](https://github.com/DeFiCh/app/releases/tag/v2.4.2) is out, this is a mandatory update. Please read through the release notes before updating. This comment is to notify you about the update.

**Comment by Genaro6675** [comment]
ok good news-bad new the good news is the 2.4.2 worked as to synchronizing
I loaded the wallet  the de fi I had are their e
yes  but all the other tokens are not  when I sent this defi I changed like
100 to 250  tokens can't really remember into all the rest thru the (DEX)
they are not here
 I have the emails of the transactions to prove my claim somewhere here

granted I haven't done anything but tap on the defi tokens showing the
tokens with the last transaction loaded what do u want me to do now does it
need time to load up???

**Comment by izzycsy** [comment]
Hi @Genaro6675 , glad that you app finally worked. If I understand your next issue correctly, are you saying the balance is not reflected or the transaction history is missing?

**Comment by Genaro6675** [comment]
Yes, that is correct.
both  all i have is this ill show u
there should be a lot of every coin I exchanged on the dex from defi to
coins

**Comment by Genaro6675** [comment]
No, it's not.   it won't unlock its right cause if I put the wrong one in
its says the wrong one  it says Berkeley something I took a pick for you

**Comment by izzycsy** [comment]
Hi @Genaro6675 , can you update to [v2.4.3](https://defichain.com/downloads/) and check to see if your balance is reflect. 

1. Backup Wallet

<img width="287" alt="Menu bar   Backup Wallet" src="https://user-images.githubusercontent.com/65014479/120663309-7cb40380-c4bc-11eb-98fd-218951391375.png">

2. Download [v2.4.3](https://defichain.com/downloads/)

3. Open app and wait for it to sync to 100%, does your balance show?

**Comment by Genaro6675** [comment]
No, it doesn't. when it is done it says to set a unlock phrase i said later
now let me send out and the other tokens do not show  still
when I do try to add a phrase it says  nothing it does nothing like the
bottom doesn't work ????
before atleased it  said something

**Comment by Genaro6675** [comment]
i was able to catch the error message it didnt give till now

**Comment by izzycsy** [comment]
Hi @Genaro6675 , can you take a screenshot of your error & attach the logs so I can better understand your issue? 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/120785724-fd780b80-c55f-11eb-9184-3941a659c9af.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/120785750-01a42900-c560-11eb-8830-3e2e951031a0.png">

**Comment by izzycsy** [comment]
Hi @Genaro6675 , update [v2.4.5](https://github.com/DeFiCh/app/releases/tag/v2.4.5) is out, this is a **mandatory update**.  Please read through the release notes before updating.

**Comment by izzycsy** [comment]
Hi @Genaro6675 , [v2.5.2](https://github.com/DeFiCh/app/releases/tag/v2.5.2) is out. Please read through the release notes before updating. Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Thank you.

**Comment by Genaro6675** [comment]
i only got the defiant not the other tokens i traded for h had bch  btc
tether etc  as i have wrote before
only the defi  i sent after using the dex   i got back so fare
ty

**Comment by izzycsy** [comment]
Hi @Genaro6675 , you can `backup wallet`, update to the latest version [v2.5.2](https://github.com/DeFiCh/app/releases/tag/v2.5.2) and reindex if your tokens displayed are missing. Seems like your app is running. Thanks for the update.

**Comment by Genaro6675** [comment]
Thanks, I'll check it out.  and let u now if the reindex works

**Comment by Genaro6675** [comment]
i did the re index but noun of my coins there only the defi coin I had is
there

**Comment by Genaro6675** [comment]
i still havent gotten the other coins that i had exchanged thru dex  to
show up in my  wallet  now what  do i do

**Comment by Genaro6675** [comment]
it didnt work i still am not getting the other coins
