### ISSUE TITLE
insufficient funds but enough tokens

### ISSUE THREAD

**Issue by sushihater** [DeFiCh/app#682]
What happened:
After update to 2.3.0 wallet got restored but can't add liquidity to the pool because "insufficient funds".  

What you expected to happen:
Because of shown funds in the wallet, I expected to exchange half of DFi to ETH and add liquidity like always.
![Wallet screen](https://user-images.githubusercontent.com/77179052/111690700-d39b2c80-882d-11eb-940d-90ec0f205945.PNG)

How to reproduce it:
The problem was mentioned in some other issues before, as the shown ammount are tokens and not coins. Using "getbalance" the ammount is ZERO
![getbalance](https://user-images.githubusercontent.com/77179052/111690852-fcbbbd00-882d-11eb-95ea-49c3fc82d254.PNG)

Using "gettokenbalance" it shows the ammount displayed before:
![gettokenbalance](https://user-images.githubusercontent.com/77179052/111690995-1d841280-882e-11eb-8980-7d4a1725b6d6.PNG)

![getaccount](https://user-images.githubusercontent.com/77179052/111692786-1e1da880-8830-11eb-8513-2dd21251a4c8.PNG)

There are 3 wallet addresses. Sure, because had some different wallets before. However, where will the coins from mining go through??? The oldest wallet (first at screenshot "getaccount") seems to be for the token. The UI only shows the up to date wallet address to work with, and can't send from one wallet to another in my own account. 

The main problem is now, that I don't get any coins from mining since 5 days. What might be the issue, or where are they? Because of the gas fees sending more DFI from external is expansive, as my account is just a small one.

Any suggestions how to get the coins when there is no funds? Tried to change token to coins using the console like allready described, but also need coins to do so. 

Would be great to have no tokens at all. Otherwise, an opportunity to change the token to coins easy and best without costs or maybe take token for it, as they are available.

What are your environment parameters?

- DeFi Wallet Version: 2.3.0
- Operating System (OS): WINODWS

[app logs.zip](https://github.com/DeFiCh/app/files/6166980/app.logs.zip)

**Comment by izzycsy** [comment]
Hi @sushihater , receiving rewards consumes no fees, our app distributed the reward that you liquidity mine. The rewards received would be the `receive shares at` address you specified before adding liquidity.  From your screenshot, you're receiving rewards into your 3 addresses.

However, you do have insufficient utxoDFI balance (min. 1 DFI) — which is required to perform swap and other functions. Your utxoDFI (`getbalance`) is 0 at the moment. DFI exist in 2 forms; **utxoDFI** and **accountDFI**. utxoDFI is used to pay for transactions fees while rewards received are in accountDFI. You can freely convert between the 2 anytime — at a 1:1 ratio, and this will consume fee some fees as well. My suggestion would be to send 1 DFI from an external exchange, then convert your accountDFI (`gettokenbalances`) to utxoDFI. The simplest way is to convert DFI would be to send DFI from your `receive address B` to your `receive address A`, the app will convert for you. 

Things you need to do: 
1. Send 1 DFI from an exchange to address `dP22...` > continue using app 
2. To convert your accountDFI to uxtoDFI, send DFI from `dUkL...` to `dP22...` > paste the `dP22...` addresses in your send > app will convert to utxoDFI for you

Anything you do on the app cost utxo fees (min 0.003DFI), as it does with any other platforms you use. Our fees are significant smaller as compared to other platforms (for eg. ETH's gas fees are. $100). Hope you understand. Thank you.

**Comment by RobinTorque** [comment]
Hi @izzycsy 
I think we will get this question 100 more times. Perhaps it would be useful to write a comprehensive article that can then always be linked. 

Many people who install DeFi Wallet have a high interest in technology. It is therefore not surprising that the new users try everything and then ask these questions. People interested in technology do not just want to follow the instructions. They want to understand it and try it out. Therefore, I think it is necessary to describe and explain this topic really comprehensively, because there will always be new users who will ask this question. 

In principle, the Bitcoin network would also function without fees. They are only optional. Thus, the question arises why DeFiChain does not simply waive fees. Ahmed has already told me the answer to this. Every transaction requires a UTXO that is sent. It would be possible to send a UTXO without fees, but it is not possible to create a transaction without UTXO. Thus, even in a network without fees, DFI would always be needed. 

I think it is important to document this knowledge. Otherwise these questions will come again and again.

**Comment by sushihater** [comment]
Dear Bella,

Thank you for the fast reply.

However, in the app I can only select one wallet at the moment. No idea
why, but the other addresses vanished after I needed to initialize the
wallet using my seed. Can this be fixed somehow to bring back the addresses
to UI or is there a need to do it via console?

Bella ***@***.***> schrieb am Fr., 19. März 2021, 07:43:

**Comment by izzycsy** [comment]
Hi @sushihater , to prevent your wallet from facing this prompt, you need to have a balance of DFI (uxtoDFI). We will update the feature to prevent users from have 0 DFI when they click MAX, likely in the next build v2.3.3. For your case, when you remove your Liquidity, you will need at least 1 DFI — transfer from an exchange, because at the moment your `getbalance` (uxtoDFI) shows 0, hence insufficient for any transaction. 

If you've missing addresses, you can add it back manually. Click `DFI wallet` > `RECEIVE` > `NEW ADDRESS` > Turn off `Automatically generate a new address` and you can add your existing addresses from there. 

<img width="869" alt="Receive   Manually add address" src="https://user-images.githubusercontent.com/65014479/111900347-13038c00-8a6d-11eb-8106-2845fcee4e1a.png">

**Comment by sushihater** [comment]
Thank you, Bella.

Sent coins to the app and all good for now.

Also added the old addresses back. Thanks a lot. Nonetheless, there is no
option to choose to send from a specific wallet address to another!?

In addition to my former question, as the amount of coins will be reduced
every time I add liquidity (fees), I will then need more coins from
external somewhen in the future or always repeat the exchange to utxoDFI?
Just to understand :)

Bella ***@***.***> schrieb am So., 21. März 2021, 10:45:

**Comment by izzycsy** [comment]
Hi @sushihater , update [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2) is out, this is a **mandatory update**.  Please read through the release notes before updating. 

I would advice that you stick to the same address when adding / removing liquidity, that way all your utxoDFI / accountDFI is send and received to the same address. It's good to keep at least 1 DFI in your wallet for fees. 

In your example, I assume you're doing liquidity mining, the rewards that you get — accountDFI, can be converted to utxoDFI (for fees / sending out to an external source). Simply input your address A (that's from the DeFi app) and send. The app will convert it for you.
