### ISSUE TITLE
app freezes when creating a wallet

### ISSUE THREAD

**Issue by bfoettin** [DeFiCh/app#694]
[Archiv.zip](https://github.com/DeFiCh/app/files/6180882/Archiv.zip)
If I create a new wallet in the app and press "Create new wallet", the app freezes. I can no longer select anything in the mask.
V.2.3.0 on Mac

**Comment by Stonygan** [comment]
https://defichain-wiki.com/wiki/V2.3.1 its for Windows, but same for MAC helps.
I suggest to wait for version 2.3.2, official release in the next 48h i think, problem dont exist in 2.3.2.

**Comment by izzycsy** [comment]
Hi @bfoettin , [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2) is out, this is a **mandatory update**.  Please read through the release notes before updating / installing.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Thank you

**Comment by izzycsy** [comment]
Hi @bfoettin , regarding the issue [`Unable to start app`](https://github.com/DeFiCh/app/issues/703), we can further discuss on the problem there. We would like to keep same issues in one thread. Thank you.
