### ISSUE TITLE
Are private keys saved within a backup file?

### ISSUE THREAD

**Issue by ChLeonhartsberger** [DeFiCh/app#699]
#### What happened: 
When starting the creation of a new wallet i faced some frozen screens and I forced the machine to close the app. What happened next .. I never got my private keys because when I reentered the app everything was like if I successfully created a new wallet. At the moment I am not able to unlock the wallet because i never saw my private keys. I have a few backups of my wallet. Is there some information in which can help to get the private keys out?

#### What you expected to happen: 
Advice how to get the private keys?

#### What are your environment parameters?
- DeFi Wallet Version: 2.3.0
- Operating System (OS): macOS big sure, 11.2.2

#### Anything else we need to know?: - 
[BinaryLogs_2021-03-22_18_53.log](https://github.com/DeFiCh/app/files/6184507/BinaryLogs_2021-03-22_18_53.log)
[AppLogs_2021-03-22_18_53.log](https://github.com/DeFiCh/app/files/6184509/AppLogs_2021-03-22_18_53.log)

**Comment by RobinTorque** [comment]
Instructions for reading the private key: 
https://defichain-wiki.com/wiki/Private_key_read_out_of_the_app

**Comment by izzycsy** [comment]
Hi @ChLeonhartsberger , try to restore wallet using your `wallet.dat`. The route to the `wallet.dat` as stated, please backup first before updating to [v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2).

Mac — Go to Folder:  /Users/<username>/Library/Application Support/DeFi/wallets/wallet.dat

<img width="1019" alt="Restore wallet from backup" src="https://user-images.githubusercontent.com/65014479/112043848-12114e00-8b84-11eb-9dce-5c528d894baf.png">

**Comment by izzycsy** [comment]
[v2.3.2](https://github.com/DeFiCh/app/releases/tag/v2.3.2) is a **mandatory update**.  Please read through the release notes before updating.

Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Thank you

**Comment by ChLeonhartsberger** [comment]
Thank you for the quick feedback! I will check as soon as possible.

**Comment by ChLeonhartsberger** [comment]
I checked now and come to the conclusion that I never fully entered the passphrase. I searched in the app logs if i successfully entered the passphrase some time but i only see a time out log.

<img width="952" alt="image" src="https://user-images.githubusercontent.com/38130234/112112130-6bde3c00-8bb5-11eb-9db6-a167036e2209.png">

As a consequence I am not able to unlock my wallet again.

<img width="874" alt="image" src="https://user-images.githubusercontent.com/38130234/112112227-8adcce00-8bb5-11eb-8ddf-39c51752b3c1.png">

I already read in a different conversation that if you can't remember your passphrase you have no chance to unlock again, but what if I never entered the passphrase. Please confirm that timeout error in the logfile states that I never successfully changed the passphrase and please advice what I can do.

Sidenote: I only transferred DFI & Bitcoin to an address on the wallet, but nothing more.

**Comment by thedoublejay** [comment]
@ChLeonhartsberger  How did you create your wallet?

**Comment by izzycsy** [comment]
Hi @ChLeonhartsberger , did you create a passphrase via the CLI? In the app UI, before you enter your wallet, setting of a passphrase consists of a double confirmation before the wallet is locked. To get to the screen you've shown, you did create a passphrase otherwise it's impossible for it to be locked.

**Comment by ChLeonhartsberger** [comment]
So you as an expert say that you can't see something wrong in the log file?

Damn I almost tried 1h to find out my passphrase. Normally I have only a hand full of easy passwords I use almost everywhere.

[AppLogs_2021-03-22_18_53.log](https://github.com/DeFiCh/app/files/6189236/AppLogs_2021-03-22_18_53.log)

**Comment by izzycsy** [comment]
Hi @ChLeonhartsberger , we are no experts, we're part of this community trying to help users resolve their issues. And we won't ask you for your passphrase, as it's crucial to unlocking your wallet. It's likely that you've created your passphrase otherwise you would not be directed to that screen. Please try to remember your passphrase. In the mean time I'll send your logs for investigation. Can you send you binary log & app config as well please. 

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/112143160-78dd4880-8c12-11eb-87ea-c5ecd185c67e.png">

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/112143152-74b12b00-8c12-11eb-86b8-aa4974a60476.png">

**Comment by ChLeonhartsberger** [comment]
Ok. Understand. Thanks. btw: compared with my experience you are for sure experts.

[app logs.zip](https://github.com/DeFiCh/app/files/6189478/app.logs.zip)

**Comment by ChLeonhartsberger** [comment]
Hi again. You can close the issue. Found my passphrase.

Most of the time the problem sits in front of the PC!

**Comment by thedoublejay** [comment]
@ChLeonhartsberger no worries. Glad to be able to help.
