### ISSUE TITLE
DFI: Missing tx history on UI

### ISSUE THREAD

**Issue by lraphael** [DeFiCh/app#734]
#### What happened:
Sent 9.9 DFI from bittrex to defichain but the transaction does not show up. Probably the credit was increased by 9.9 DFI, but the entry in the transactions is missing. When I export the transactions, I see the entry.

#### What you expected to happen:
That the transaction also appears in the app.

### Transaction
https://mainnet.defichain.io/#/DFI/mainnet/tx/79d82b3dc1feb5cdcf36100753edd4076d321b64e97e404e955d8e6039ab273a
### Logs
[defi.zip](https://github.com/DeFiCh/app/files/6264745/defi.zip)

### Screenshot
![Bildschirmfoto 2021-04-06 um 14 48 59](https://user-images.githubusercontent.com/2973257/113714198-6ec64a00-96e8-11eb-9124-36647e655334.png)

#### What are your environment parameters?

- DeFi Wallet Version: 2.3.3
- Operating System (OS): Mac OS Big Sur 11.2.3

**Comment by izzycsy** [comment]
Hi @lraphael , thanks for your feedback, please give us time to investigate this issue.

**Comment by Hype-hash** [comment]
I am having an almost identical issue since 2.3.3
A tx from Bittrex to my wallet is missing in the wallet and also that funds. Same in CLI.
But I also don't see this tx when exporting the CSV.
I attached my files as suggested on Telegram.
[logs and config.zip](https://github.com/DeFiCh/app/files/6310644/logs.and.config.zip)

**Comment by izzycsy** [comment]
Hi @Hype-hash , well received, please give us time to investigate this issue.

**Comment by Sumpfi-75** [comment]
@ izzycsy
as desired, here are the log data to my article https://github.com/DeFiCh/app/issues/757
Log:
 
[log.zip](https://github.com/DeFiCh/app/files/6319279/log.zip)

**Comment by Hype-hash** [comment]
@izzycsy is there a way to filter this list? It's flooded with LM rewards

**Comment by izzycsy** [comment]
Hi @lraphael @Hype-hash @Sumpfi-75 , [v2.3.4](https://github.com/DeFiCh/app/releases/tag/v2.3.4) is out. Please read through the release notes before updating.   Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Thank you.

**Comment by michaelE123** [comment]
[Archive.zip](https://github.com/DeFiCh/app/files/6552934/Archive.zip)
Hi Bella, 

I hope this is correct here. The App stopped tracking the transactions in the transaction window after we moved all the tokens to the new address.

**Comment by izzycsy** [comment]
Hi @lraphael @Hype-hash @Sumpfi-75 @michaelE123 , [v2.4.0](https://github.com/DeFiCh/app/releases/tag/v2.4.0) is out, this is a mandatory update. Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by thunderstorm99** [comment]
2.4.0 seems not to have fixed this issue. Even worse, for me 2.4.0 doesn't even include any reward transactions if I check the box.

**Comment by izzycsy** [comment]
Hi @lraphael @Hype-hash @Sumpfi-75 @michaelE123 @thunderstorm99 , [v2.4.2](https://github.com/DeFiCh/app/releases/tag/v2.4.2) is out, this is a **mandatory update**.  Please read through the release notes before updating. _The above issue is not included in this update yet, this comment is to notify you about the update._ 

Our team is investigating on the `missing tx history` issue, will keep you updated here or you may refer to [DeFiChain Announcements (EN)](https://t.me/defichain_announcements) for a quicker notification update. Thank you for your patience.

**Comment by izzycsy** [comment]
Hi  @lraphael @Hype-hash @Sumpfi-75 @michaelE123 @thunderstorm99 , [v2.4.3](https://github.com/DeFiCh/app/releases/tag/v2.4.3) is out. Please read through the release notes before updating. 

Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs to this issue [`v2.4.0: Missing past tx history #891`](https://github.com/DeFiCh/app/issues/891). We can further discuss on the issue there, as we would like to keep same issues in one thread. Thank you.
