### ISSUE TITLE
Transaction issues (receive)

### ISSUE THREAD

**Issue by Cultured-Man** [DeFiCh/app#738]
Hello,

I have just (few hours ago) made two transactions from Bittrex to my DeFi wallet using the Address generated in the DeFI application. 

The first transaction was DFI, which arrived within a few minutes. The second transaction however was BTC but several hours later I still am to received those.

Please advice on whether I made any mistakes/errors or whether there is anything we can do the make by BTC appear :)

Im on Mac and using DeFi 2.3.3

Kind Regards

**Comment by izzycsy** [comment]
Hi @Cultured-Man , does Bittrex provide a tx id for you after you withdraw BTC from there? Attaching a [link](https://bittrex.zendesk.com/hc/en-us/articles/115000233331-Where-is-my-withdrawal-) for your reference. As for the DeFi Wallet, are you synced 100%?

**Comment by wmbst** [comment]
@Cultured-Man Are you sure bittrex can send BTC via DeFiChain?
Did you choose DeFiChain as a transfer method at bittrex? I haven't seen this option at bittrex.
You cannot send BTC directly via native bitcoin-chain to your DFI Wallet.

**Comment by Cultured-Man** [comment]
I guess not ;) How do i get BTC into DFI then?

**Comment by wmbst** [comment]
You have two options.
You can send DFi from bittrex to your wallet and then trade it within the wallet (DEX part) to BTC.
Or if you have an account at cakedefi.com you can send native BTC to cakedefi and from there you can send the BTC via DeFiChain to your wallet.

**Comment by izzycsy** [comment]
Hi @Cultured-Man , to add on to what @wmbst mentioned and using BTC as an example. BTC on DeFiChain is a DeFi Standard Token (DST) — in other words D-BTC, that is only transmittable to other DeFiChain addresses (usually starting with `8` or `d`). Try sending it through <cakedefi.com>, then to your own preferred exchange.  

To swap from D-BTC to BTC, you can go through sites like <cakedefi.com> or swap D-BTC to DFI on DEX. 

After a Cake account, you can retrieve the DeFiChain address, try sending a small amount first to test.

1. Click on Balances in <cakedefi.com>
2. In the BTC row, click on Deposit button
3. You'll see the Transfer Network options `BTC` / `DeFiChain`
4. Under the QR Code states your DeFiChain address, copy it
<img width="375" alt="Click DeFiChain   BTC" src="https://user-images.githubusercontent.com/65014479/114682210-75d10600-9d41-11eb-8326-ab33f2393d2f.png">

5. Go back to DeFi Wallet > BTC wallet > Send
6. Paste your DeFiChain address into DeFi Wallet `To address` field

A good rule of thumb, same token and way into DeFi Wallet, same token out from DeFi Wallet.

You may turn to DeFiChain’s telegram for how-to related issues: 
[DeFiChain Telegram (EN)](https://t.me/defiblockchain) 

Do give a thumbs up to this comment if your issue has been resolved, otherwise, if you face an error-related issue, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
