### ISSUE TITLE
After updating to 2.3.3 no sync anymore. Cannot access DeFi Wallet

### ISSUE THREAD

**Issue by MrsZoggy** [DeFiCh/app#756]
#### What happened: after upgrading from 2.3.2 to 2.3.3. the blockchain sync always fails at around 85%. Neither "Sync Node" nor "Download Snapshot" solves this issue because the sync/download always fails over and over again.
I tried to "Delete the DeFi App" from my laptop following these instructions: https://defichain-wiki.com/wiki/Delete_DeFi_App
I have access to all hidden folders, but I dont have the folder **.defi, DeFi, defi-app**
I downloaded the DeFi Wallet.dmg and tried to reinstall the app - not working - sync still stucks.

<img width="658" alt="Bildschirmfoto 2021-04-12 um 09 35 37" src="https://user-images.githubusercontent.com/82367341/114358692-787e0080-9b73-11eb-9d97-993b7efdca92.png">

<img width="625" alt="Bildschirmfoto 2021-04-12 um 09 39 36" src="https://user-images.githubusercontent.com/82367341/114358712-80d63b80-9b73-11eb-9527-8700f2e2dfdc.png">

After syncing several times the laptop notifies me that volume might be full - what doesn't make sense to me

<img width="214" alt="Bildschirmfoto 2021-04-12 um 09 51 57" src="https://user-images.githubusercontent.com/82367341/114359972-ce9f7380-9b74-11eb-9bf5-86ff22a98e7d.png">

#### What are your environment parameters?

- DeFi Wallet Version: 2.3.3
- Operating System (OS): mac os Big Sur 11.2.3

#### Anything else we need to know?:

I have my Passphrase and my Backup.dat - but no log-files

**Comment by izzycsy** [comment]
Hi @MrsZoggy , thanks for your feedback, the reason why you're unable to find the folders is because it's kept hidden, to prevent users from accidentally deleting them. 

You may try this workaround please follow the steps carefully, and make a **backup of your wallet.dat** before proceeding. 
To find your `wallets` folder, search in Go To Folder:
`/Users/<username>/Library/Application Support/Defi/wallets`
<img width="822" alt="wallet dat location" src="https://user-images.githubusercontent.com/65014479/114377885-ba319a00-9bb9-11eb-86bf-3f3e9c6dc4fe.png">

You can copy and paste the `wallets` folder on another directory in your mac, I personally put it in Documents so it's easier for me to `Restore Wallet from backup` if need be.

**Snapshot (sync from 90%+)** 
  1. Ensure app is not running 
   2. Download the [Snapshot](https://defi-snapshots-europe.s3.eu-central-1.amazonaws.com/snapshot-mainnet-738700.zip)  
   3. In app, `RESET & REINDEX` via Settings 
<img width="680" alt="Reset   Reindex" src="https://user-images.githubusercontent.com/65014479/114377536-560ed600-9bb9-11eb-8daf-de612de52c1e.png">

     4. Wait for 1%, close the app  
     5. Go to Defi (Mac) folder  
 Mac — Go to Folder:  `/Users/<username>/Library/Application Support/Defi`  
<img width="439" alt="Defi folder route" src="https://user-images.githubusercontent.com/65014479/114377680-8191c080-9bb9-11eb-8b62-fafdd43bd34d.png">
  
6. Unzip the downloaded Snapshot, drag and replace the folders `blocks`, `chainstate` and `enhancedcs` respectively in the DeFi Blockchain (Windows) folder 
 7. Open the app, it should start synchronizing from 90%+
 
 If your issue persist, we can further discuss on the problem here [`Unable to start blockchain`](https://github.com/DeFiCh/app/issues/733). We would like to keep same issues in one thread. Thank you for your patience.
