### ISSUE TITLE
DFI receive not possible

### ISSUE THREAD

**Issue by Sumpfi-75** [DeFiCh/app#757]
Hello,

i hope someone can help me, as I only know my way around superficially.

History:
a few days ago i had a problem updating to 2.3.3 (Win10) because the pc crashed during the synchronization. So the wallet.dat was damaged. Luckily i was able to recreate the wallet with the seed. After that was all addresses (54) lost. The liquid mining shares were found and are fine. I can also expand this. After that i couldn't see an address in the wallet. I created a new address to transfer DFI to Cake/Kucoin/Bitrex.

Problem:
Since the liquid mining was started with the old DFI main address before the update. I know the old address is not lost, but  i would like to rule out a loss of the coins. So i made a test and sent from Kucoin and Cake some DFI. Both transactions were reported as transferred by Kucoin and Cake. But nothing was received in the wallet. I noticed the note "not yet redeemed" in Explorer.

Questions:
What does the "not yet redeemed" that mean? Is that in connection?
Comes the Reward from the old addresses in my wallet?
How can i reactivate/show the old addresses?
Where are the transaction in the wallet?

Attechments (if we need more, so tell me):
Old Main address: dEA2cGMNzKeykq548hz9EUzqKCKzHQtPtM
New created address: dZS8ND5Nz9yGHtyv3LmkvbdQvM3TAMH5YW
Hash Cake: 8ca4ef17e2580b7bf5aa9aad8cefc394ec93d1a492a80e3d253bd2cce9d5c049
Hash Kucoin: 1342f11e71cbb91f9e72891bf71efe20bfa1b0c6b587444d6e55285305c33955
Picture wallet of the last 2 days:
![image](https://user-images.githubusercontent.com/82049639/114409186-76836400-9baa-11eb-8b60-ed3a3aefe1af.png)
![image](https://user-images.githubusercontent.com/82049639/114409318-9ca90400-9baa-11eb-81b9-031b4b6d8a3c.png)
![image](https://user-images.githubusercontent.com/82049639/114414525-2d81de80-9baf-11eb-8925-3d9d6597c73f.png)

**Comment by wmbst** [comment]
I am not a developer, so I guess I cannot help you much.
But I have 2 questions which could help to hint in the right direction.

You wrote you recovered with the seed phrase. Was your old wale password protected?
Did you try to add your old address to the wallet?
Generate a new address, but deactivate the "automatic generate new address". Then you can enter your old address.

**Comment by Sumpfi-75** [comment]
Hello,
i already had the idea and tried it before. The first main address is in the wallet again, but I still cannot see the receipt of both transactions. after manually adding the old address, I sent a test amount to Cake, which also arrived.  they were sent from the old address and that worked.  then I sent them back to the same old main address and these coins are not displayed in the wallet.

**Comment by izzycsy** [comment]
Hi @Sumpfi-75 , if I understood your issue correctly, you can try to Restore Wallet via Backup (wallet.dat), your addresses should be in it. If you made backups / keep a copy of your wallet.dat you can recover from those files, if not the app also automatically backup the wallet.dat for you. The wallet.dat won't be corrupted unless the user knowingly / unknowingly move or delete files that they're unfamiliar with. These files are deliberately kept hidden in your PC to prevent users from doing this to their wallet. 

To find your wallet.dat (unless you've stored it in another folder): 
`C:\Users\<username>\AppData\Roaming\DeFi Blockchain\wallets\wallet.dat` 

<img width="822" alt="wallet dat location" src="https://user-images.githubusercontent.com/65014479/114553461-3ac6c800-9c98-11eb-8a4f-88d4f5d70c93.png">

Personally i keep my backup `wallet.dat` in Documents, so it's easy for me to access as I'm the only owner of my PC. Even if other people get access to my wallet.dat they can't use it because of the passphrase encryption. So currently I've wallet.dat in the DeFi Blockchain folder and in my Documents. 

So for your case, if you didn't keep extra backups, go to the `wallets` folder and try `Restore Wallet from backup` using the `wallet.dat` files.

<img width="1021" alt="Restore wallet from backup" src="https://user-images.githubusercontent.com/65014479/114554865-bc6b2580-9c99-11eb-860a-a3f5b7daf353.png">


The answers to your questions: 
What does the "not yet redeemed" that mean? Is that in connection?
Do you have a screenshot of `not yet redeemed`? 

Checking from your tx id provided: 
`8ca4ef17e2580b7bf5aa9aad8cefc394ec93d1a492a80e3d253bd2cce9d5c049`, 4.8 DFI to address `dEA2...`
`1342f11e71cbb91f9e72891bf71efe20bfa1b0c6b587444d6e55285305c33955`, 2.00004435 DFI to address `dEA2...`

appears to be confirmed. 

Comes the Reward from the old addresses in my wallet?
Not sure what you mean by this question but I'll try to answer it. Rewards are received to the address you stated when adding liquidity. 

<img width="763" alt="#2 Add Liquidity   State receive address" src="https://user-images.githubusercontent.com/65014479/114554985-ddcc1180-9c99-11eb-88fe-3b50cc522840.png">

How can i reactivate/show the old addresses?
You can manually add back addresses, however on a newly created wallet those address won't work, hence the start of this comment, you need to `Restore Wallet via Backup` (using your original wallet.dat), the original wallet.dat should contain your 54 addresses including `dEA2...`.

<img width="869" alt="Receive   Manually add address" src="https://user-images.githubusercontent.com/65014479/114555157-0227ee00-9c9a-11eb-823c-09b61eeef4a2.png">

Where are the transaction in the wallet?
Restore the original wallet.dat and your tx history should appear.

**Comment by Sumpfi-75** [comment]
Hello izzycsy,
thanks for your answer.
I know it:
1. backup and restore the wallet
2. insert a old adress
I did all of this because the PC crashed on 2.3.3 while syncing. After points 1 and 2 everything went well. But there is one problem with creating the story, however.
I export the csv and this is ok, but in history of the wallet i miss the transaktion. After points 1 and 2 everything went well. However, there is a problem with creating the history in the app. As you can see in the first two app images, there are no transactions of the two test amounts to be seen. in the export csv but already. in the meantime i have sent a test amount to another dfi app wallet and back again. again, the transaction cannot be seen in the wallet app. It feels like there is a problem with the display of the transaction in the app. the export works properly.

**Comment by izzycsy** [comment]
Hi @Sumpfi-75 , thanks for the update. Yes there's an ongoing UI issue, regarding the issue [`DFI: Missing tx history on UI`](https://github.com/DeFiCh/app/issues/734), we can further discuss on the issue there. Kindly save your app logs and send them there. We would like to keep same issues in one thread. Thank you. 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/114891739-b82c3d00-9e3e-11eb-81b4-22602785e4dd.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/114891751-bbbfc400-9e3e-11eb-8ffd-b17a110abb48.png">
