### ISSUE TITLE
Will the DEX be abolished?

### ISSUE THREAD

**Issue by RobinTorque** [DeFiCh/app#769]
I am reading the transparency report and I am very shocked by what is written there. I don't understand why a DEX is first built up and then dismantled. 

<img width="768" alt="Bildschirmfoto 2021-04-16 um 20 49 25" src="https://user-images.githubusercontent.com/65536965/115073331-78299080-9ef8-11eb-9148-937eeeb29dd7.png">

According to this paragraph, the use of DEX will disappear from the DeFi Wallet. 

<img width="718" alt="Bildschirmfoto 2021-04-16 um 21 08 23" src="https://user-images.githubusercontent.com/65536965/115073393-92636e80-9ef8-11eb-8e13-b9bda0b598cd.png">

According to this paragraph, the Lite Wallet will use a centralised service. We will no longer have a decentralised exchange and will be more centralised than Ethereum. 

With Bitcoin it is possible to use a 100% decentralised node with only 5GB of storage. Without having to trust a single person. Why is there no effort to offer something like this for DeFiChain?

https://academy.bit2me.com/en/what-is-a-pruned-node/

I think it's fine if the wallet needs a lot of storage space. But offering features only on the centralised lite wallet has nothing to do with what we were promised. 

This is very disturbing to read. 

@uzyn @monstrobishi

**Comment by uzyn** [comment]
@RobinTorque 

1. Full node wallet will not be dropped. It is started as such because we need distributed full nodes and we are reaping the benefits now by having so many decentralized nodes. 
2. Light wallet is an option, not a necessary. Light wallet is where most users will be interacting with DeFiChain.
3. Power users like you and me will continue to run full node, just like you can do that with Bitcoin.
4. The part about mining can probably be a little confusing. Mining (masternode) UI will not be supported on Light wallet because masternode requires full blockchain node to function, thus will be full wallet only. 
5. Also, if you missed the part where we shared about light wallet design, we are designing to allow _anyone_ to run full node and to offer their services to everyone. Full node is a community service that _anyone_ can run. This takes it even a step-further than Infura. 

Hope this clears up your doubt. We are solving 2 problems here: 
1. UX issue, esp. for new users. Most users do not want to spend 12 hours setting up a wallet. We are competing with MetaMask, whether we like it or not.
2. Decentralization – all throughout our design, our direction has always been moving towards further and further decentralization. never less.

**Comment by RobinTorque** [comment]
Hello @uzyn 

That's very nice to hear. Thank you very much for this clarification.  

I am unfortunately not able to watch and understand the English YouTube videos. I can only rely on the German videos and the written texts.
