### ISSUE TITLE
Synchronizing my Wallet takes too long

### ISSUE THREAD

**Issue by ChingN** [DeFiCh/app#780]
What happened: Synchronizing my Wallet to 100% takes more than 24 hours when I open it on my laptop computer.

What you expected to happen: My wallet should not take more than 30 minutes to complete synchronization. 

#### What are your environment parameters?

- DeFi Wallet Version: 2.3.3
- Operating System (OS): Windows 10 Pro

**Comment by izzycsy** [comment]
Hi @ChingN , thanks for your feedback, what you're facing is due to running the DeFi Wallet remotely and depending on your location and internet connection, it'll affect the synchronisation speed. Due to this, the team has implemented a snapshot download to shorten the waiting time. Currently, the issue is with the size of the desktop app and the team is working on reducing the storage size needed and also on a Light Wallet. I'll provide the steps for you to download the snapshot, kindly note that you'll roughly need 50GB (Mac) and 110GB (Windows) space respectively, to run the app smoothly — [more details here](https://github.com/DeFiCh/app/releases/tag/v2.3.3). Lack of storage will likely throw you an error such as this [`Unable to Start Blockchain`](https://github.com/DeFiCh/app/issues/733).

1. Click on i located at bottom-left corner of app screen 
2. Download Snapshot

<img width="244" alt="`i` to trigger Snapshot download" src="https://user-images.githubusercontent.com/65014479/115857194-f7bae080-a45f-11eb-97e0-124ee3f9aa59.png">

<img width="1007" alt="Snapshot size" src="https://user-images.githubusercontent.com/65014479/115857668-892a5280-a460-11eb-8da9-32b09bdbc59f.png">

Once snapshot download is successful, your synchronisation should start at 90%+. 

<img width="1011" alt="Snapshot successful" src="https://user-images.githubusercontent.com/65014479/115857885-dd353700-a460-11eb-93d5-7761c3f76866.png">

Once you've reached 100%, from then on when you close and open the app after a day (for example), it should take a few minutes to sync up to the latest block. If you've further questions on how to use etc, you can refer to [DeFiChain Telegram (EN)](https://t.me/defiblockchain) for more enquiries, our community will help you out! Thank you for your patience.
