### ISSUE TITLE
Can't Open DeFi Wallet on Win10 Pro

### ISSUE THREAD

**Issue by tweedleDumb-69** [DeFiCh/app#796]
Hey everyone I've been battling with this issue for a few days now and I can't find the problem for the life of me. Every once in a while when trying to launch the app it will give me an error saying "Configuration failure- Cannot read property 'message' of undefined, here's a [photo](https://imgur.com/a/6TlNHfs) of the error. This is the only information I receive from the application. The only way I've  been able to resolve this issue is to do a fresh install of my OS and then it functions for a few days before randomly stopping working again. The only thing I could see causing an issue with this app is docker which has a web server running on port 8080. I've spent a few days trying to resolve this and have performed a fresh install twice already and I am just defeated at this point as I don't want to waste another few hours deploying the OS for it to break again. At this point I'm at a loss and just searching for anything that may help. Any help is much appreciated! I can also provide more information upon request.

**Comment by izzycsy** [comment]
Hi @tweedleDumb-69 , can you check if you've enough storage? Currently the app requires about 130GB. Before you perform a backup, please ensure that you made a backup of your wallet.dat. Can you send your app logs please? 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/116520715-a7cb9600-a905-11eb-8e89-03a20a1bc420.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/116520724-ab5f1d00-a905-11eb-8517-4422b7922e88.png">

**Comment by tweedleDumb-69** [comment]
Hey thanks for getting back to me I should have enough storage I currently have 175gb free on my drive. I don't seem to have to logs tab on my DeFi Wallet though idk if its because I'm on windows or what but I only have File, Edit, View, Window, and Help; and after looking thorough all those menus I don't see a logs option. I also checked the program folder and didn't see any log files there. It could also be because I removed the program at one point.

**Comment by tweedleDumb-69** [comment]
Here's the output when I run it in powershell if that helps any. ![cmdLineDeFiWalletResult](https://user-images.githubusercontent.com/79294887/116548019-a5dfe380-a8c1-11eb-918c-35699c4f0bae.png)

**Comment by izzycsy** [comment]
Hi @tweedleDumb-69 , while waiting for the team's investigation, let me guide you to reinstalling and see if it works, maybe then you can export your logs if the error occurs again. Please follow the steps carefully while performing a reinstallation of DeFi Wallet.

In app directory: 
1. Make a copy of the `wallets` folder, and paste in Documents (for example), so it’s easier to find it when restoring wallet later on. 

Win:
`C:\Users\<username>\AppData\Roaming\DeFi Blockchain\wallets\`

<img width="822" alt="wallet dat location" src="https://user-images.githubusercontent.com/65014479/115116300-6c5ace80-9fcb-11eb-9058-ecb719e01315.png">

2. Delete the following hidden folders: 

(a) Delete `DeFi Blockchain` folder
`C:\Users\<username>\AppData\Roaming\DeFi Blockchain\` 

(b) Delete `defi-wallet` folder
`C:\Users\username\AppData\Roaming\defi-wallet` 

(c) Delete `DeFi Wallet` app
`C:\Users\username\Program Files\DeFi Wallet` or whichever drive that you installed it on 

(d) Delete `.defi` folder
`C:\User\<username>\.defi`

Then proceed with the following: 

3. Download update from <https://defichain.com/downloads/> 
4. Open `DeFi-Wallet-2.3.3.exe` file 
5. Prompt: “DeFi Wallet” can’t be opened because Apple cannot check it for malicious software. > `OK` 
6. Go to `System Preferences` > `Security & Privacy` > `Open Anyway` 
**Installation guide for [Windows / Linux](https://defichain.com/learn/defi-app-how-to/)**  

<img width="665" alt="Open Anyway" src="https://user-images.githubusercontent.com/65014479/115116318-7ed50800-9fcb-11eb-9c4d-4d87700d0645.png">

8. At this point, you can either wait for the app to sync to 100% 
**or**
Download snapshot (27GB) and wait for app to sync to 100% 

<img width="1007" alt="Snapshot size" src="https://user-images.githubusercontent.com/65014479/115116337-914f4180-9fcb-11eb-816b-8d7c41164ab2.png">


9. When app syncs to 100% `Restore wallet from backup (wallet.dat) ` 
– Guide the app to where where your `wallet.dat` is located

<img width="1021" alt="Restore wallet from backup" src="https://user-images.githubusercontent.com/65014479/115116341-96ac8c00-9fcb-11eb-9e4a-ea59c4c8e330.png">

10. If the app throws and error, take a screenshot, save your app logs and send it here.

**Comment by tweedleDumb-69** [comment]
Hey I just tried following the steps above, with no luck I've tried installing it for just myself and for all users. All the folders mentioned were remove prior to running the uninstaller as well as the .defi folder. I still can't find any error logs I checked all the folders in the defi wallet program directory and theres no log files in there and I don't see any other way for me to gather logs on this machine. I think the app needs to finish the boot in order to access that option, I can see it on the defi wallet app on my laptop but its missing on the desktop. Here's a screenshot so you can see my problem. 
![2021-04-29 09_51_13-DeFi Wallet](https://user-images.githubusercontent.com/79294887/116561654-8308fb80-a8d0-11eb-8303-e459daacd410.png)

**Comment by John-Gee** [comment]
Yeah a bunch of stuff in the app is N/A until it's synchronized.

**Comment by izzycsy** [comment]
Hi @tweedleDumb-69 is your anti-virus turned off when running the app?

**Comment by tweedleDumb-69** [comment]
@izzycsy No it wasn't but I just tried disabling real time protection on windows defender and the app threw the same error

**Comment by izzycsy** [comment]
Hi @tweedleDumb-69 , I would think you've to turn off your anti-virus. Windows tend to have anti-virus installed, the anti-virus hooks into file system natively for real time detection which is a common cause of file related corruption issues.

**Comment by tweedleDumb-69** [comment]
Hi @izzycsy, I only have windows defender on this machine, disabling that doesn't seem to correct the problem

**Comment by izzycsy** [comment]
Hi @thunderstorm99 can you try asking our community [DeFiChain Telegram (EN)](https://t.me/defiblockchain)? So far no Windows user face this issue and if we can't reproduce it yet. All i can suggest is for you to keep your `wallet.dat` safe first, and wait for the next update.

**Comment by izzycsy** [comment]
Hi @tweedleDumb-69 @John-Gee , update [v2.4.0](https://github.com/DeFiCh/app/releases/tag/v2.4.0) is out, this is a **mandatory update**.  Please read through the release notes before updating. Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Thank you.

**Comment by izzycsy** [comment]
Hi @tweedleDumb-69 , [v2.4.2](https://github.com/DeFiCh/app/releases/tag/v2.4.2) is out, this is a **mandatory update**. Please read through the release notes before updating. _This comment is to notify you about the update._ 

If you still face the same issue, kindly refer to [`Unable to start blockchain`](https://github.com/DeFiCh/app/issues/888), in it consist of steps on how to reinstall. If you do proceed, kindly **backup your wallets** folder first. Thank you.
