### ISSUE TITLE
App crashed when moving window during sync

### ISSUE THREAD

**Issue by nippur72** [DeFiCh/app#798]
while the app was syncing, I moved the window on the screen and it became unresponsive (Defi Wallet not responding) then it closed. After reopening it the database became corrupt :cry: 

I can attach the log if it's needed.

**Comment by nippur72** [comment]
Here is the app log: [app.log](https://github.com/DeFiCh/app/files/6407250/app.log)

**Comment by izzycsy** [comment]
Hi @nippur72 kindly check if you turned off your firewall / anti-virus. Windows tend to have Anti Virus installed, the Anti Virus hooks into file system natively for real time detection which is a common cause of file related corruption issues. If your issue continues to persist, we can further discuss on the issue here [`Unable to Start Blockchain`](https://github.com/DeFiCh/app/issues/733). We would like to keep same issues in one thread. Thank you.
