### ISSUE TITLE
BTC Balance is showing in wallet when using CLI but not showing in wallet in the APP

### ISSUE THREAD

**Issue by Ratchetmasta** [DeFiCh/app#822]
I did a swap of DEFI for BTC and after the balance is showing 0. I checked using the CLI and it is showing the appropriate amount of btc but the balance is not showing in my wallet, so I cannot access it,  send it, or do anything with it. Please help

**Comment by Ratchetmasta** [comment]
I am afraid to post the logs because I do not know how to identify what is sensitive and what is not. I can send them if requested to an official email

**Comment by izzycsy** [comment]
Hi @Ratchetmasta , thanks for your feedback. Can you check your output via CLI, and see what does it reflect? You may also check on [DeFi Explorer](https://dex.defichain.com/mainnet/pool). If the coins are reflected there, it could be an UI bug issue that you're facing. Kindly attach a screenshot of your error and your app logs for further investigation, thank you. 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/117583337-40012080-b139-11eb-90dd-48d7f353f3aa.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/117583341-4394a780-b139-11eb-9588-f73eaeda2bdd.png">

**Comment by thedoublejay** [comment]
@Ratchetmasta you can send it to engineering@defichain.com

**Comment by Ratchetmasta** [comment]
I sent the logs in a zip to the email above from the email ratchetmasta@gmail.com. I also was informed by the community on Telegram of a CLI command last time I was able to open the app that was simmilar to"gettokenbalances {} false false True" i cant remember the specific Command, but it did show the correct BTC  balance. untill i am able to access the app again hopefully the log zip and the  info Ive provided so far will help. I am currently having the issue with the app where it says there is a corrupted blochain data and i have to start from sync node and then try to apply a snapshot each time just to get it started. usualy it takes so long something will happen and the PC will freeze or restart during the process and I need to start again.

**Comment by Ratchetmasta** [comment]
> Hi @Ratchetmasta , thanks for your feedback. Can you check your output via CLI, and see what does it reflect?
> `getbalance` — utxoDFI
> `gettokenbalances` — accountDFI + other tokens
> 
> You may also check on [DeFi Explorer](https://dex.defichain.com/mainnet/pool). If the coins are reflected there, it could be an UI bug issue that you're facing. Kindly attach a screenshot of your error and your app logs for further investigation, thank you.
> 
> <img alt="1 App log" width="339" src="https://user-images.githubusercontent.com/65014479/117583337-40012080-b139-11eb-90dd-48d7f353f3aa.png">
> 
> <img alt="2 Compress" width="511" src="https://user-images.githubusercontent.com/65014479/117583341-4394a780-b139-11eb-9588-f73eaeda2bdd.png">

Can you let me know how to utilize the Defi Explorer to find the information you are looking for? I have no clue on what im doing.

**Comment by Ratchetmasta** [comment]
> > Hi @Ratchetmasta , thanks for your feedback. Can you check your output via CLI, and see what does it reflect?
> > `getbalance` — utxoDFI
> > `gettokenbalances` — accountDFI + other tokens
> > You may also check on [DeFi Explorer](https://dex.defichain.com/mainnet/pool). If the coins are reflected there, it could be an UI bug issue that you're facing. Kindly attach a screenshot of your error and your app logs for further investigation, thank you.
> > <img alt="1 App log" width="339" src="https://user-images.githubusercontent.com/65014479/117583337-40012080-b139-11eb-90dd-48d7f353f3aa.png">
> > <img alt="2 Compress" width="511" src="https://user-images.githubusercontent.com/65014479/117583341-4394a780-b139-11eb-9588-f73eaeda2bdd.png">
> 
> Can you let me know how to utilize the Defi Explorer to find the information you are looking for? I have no clue on what im doing.

**Comment by Ratchetmasta** [comment]
> Hi @Ratchetmasta , thanks for your feedback. Can you check your output via CLI, and see what does it reflect?
> `getbalance` — utxoDFI
> `gettokenbalances` — accountDFI + other tokens
> 
> You may also check on [DeFi Explorer](https://dex.defichain.com/mainnet/pool). If the coins are reflected there, it could be an UI bug issue that you're facing. Kindly attach a screenshot of your error and your app logs for further investigation, thank you.
> 
> <img alt="1 App log" width="339" src="https://user-images.githubusercontent.com/65014479/117583337-40012080-b139-11eb-90dd-48d7f353f3aa.png">
> 
> <img alt="2 Compress" width="511" src="https://user-images.githubusercontent.com/65014479/117583341-4394a780-b139-11eb-9588-f73eaeda2bdd.png">

I sent the logs in a zip to the email above from the email ratchetmasta@gmail.com. I also was informed by the community on Telegram of a CLI command last time I was able to open the app that was simmilar to"gettokenbalances {} false false True" i cant remember the specific Command, but it did show the correct BTC balance. untill i am able to access the app again hopefully the log zip and the info Ive provided so far will help. I am currently having the issue with the app where it says there is a corrupted blochain data and i have to start from sync node and then try to apply a snapshot each time just to get it started. usualy it takes so long something will happen and the PC will freeze or restart during the process and I need to start again.

**Comment by Ratchetmasta** [comment]
Have you recieved the email with the log files?

**Comment by izzycsy** [comment]
Hi @Ratchetmasta , [v2.3.5](https://github.com/DeFiCh/app/releases/tag/v2.3.5) is out. Please read through the release notes before updating. 
Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Please give us time to investigate. Thank you.

**Comment by Ratchetmasta** [comment]
I updated. and it did not help. but I didnt know how to update manual, so i just updated by installing, is there instructions on how to update manualy i could get a link to, and should I downgrade first now iam already on 2.3.5? I If so is there a link to the instructions to do that?

**Comment by Ratchetmasta** [comment]
Was there not any discoveries into the problem when going thru the app logs and knowing that the balance is showing from the CLI? I have been having a tremendous difficulty in even getting the app to function to the point where it is synchronized so I can even run the CLI. I have backed up the 3 files in the Defi Blockchain folder, deleted them and replaced them after starting the program, as stated in the help section addressing the corrupted blockchain data issue hoping it would shorten teh loading time, but when it gets to teh snapshot aplication I am hitting Javascript errors and sometimes it just freeses when applying the snapshot after download.  I am also in need of the correct version of the CLI command I was referring to that was something like  " getbalances {} false false true " if possible.

**Comment by izzycsy** [comment]
Hi @Ratchetmasta , you need to let the wallet sync to 100% for it to present to you the correct balance. To list the breakdown of your tokens, `listaccounts {} false false true`. `getbalance` outputs the amount of utxoDFI that you've. For how-to enquires you can ask the community on [DeFiChain Telegram (EN)](https://t.me/defiblockchain). 

Back to your issue, instructions to manually update (Mac):
1. Back up your wallet.dat first
2. Download update [v2.3.5](https://github.com/DeFiCh/app/releases/tag/v2.3.5)
3. Open `DeFi-Wallet-2.3.3.dmg` file
4. Drag and replace the app

<img width="540" alt="Replace app1" src="https://user-images.githubusercontent.com/65014479/118495264-9e3f8c00-b755-11eb-9314-79813f65d98e.png">
<img width="537" alt="Replace app2" src="https://user-images.githubusercontent.com/65014479/118495295-a4356d00-b755-11eb-9086-386ae1b1e136.png">

5. Prompt: “DeFi Wallet” can’t be opened because Apple cannot check it for malicious software. > OK
6. Open System Preferences > Security & Privacy > Open Anyway 

<img width="665" alt="Open Anyway" src="https://user-images.githubusercontent.com/65014479/118495374-b9aa9700-b755-11eb-82d1-4a7779744c6a.png">


Currently the app requires, 120GB of storage & 40.51GB if you're going to apply the snapshot for faster synchronisation. Hence, you may face issues such as `unable to start blockchain` if you've insufficient storage. The team is working on the Light Wallet at the moment. Thank you for your patience.

**Comment by izzycsy** [comment]
Hi @Ratchetmasta , update [v2.4.0](https://github.com/DeFiCh/app/releases/tag/v2.4.0) is out, this is a **mandatory update**.  Please read through the release notes before updating. Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Thank you.

**Comment by izzycsy** [comment]
Hi @Ratchetmasta , [v2.4.2](https://github.com/DeFiCh/app/releases/tag/v2.4.2) is out, this is a **mandatory update**. Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @Ratchetmasta , [v2.4.5](https://github.com/DeFiCh/app/releases/tag/v2.4.5) is out, this is a **mandatory update**. Please read through the release notes before updating. This comment is to notify you about the update. App storage required is 16GB. Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
