### ISSUE TITLE
Unable to sync to 100%

### ISSUE THREAD

**Issue by miromiro321** [DeFiCh/app#853]
#### How to reproduce it (as minimally and precisely as possible):

 I shut down my computer while the Defi app was still shutting down. The next day as i started the app it wouldn't load to a 100% since. It seems that it comes to cerent Block and stops there. There was only one time since the malfunction where it loaded successfuly to 100%

#### What are your environment parameters?

- DeFi Wallet Version: 2.3.3
- Operating System (OS): Windows 10 Pro
– Current free storage capacity: 290 GB
[app_logs.zip](https://github.com/DeFiCh/app/files/6472750/app_logs.zip)

**Comment by Faucet1313** [comment]
I guess you should backup your wallet.dat, update the defi wallet, download and apply the new snapshot.

**Comment by miromiro321** [comment]
Thank you, already tried to download the snapshot a couple of times but it seems that it never integrates it

**Comment by izzycsy** [comment]
Hi @miromiro321 , when shutting down the app, you need to let it close itself, there's loading screen to prompt the user that app is shutting down, if you close it before the app closes you'll likely face a corrupted blockchain issue. 

[v2.3.5](https://github.com/DeFiCh/app/releases/tag/v2.3.5) is out. Please read through the release notes before updating. Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. 

As @Faucet1313 suggested, please backup your wallet.dat before updated to v2.3.5. Thank you.

**Comment by Faucet1313** [comment]
I'm also unable to sync 100% the version 2.3.5 on my Windows server 2019. I used the 2.3.3 to sync 100% then i installed again the 2.3.5 to get synchronized.

**Comment by izzycsy** [comment]
Hi @Faucet1313 , during the last few blocks if there's no error thrown it is still syncing, it took me about an hour to sync the last few blocks as well. Try to let it sync without interruptions — computer going to sleep / firewall.

**Comment by Faith04Brave18** [comment]
> Thank you, already tried to download the snapshot a couple of times but it seems that it never integrates it

Same here.

**Comment by izzycsy** [comment]
Hi @Faith04Brave18 , can you send your logs please? It'll help with the investigation. In the mean time, do you have sufficient storage? Currently the app requires 120GB of storage excluding temporary storage should you apply snapshot (40.51GB). Kindly clear storage and try again or wait for the Light Wallet. Please keep your `wallet.dat` safe.

**Comment by blackstormtrader** [comment]
I had one successful install and sync of the wallet app and that went flawlessly might I add. Second day I logged on and started having issues. I was given a corruption notification. Since then I cant get the sync to properly complete. I have been at this for a few days, with two different drives both using win 10 pro. One drive is 250gb and the other is 500gb. The 250gb is an ssd and 500gb is an nvme. The nvme I bought because I couldnt get the sync to complete on the ssd (excluding the first time). The several attempts I made gave me the indication that I didnt have enough capacity on my ssd. So I bought the 500gb nvme. I get that home and install win 10 and the wallet app and begin to sync. I have made several attempts on this nvme drive as well, and have not had one successful sync yet. The last attempt, froze the entire drive, or corrupted it, to the point my computer gets stuck in the pre bios screen where you hit f2 or delete to enter bios. I have tried usb recovery sticks to kali/parrot recovery sticks, (they usually work to allow me to at least format the drive while on usb live). I cant get the computer to boot as long as the nvme is installed. I will attempt to swap the nvme at the store as soon as it opens and attempt another install of win 10 and the wallet app and the sync today. 

About the last attempt: 
Fresh install of win 10 pro, updated, install wallet app all without an issue. After reading here in another post on a solution to the potential syncing issue, I copied a command to enter into the CL in the wallet app to assist in the sync. The command was to add nodes to sync to. This got the sync to start, and worked every time I had attempted the command. (I think around 4 times I used this method, 3 on the nvme and once on the ssd).

Once the sync starts I do my own thing, get some music playing and I let the computer work, checking in on the progress every 15 min or so. When it got to 11 pm, I was 80% the way there and dozed off. Wake up at 5 am and my pc is on but the screen is black with no VGA signal to the monitor and it was unresponsive. I attempted to reboot, alt ctl del, nothing, had to manually kill power to the mobo. From there I wasnt able to get into bios let alone the OS of the nvme. 

I had another attempt freeze the app and sync and gave a corruption notification after the network activity froze while syncing, and me watching a documentary on YouTube. I had to restart my to get the app to work again. 

I notice that the sync wont start for me unless I add "addnode seed.mydeficha.in:8555 add" to the CL 

I notice the pc/app can freeze 

I notice there was no difference in outcome rather I used snapshot from the app or zip file and manual extraction, then picking up on the sync. I would usually get a corrupted notification. 

I noticed that the first time I installed and synced the wallet, I had no issues what so ever, and was able to invest DFI and BTC to a pool. I managed to make a copy of my wallet.dat and made a backup.dat file and have those two files safe, but possibly that not copying the entire wallet folder from the successful install, will cost me my investment?  

IDK why I cant get the sync to work, and I fear I lost my investment. Not a great start. I hope We can resolve this issue, really do. Thanks for any help provided. I am doing my best to research and learn as I go. My intention is to best help you, help us all who have the issue here. 

Im a head to the store and get a new nvme and hope that when I come back I can use my win 10 product key again, and then continue with the installation. I dont have any logs from the nvme, I only have the ssd atm I can install the app and get logs but atm my ssd has no wallet app installed.

**Comment by blackstormtrader** [comment]
> 
> 
> I'm also unable to sync 100% the version 2.3.5 on my Windows server 2019 I tried few times but always freezing at some blocks near the end of the sync. I finally used the 2.3.3 to sync 100% then i installed again the 2.3.5 to get synchronized. I'm pretty sure the next update will resolve a lot of issues including this one.

IDK how to do this and wonder if this would work for me. I could try this after the current attempt should this not work. I appreciate any help, tips, or links. Ill do some googling to see if I cant find it myself. Cheers!

**Comment by blackstormtrader** [comment]
I finally got the sync to complete after getting the nvme replaced. The app synced and I attempted to recovery wallet but theres no $ in there . . . sigh. so wheres my 200$ in btc and dfi?

**Comment by Faucet1313** [comment]
> 
> 
> Hi @Faucet1313 , during the last few blocks if there's no error thrown it is still syncing, it took me about an hour to sync the last few blocks as well. Try to let it sync without interruptions — computer going to sleep / firewall.

Yes thank you i have no issue now regarding sync.

**Comment by jonho79** [comment]
I'm having the same issue in regards to syncing.  I've been trying for days and can't get the wallet synced.  The sync either never starts (stuck at block 0), takes forever and gets stuck prior to finishing.   Unfortunately, this has been an issue for close to a week and I have not been able to access my wallet.

**Comment by izzycsy** [comment]
Hi @jonho79 , are you on Mac / Windows? 
Do you have sufficient storage? 
What version are you on? 
Please keep you wallet.dat safe. 

Here some steps to synchronisation: 

**Option 1 — Reset & Reindex (sync from 0%)**
  1. Settings > `Reset & Reindex` 

 **Option 2 — Snapshot (sync from 90%+)** 
 1. Settings > Reset & Reindex 
 2.  Wait for app to start syncing 
 3.  Ensure you’ve at least 40.51GB of extra space 
 4. Click on `i` located at bottom-left corner of app screen  
 
<img width="244" alt="`i` to trigger Snapshot download" src="https://user-images.githubusercontent.com/65014479/119002988-efeb4f00-b9bf-11eb-85d8-b9daa2d011ee.png">

 5. Download Snapshot 

<img width="1017" alt="Snapshot (Europe)" src="https://user-images.githubusercontent.com/65014479/119003017-f7aaf380-b9bf-11eb-96f3-61f8b2a27e48.png">

<img width="1017" alt="v2 3 5 Snapshot successful 842677" src="https://user-images.githubusercontent.com/65014479/119003036-fbd71100-b9bf-11eb-9b42-a854489e1ae8.png">

**Comment by izzycsy** [comment]
Hi @miromiro321 @Faucet1313 @Faith04Brave18 @jonho79 , update [v2.4.0](https://github.com/DeFiCh/app/releases/tag/v2.4.0) is out, this is a **mandatory update**.  Please read through the release notes before updating. Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Thank you.

**Comment by miromiro321** [comment]
Hey Bella,
Thanks for always helping us out, i guess we all are really happy that someone is consistenly looking for solutions. I really appreciate that service.

Unfortently the app is still not sycing to 100% 

First I upgraded to the new Software. 

Secondly, I applied the snapshot what only took a couple of minutes. Then the app started syncing form the last block of the snapshot but it failed to surpass a sertent level, where it is stuck for a couple of hours i guess (I am not sure but I startet the sync 6 hours ago from the last block of the snapshot, im sure it should'nt take so long.) 

Thirdly, I added more nodes as you suggested to with a comand in the console

Here you have the app_logs and a info that pops up everytime i start the app, which started to occour first when the syncing problem started. It says: Update Auto-lock Time Timeout updated to 300 seconds, there is aswell a file which is named: .walletlock 
let me know if you need it asweel, altough it shows to have 0 KB

![defichain update autolock](https://user-images.githubusercontent.com/77572951/120226918-7ae20a00-c248-11eb-9798-361cfabb55f5.PNG)

[app_logs.zip](https://github.com/DeFiCh/app/files/6571681/app_logs.zip)

**Comment by defijeff** [comment]
@miromiro321 Once you're running a version that uses 1.7.2+ you may need peers which have the full chain.
See https://chainz.cryptoid.info/dfi/#!network  - click on node list for those with protocol 70017 and add the addnode= lines to your defi.conf and restart.

**Comment by izzycsy** [comment]
Hi @miromiro321 , thanks for your patience and for updating to v2.4.1, regarding the notification `Update Auto-lock Time`, it means that your app has sync to 90%+ after snapshot application, is active and running, you just need to wait for it to reach 100%. It could be your internet connection that's causes the lag.

**Comment by izzycsy** [comment]
Hi @miromiro321 @Faucet1313 @Faith04Brave18 @jonho79 @moneymining83 @helhimm @rolandwellinger @blackstormtrader @yungmann @jas32096 @SKapi1985 @pplin810 @waywardone1 @Ausafari @luzettemok1 @felik-panda , [v2.4.2](https://github.com/DeFiCh/app/releases/tag/v2.4.2) is out, this is a **mandatory update**. Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by helhimm** [comment]
Thanks for the update, without your email I would have missed it.
It would be a good idea to send an automated email to all users. I am not
using Telegram unless I have a question and I believe that I am not
the only one.

Regards
Hh

**Comment by izzycsy** [comment]
Hi @miromiro321 @Faucet1313 @Faith04Brave18 @jonho79 @moneymining83 @helhimm @rolandwellinger @blackstormtrader @yungmann @jas32096 @SKapi1985 @pplin810 @waywardone1 @Ausafari @luzettemok1 @felik-panda @helhimm , should you face the same issue regarding `Unable to start blockchain`, we can further discuss on the issue there respectively. The team is investigating. Thank you. 

[`Mac: 2.4.4 unable to start blockchain #921`](https://github.com/DeFiCh/app/issues/921)

[`Windows: 2.4.4 Sync stalled #922`](https://github.com/DeFiCh/app/issues/922) 

Please refer to [DeFiChain Announcements (EN)](https://t.me/defichain_announcements) for the latest updates. 

@helhimm , you can publish your idea on [DeFiChain Discussions](https://github.com/DeFiCh/app/discussions/categories/ideas), garner some support from the community, and the team can decide whether to implement the feature in the future. We'll continue to update users with bug related issues on Github as well.

**Comment by jonho79** [comment]
Hi Bella,

I'm getting the same "unable to start blockchain" when trying to start
Window 2.4.5 for the first time.

Any thoughts on how to resolve?

**Comment by izzycsy** [comment]
Hi @jonho79 , restart your PC and try again. If it still does not work, then delete the app and reinstall. Please `backup wallet` first before deleting anything. There's a guide in [DeFiChain Telegram (EN)](https://t.me/defiblockchain).

<img width="269" alt="Menu bar   Backup Wallet" src="https://user-images.githubusercontent.com/65014479/121954685-a1985880-cd91-11eb-84fb-b971f48ca45d.png">
