### ISSUE TITLE
Mac: Unable to start blockchain

### ISSUE THREAD

**Issue by BastianReed** [DeFiCh/app#888]
I have a Mac Book Pro with BigSur 11.3.1 

I updated the Dex on Version 2.4.0 with a snapshot. 
After the Restart, the App is freezing on the loading screen and no more works...

What can i do?
![Bildschirmfoto 2021-05-28 um 15 24 31](https://user-images.githubusercontent.com/77586161/119990644-dbfbaa80-bfc8-11eb-931b-887da387ce91.png)

**Comment by izzycsy** [comment]
Hi @BastianReed @kxkxkx111 , can you save your logs and send it here so that we can look into the issue further? Thank you. 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/120078377-dba30280-c0e1-11eb-8014-5b8a807d7db8.png">

<img width="511" alt="2 Compress" src="https://user-images.githubusercontent.com/65014479/120078379-de9df300-c0e1-11eb-8b00-ea1eaeb11c7a.png">

**Comment by Okto8on** [comment]
I have the same issue/error message with Linux AppImage 2.4.0:

![Screenshot from 2021-05-29 19-05-33](https://user-images.githubusercontent.com/76601018/120079173-045fd380-c0b3-11eb-86e8-c6293e137dea.png)

The Wallet app did start the very first time after upgrade, but after shutting down since then, the error above appears.
See app.log from [2021-05-29 16:32:41.398]

Logs:
[logs.zip](https://github.com/DeFiCh/app/files/6565114/logs.zip)

**Comment by izzycsy** [comment]
Hi @Okto8on , thanks for your logs. It could be because you were on a much older version and the app is having trouble updating. May I suggest a reinstallation. 

Can you first save your `wallet.dat` then reinstall DeFi Wallet again. 

1. If you did not specify where you stored your `wallet.dat`, proceed to backup the **entire** wallets folder, in the wallets folder you'll likely see `wallet-bak-123456789` as well, this are additional backups. 

For Mac it's located here:  Go To Folder
`/Users/<username>/Library/Application Support/Defi/wallets/`

<img width="459" alt="Mac - Go To Folder" src="https://user-images.githubusercontent.com/65014479/120080051-a8647180-c0e9-11eb-93b6-4af29d0c0da0.png">

<img width="822" alt="wallet dat location" src="https://user-images.githubusercontent.com/65014479/120079154-3722bf80-c0e5-11eb-8722-b62bb308948a.png">

2. After you've safely made a copy, proceed to delete the following folders: 

App Installation 
` /Users/<username>/Applications/DeFi Wallet.app`

 Blockchain folder 
`/Users/<username>/Library/Application Support/Defi/`

 DeFi Wallet folder
` /Users/<username>/Library/Application Support/defi-wallet`

3. Download [v2.4.0](https://github.com/DeFiCh/app/releases/tag/v2.4.0)

For Windows, select `DeFi-Wallet-Setup-2.4.0.dmg` 
<img width="501" alt="Download dmg" src="https://user-images.githubusercontent.com/65014479/120080075-cdf17b00-c0e9-11eb-99ea-5718eef56a5a.png">

4. After installing v2.4.0 and syncing to 100%, `Restore wallet via backup` (wallet.dat), use the wallet.dat that you've previously backed up (step 1)

<img width="1021" alt="Restore wallet from backup" src="https://user-images.githubusercontent.com/65014479/120079091-004ca980-c0e5-11eb-8194-b43efda7a7b0.png">

Your wallet balance should reflect as per the `wallet.dat` you selected, if it's incorrect, select another `wallet.dat` from the wallets folder and try again.

**Comment by kxkxkx111** [comment]
Problem has been solved. You need to update your macbooks on the latest firmware

**Comment by Okto8on** [comment]
@izzycsy I have made a full de-installation and full new installation and restored a backup, as you suggested. It took very long to fully sync (more than 12h) but it works now. Thank you.

**Comment by BastianReed** [comment]
> Hi @BastianReed @kxkxkx111 , can you save your logs and send it here so that we can look into the issue further? Thank you.
> 
> <img alt="1 App log" width="339" src="https://user-images.githubusercontent.com/65014479/120078377-dba30280-c0e1-11eb-8014-5b8a807d7db8.png">
> 
> <img alt="2 Compress" width="511" src="https://user-images.githubusercontent.com/65014479/120078379-de9df300-c0e1-11eb-8b00-ea1eaeb11c7a.png">

now it works after some resyncs and two reinstallations.

**Comment by izzycsy** [comment]
Hi @Okto8on @BastianReed @kxkxkx111 , [v2.4.2](https://github.com/DeFiCh/app/releases/tag/v2.4.2) is out, this is a **mandatory update**. Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @Okto8on @BastianReed @kxkxkx111 @tweedleDumb-69 , should you face the same issue regarding [`Unable to start blockchain`], we can further discuss on the issue there respectively. The team is investigating. Thank you. 

[`Mac: 2.4.4 unable to start blockchain #921`](https://github.com/DeFiCh/app/issues/921)

[`Windows: 2.4.4 Sync stalled #922`](https://github.com/DeFiCh/app/issues/922) 

Please refer to [DeFiChain Announcements (EN)](https://t.me/defichain_announcements) for the latest updates.
