### ISSUE TITLE
Balance of LP Token BCH-DIF is not correct

### ISSUE THREAD

**Issue by baludwi** [DeFiCh/app#896]
#### Actual behavior:
Just the balance of one of my addresses is shown as balance for BCH-DFI. Also the cli command "gettokenbalances" shows me to less balance for BCH-DFI. This is since 2.4.0

The balances of other LP-Tokens are correct.
 
But when i check my addresses in https://dex.defichain.com/mainnet/pool, all balances are correct 

#### Expected behavior:
the sum of all balances of all my addresses for BCH-DFI has to shown in DeFi Wallet.

#### What are your environment parameters?

- DeFi Wallet Version: 2.4.0
- Operating System (OS): Mac OS 11.4
– Current free storage capacity: 195 GB

**Comment by izzycsy** [comment]
Hi @baludwi , update [v2.4.2](https://github.com/DeFiCh/app/releases/tag/v2.4.2) is out, this is a **mandatory update**.  Please read through the release notes before updating. Do give a thumbs up to this comment if your issue has been resolved, otherwise, please send new information (include screenshots) and app logs. Thank you.
