### ISSUE TITLE
Sync stuck

### ISSUE THREAD

**Issue by gabriello79** [DeFiCh/app#910]
Dear guys,

I'm using defi wallet since a while. This morning it was syncing the blockchain, but at a certain point stopped to synch and it is now refusing to keep syncing. I upgraded the app to the last version, started from the snapshot, but the app is still synced at the same point of the snapshot, with no progress.

#### Actual behavior: app is not syncing, after upgrading and downloaded the snapshot nothing has changed

- DeFi Wallet Version: 2.4.3
- Operating System (OS): Win 10 pro
– Current free storage capacity: 262 GB

#### Anything else we need to know? It was syncing correctly, and suddenly stopped

[log.zip](https://github.com/DeFiCh/app/files/6590702/log.zip)

**Comment by izzycsy** [comment]
Hi @gabriello79 , it could be because you were on a much older version and the app is having trouble updating. May I suggest a reinstallation. 

Can you first **Backup Wallet** then reinstall DeFi Wallet again. 

<img width="287" alt="Menu bar   Backup Wallet" src="https://user-images.githubusercontent.com/65014479/120626301-1bc50500-c495-11eb-97fa-4ef5ab020952.png">


1. If you did not specify where you stored your `wallet.dat`, proceed to backup the **entire** wallets folder, in the wallets folder you'll likely see `wallet-bak-123456789` as well, these are additional wallet backups. 

For Windows it's located here:  
`C:\Users\<username>\AppData\Roaming\DeFi Blockchain\wallets\`

<img width="822" alt="wallet dat location" src="https://user-images.githubusercontent.com/65014479/120079154-3722bf80-c0e5-11eb-8722-b62bb308948a.png">

2. After you've safely made a copy, proceed to delete the following folders: 

**App Installation** 
`C:\Users\username\Program Files\DeFi Wallet`

 **Blockchain folder** 
`C:\Users\<username>\AppData\Roaming\DeFi Blockchain\`
_*Remember to backup `wallets` folder_

 **DeFi Wallet folder**
` C:\Users\username\AppData\Roaming\defi-wallet`

3. Download [v2.4.3](https://github.com/DeFiCh/app/releases/tag/v2.4.3)

For Windows, select `DeFi-Wallet-Setup-2.4.3.exe` 

<img width="476" alt="Download exe v2 4 3" src="https://user-images.githubusercontent.com/65014479/120626879-af96d100-c495-11eb-960a-5d32000ca508.png">


4. After installing v2.4.3 and syncing to 100%, `Restore wallet via backup` (wallet.dat), use the wallet.dat that you've previously backed up (step 1)

<img width="1021" alt="Restore wallet from backup" src="https://user-images.githubusercontent.com/65014479/120079091-004ca980-c0e5-11eb-8194-b43efda7a7b0.png">

Your wallet balance should reflect as per the `wallet.dat` you selected, if it's incorrect, select another `wallet.dat` from the wallets folder (step 1) and try again.

**Comment by izzycsy** [comment]
Hi @gabriello79 , if the app is syncing and seems stuck but no error was thrown, give it some more time to load. Can you try to `Reindex` and re-sync to 100%.

**How to Reindex:** 
1. Go to the app's Menu Bar > Wallet > `Reindex Wallet`
- you may choose to `Backup Wallet` first if you have not made a backup before

<img width="343" alt="Menu bar   Reindex Wallet" src="https://user-images.githubusercontent.com/65014479/120220164-e8089600-c26e-11eb-8843-3ccdc602a13d.png">

2. Node will proceed to restart
3. After which, at the bottom left hand corner, click on `i` to trigger Snapshot

<img width="234" alt="Preparing sync" src="https://user-images.githubusercontent.com/65014479/120387543-a229fb80-c35c-11eb-8389-a6f582551a34.png">

<img width="1015" alt="Snapshot (Europe) v2 4 3" src="https://user-images.githubusercontent.com/65014479/120627896-b5d97d00-c496-11eb-9ca1-e0db66ff34b7.png">


4. During the snapshot download, the app will download and unpack the snapshot contents. 

**It is recommended:** 
- ensure sufficient storage (temporary) for snapshot 
- to leave the app running with good internet connection
- turn off auto-lock / screen saver on your PC to prevent interruption

<img width="1018" alt="Downloading Snapshot" src="https://user-images.githubusercontent.com/65014479/120308553-ceb32880-c306-11eb-87bb-5b5d9fa28a42.png">


5. When snapshot is unpacked & successful, user may select `DELETE SNAPSHOT & RESTART`

<img width="1019" alt="v2 4 3 Snapshot successful 893149" src="https://user-images.githubusercontent.com/65014479/120628019-d1448800-c496-11eb-8c09-3d710624f6eb.png">


6. After your app restarts, synchronisation should begin at ~90%, leave your app running till it reaches 100%.

**Comment by gabriello79** [comment]
Thank you @izzycsy I restarted the app few times, reindexed and now it is working again...

:-)

**Comment by supervolot** [comment]
I got my servers live again. I change to SPV=1 line in the defi.conf; and delete all folders (except "wallet") and start the wallet with snapshot 893149.zip
