### ISSUE TITLE
After applying Liquidity - no added liquidity to my account

### ISSUE THREAD

**Issue by chthkuh** [DeFiCh/app#925]
#### How to reproduce it (as minimally and precisely as possible):

After adding Liquidity to LTC-DFI pool - No added shares to my account shown.

#### What are your environment parameters?

- DeFi Wallet Version: 2.4.5
- Operating System (OS): Windows 10
– Current free storage capacity: 200GB

#### Anything else we need to know?

I do have the Transaction hash for info if needed

**Comment by thedoublejay** [comment]
Hi @chthkuh, can you type `listpoolshares {"start":0} true true` in the CLI? Let me know if you can see any response

**Comment by seb18781** [comment]
Hi #943 was closed to keep the no of issues low, but it is still a bug.

A transaction to add liquidity to LP (dBTC-DFI) was skipped:
https://mainnet.defichain.io/#/DFI/mainnet/tx/62cb53cdad8eb5c4eaebf07e647f04d55a3d1dca55d401dc41691a55367cc5e3

https://dex.defichain.com/mainnet/tx/62cb53cdad8eb5c4eaebf07e647f04d55a3d1dca55d401dc41691a55367cc5e3

I have not got my coins back ( I think it is only a display error in the DefiWallet App) 

![image](https://user-images.githubusercontent.com/69623583/120996198-68a32700-c786-11eb-97d4-b0972552030a.png)


#### Expected behavior:

The calculated amount of coins shown in the DefiWallet should incorporate coins which were not sent correctly to a liquidity pool and are thus still in your wallet.

**Comment by nippur72** [comment]
I see that the transaction is confirmed, do you still have the issue?

**Comment by seb18781** [comment]
For somehow, it seems it has skipped the receiver-address. Maybe because I had no UTXO coins? The problem occured on my office notebook. At home, the sum of all token is correct. No problem any longer!

**Comment by izzycsy** [comment]
Hi @seb18781 , thanks for the confirmation, in the future, thank you for your patience.
