### ISSUE TITLE
Liquidity Pool doesn't add Token

### ISSUE THREAD

**Issue by homescreen2** [DeFiCh/app#948]
#### Actual behavior: 
Liquidity Pool doesn't add my token to a Pool. ( BTC-DFI)
#### How to reproduce it (as minimally and precisely as possible):

Create Liquidity Pool

#### What are your environment parameters?

- DeFi Wallet Version: 2.4.5
- Operating System (OS): MAC Big Sur 11.4 
– Current free storage capacity: 1TB

**Comment by izzycsy** [comment]
Hi @homescreen2 , could you describe your issue further? Was an error thrown when trying to add liquidity or was the loading rather long but no error was thrown?

**Comment by izzycsy** [comment]
Hi @homescreen2 , [v2.5.0](https://github.com/DeFiCh/app/releases/tag/v2.5.0) is out. Please read through the release notes before updating. Do give a thumbs up to this comment if your issue has been resolved, otherwise, you may reopen this issue with new information (include screenshots) and app logs. Thank you.
