### ISSUE TITLE
Funds are missing, no .dat available, Status Code 500

### ISSUE THREAD

**Issue by MKR32** [DeFiCh/app#952]
#### How to reproduce it (as minimally and precisely as possible):

Hello,
can you possibly help me? These are my funds from the DeFi wallet. It's about the DeFi app, now DeFi wallet.
I cannot restore my funds with the seed. I have not yet been able to create a .dat file, as this was not possible in the earlier versions. I have a .TXT wallet backup. I read this in via the command line "Importwallet" in the DeFi app version 2.3.0 and it then shows zero. But that can't be right. Because the amounts (DFI and BTC) that I sent from Cake to the app have arrived. I could still see that in the app. Only when my PC crashed in January while the app was open did the balances / funds disappear when it started up afterwards. Since then, I've been asking for help in all possible places.

Do you have an idea why?

Thanks in advance!
Best regards
Marcel

#### What are your environment parameters?

- DeFi Wallet Version: 2.5.0
- Operating System (OS): MS Windows 10
– Current free storage capacity: 128GB

#### Anything else we need to know?

[app_logs.zip](https://github.com/DeFiCh/app/files/6624555/app_logs.zip)

**Comment by izzycsy** [comment]
Hi @MKR32 , based on your logs, your `wallets` folder is missing, before you computer crashed, did you make a backup of it? Does your wallet have a passphrase (encryption)? If yes, you need your `wallet.dat` to restore you wallet. If no — wallet does not have passphrase, you’ll likely still be able to restore wallet via mnemonic seed, if you started using DeFi Wallet from before v2.3.0. 

After v2.3.0, wallet passphrase (encryption) was introduced, users who created a passphrase have to rely on their `wallet.dat` when restoring.

To find your `wallet.dat` on Windows: 
`C:\Users\<username>\AppData\Roaming\DeFi Blockchain\wallets\`

In the wallets folder you'll likely see `wallet-bak-123456789` as well, these are additional wallet backups. 

<img width="822" alt="wallet dat location" src="https://user-images.githubusercontent.com/65014479/121404047-25b3a000-c98e-11eb-96a5-055ccb23d494.png">

1. Exit Wallet
<img width="236" alt="Exit Wallet" src="https://user-images.githubusercontent.com/65014479/121404146-3e23ba80-c98e-11eb-8a16-576f9a234c7b.png">

2. Select any one of the `wallet.dat` and `Restore Wallet via backup`: 
<img width="1021" alt="Restore wallet from backup" src="https://user-images.githubusercontent.com/65014479/121404183-4845b900-c98e-11eb-9e40-67de0ccc0bc1.png">

**Comment by MKR32** [comment]
Hi @izzycsy,
thank you very much for your super quick response.
Sadly I don't have a backup of my wallets folder.
The last couple days after your answer I treid to find these folder. But it is lost with my PC crash in january and the only thing I have are the 24 words to my account, thats all.
And with these I tried a thousand times to restore it, but no success.

Is there any other chance to get my funds back?

**Comment by izzycsy** [comment]
Hi @MKR32 , if you did any transactions after having a passphrase the wallet.dat becomes encrypted — your transactions & tokens since are contained in your encrypted `wallet.dat`. Mnemonic seed will only work if your wallet.dat has no encryption. In other words, if you `restore wallet via mnemonic seed`, it would present the balance that was prior activation of passphrase. 

To answer your question, if your wallet has encryption enabled, you can only `restore it via wallet backup`. Before your PC crashed, did you make any backup? If no, then I'm sorry to say, you won't be able to access your funds as it's stored in your encrypted wallet.dat. Kindly understand that your wallet is your responsibility and PC crashing is beyond our control. Perhaps you can try to engage with your PC's repair centre to see if the lost files can be retrieved. Other than that, that's all I can help at this point. This issue will be closed. Best of luck.
