### ISSUE TITLE
Sync stops at 878369 with checkpoints=0

### ISSUE THREAD

**Issue by defiuser2** [DeFiCh/app#986]
When running a full sync with checkpoints=0 the process stops at 878369 for now 24 hrs. This was tested twice on windows and mac with node version 1.7.11

**Comment by izzycsy** [comment]
Hi @defiuser2 , can you attach your logs for investigation please? Which snapshot region did you select? 

<img width="339" alt="1 App log" src="https://user-images.githubusercontent.com/65014479/123556760-985eb100-d7bf-11eb-80bc-40aaedd6981b.png">

![Uploading 2 Compress.png…]()

**Comment by izzycsy** [comment]
Hi @defiuser2 , update [v2.6.0](https://github.com/DeFiCh/app/releases/tag/v2.6.0) is out, this is a **mandatory update**.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @defiuser2 , update [v2.6.1](https://github.com/DeFiCh/app/releases/tag/v2.6.1) is out.  Please read through the release notes before updating. _This comment is to notify you about the update._ 

If your issue persist, kindly reopen the issue with the following information. 
**Actual behavior:**

**Expected behavior:**

**How to reproduce it (as minimally and precisely as possible):**

**What are your environment parameters?**
DeFi Wallet Version:
Operating System (OS):
Current free storage capacity:
Anything else we need to know?
