### ISSUE TITLE
Snapshot with historical data 

### ISSUE THREAD

**Issue by defiuser2** [DeFiCh/app#987]
Hi there,

as the current snapshots are currently very helpful I'd also like to have this without the pruning part so (checkpoints=0) enabled.
This would help on the app side to get all rewards back and also on the masternode side.
So I could run my masternode with all data to support the network without waiting several days for a sync.

**Comment by izzycsy** [comment]
Hi @defiuser2 , without pruning, your app storage would go beyond 150GB because you're storing every single block on your local — hence the implementation of pruning. 

As for rewards not displaying, you can try to reindex (without snapshot but it'll take you likely 12 hours to sync up) to see if the tx history for rewards appear, or wait for another app release. Some users reported that they no longer face the [`missing tx history`](https://github.com/DeFiCh/app/issues/891) issue since v2.5.0, although some new users started to face it. Please send screenshots & logs to [`missing tx history`](https://github.com/DeFiCh/app/issues/891) if you want us to investigate. We would like to keep same issues in one thread. Thank you.
