### ISSUE TITLE
Export CSV: Limit to last

### ISSUE THREAD

**Issue by johnnyknoxville1337** [DeFiCh/app#992]
#### Actual behavior:
While exporting the CSV file for past transactions the number is limited to 6 figures.
While we have reached the 1 millionth block now, the user should be able to configure 7 figures there to have the whole transaction history available for export.

#### Expected behavior:
put 7 figures in the limit to last field

#### How to reproduce it (as minimally and precisely as possible):
try to put 7 figures in the field 

#### What are your environment parameters?

- DeFi Wallet Version: 2.5.2
- Operating System (OS):  Linux
- Current free storage capacity: 300GB

**Comment by izzycsy** [comment]
Hi @johnnyknoxville1337 , thanks for your feedback, will convey it to the team. Posting non-bug related issues here will eventually turn stale. You could copy & paste your idea on DeFiChain Discussions so that it does not turn stale, at the same time garner more support from the community. The team is in the midst of working on the Light Wallet, hence I cannot provide you with a timeline on this yet. Thank you.

**Comment by izzycsy** [comment]
Hi @johnnyknoxville1337 , update [v2.6.0](https://github.com/DeFiCh/app/releases/tag/v2.6.0) is out, this is a **mandatory update**.  Please read through the release notes before updating. _This comment is to notify you about the update._

**Comment by izzycsy** [comment]
Hi @johnnyknoxville1337 , I've notified the team of this feedback, however the team is currently focusing on Light Wallet so I do not have a timeline on this at the moment, regarding the issue [`Export Button is clickable to early`](https://github.com/DeFiCh/app/issues/979), we can further discuss on the issue there. We would like to keep same issues in one thread. Thank you.
